### ISSUE TITLE
Kivy does not support RTL

### ISSUE THREAD

**Issue by SaeidJavadi** [kivy/kivy#8001] opened 2022-09-08 19:29 UTC
### Kivy does not support RTL
Thanks for your great library
But there are several big problems
kivy fonts do not support many languages, such as Chinese Persian Arabic and ...
And your library does not support RTL (only LTR supports) In the event that must be a capability in your components to adjust RTL or LTR (as a parameter)
For example some methods or components cannot be adjusted RTL to display text and this is a problem
Please check and solve these elementary problems
![Kivy](https://user-images.githubusercontent.com/53658372/189209321-2c28862c-f418-49bc-b777-4903195b6712.PNG)

Thank you for not simply rejecting these problems

### Versions
* OS: windows 10
* Python: 3.10.5
* Kivy: 2.1.0

**Comment by masoodcmpy** [comment] 2023-01-15 20:53
It's my problem
Kivy is really great
I wish this problem would be solved soon
Because of this problem, I have to go to Kotlin and Android Studio

**Comment by misl6** [comment] 2023-01-16 17:56
Duplicate of https://github.com/kivy/kivy/issues/7704

**Closed by misl6** 2023-01-16 17:56 UTC
