### ISSUE TITLE
TextInput Bubble disappears immediately after it appears

### ISSUE THREAD

**Issue by brianddk** [kivy/kivy#6473] opened 2019-08-14 23:52 UTC
### Versions

* Python: Python 3.6.8
* OS: Ubuntu 18.04 u18-build 4.15.0-55-generic x86_64
* Kivy:  master ce9b5719 
* Kivy installation method: Python 3.6 Nightly wheel
* Buildozer: 40 ( master 7a0ef4f ) from pip tarball 
* Android: 8.0.0
* Android NDK: 17.2.4988734
* Android Build Tools: 29.0.2
* Android API target: 27 

### Description

***Observation:*** On Android, when selecting text from a TextInput, the cut/copy/paste bubble only shows up for a few milliseconds then disappears.  Far to quick to be of any use.

***Expectation:*** The cut/copy/paste bubble should remain visible for multiple seconds or until focus on TextInput is lost.

### Code and Logs

```python
from kivy.app import App
from kivy.uix.textinput import TextInput

class Sample(App):
    def build(self):
        return TextInput(text="Test Text")

_app = Sample()
_app.run()
```

**Comment by shakna-israel** [comment] 2019-08-16 01:07
Being able to control dismiss in [#6432](https://github.com/kivy/kivy/pull/6432) should go a ways to working around this, but the ms timing of the bubble vanishing is definitely "unexpected" behaviour.

---

I hit this as well, under:

Python: 3.7.4
Host OS: Arch Linux 5.2.8-arch1-1-ARCH
Buildozer: 40 (master 7a0ef4f10c)
Android: 5.1.1

**Comment by btonasse** [comment] 2020-05-22 12:36
I'm having the same issue on android 10. Is there anything I need to do on the code to prevent it from disappearing?

**Comment by rachiteagles** [comment] 2020-10-07 19:22
i solved this problem.

i created a CustomTextInput class that inherits from TextInput.
After that I overrided the function _hide_cut_copy_paste to comment out bubble.hide().
PFB code snippet

class CustomTextInput(TextInput):
    def _hide_cut_copy_paste(self, win=None):
        bubble = self._bubble
        if not bubble:
            return

        **#bubble.hide()**

Also, replaced TextInput with CustomTextInput in .kv file

**Comment by Zen-CODE** [comment] 2020-10-14 18:11
I think this could be solved by this merge:

    https://github.com/kivy/kivy-ios/issues/499

Would it be possible to test using a checkout of master that included this fix?

**Comment by tshirtman** [comment] 2021-03-27 13:31
This has been confirmed to be fixed in 2.0.0, closing :).

**Closed by tshirtman** 2021-03-27 13:31 UTC

**Comment by duarteleonardosales** [comment] 2021-03-31 01:50
The problem continues in the new version 2.
I solved the problem in the code of my work using hint from @rachiteagles . Thanks.

**Comment by Stepan0806** [comment] 2022-02-14 15:22
> This has been confirmed to be fixed in 2.0.0, closing :).

I still have this problem on kivy 2.0.0.

**Comment by Stepan0806** [comment] 2022-02-14 21:33
@Zen-CODE  Yes it occurs in the minimal example. I builded apk on [this](https://github.com/Zen-CODE/kivybits/tree/master/KivyCompleteVMl) VM and only upgraded kivy version to 2.0.0. The python version there is 3.6.8. I run app on MIUI 12.0.11

**Comment by Zen-CODE** [comment] 2022-02-15 15:54
@Stepan0806 Can't reproduce this. Work fine me. So, to confirm,, this happens on your desktop OS? MIUI? That's quite niche and untested. Would  it be possible to test on an Ubuntu-based distro?

**Comment by Stepan0806** [comment] 2022-02-15 17:58
@Zen-CODE MIUI is modified Android. It is OS on Redmi phone.

**Comment by Zen-CODE** [comment] 2022-02-16 18:56
@Stepan0806 I'm testing on Android 11 on an Oppo A74 phone (which also uses ColorOS - a tweaked version of Android). And the bubble stays until dismissed....I can only think it's either a peculiarity of MIUI or the Android version? Is it possible for you to test on another phone?

**Comment by Stepan0806** [comment] 2022-02-16 21:53
@Zen-CODE I'm sorry for disturbing you. I just ran `buildozer android clean` and now all works fine. Sorry
