### ISSUE TITLE
Packaging on Windows with error gstplayer playbin

### ISSUE THREAD

**Issue by taisreis** [kivy/kivy#4931] opened 2017-01-17 20:29 UTC
I created a windows package kivy(1.9.1) using PyInstaller(3.2) and I followed the instructions from the documentation but when I run the .exe get the message error "Unable to create a playbin".
I have the Kivy dependencies installed and the GStreamer(1.11.1). 
My output: https://gist.github.com/taisreis/006015cd5e20d1ed5801026775174230

**Comment by dessant** [comment] 2017-01-17 20:35
This may help: https://github.com/kivy/kivy/issues/4652.

**Comment by taisreis** [comment] 2017-01-17 21:03
I've already see this and the PyInstaller version I'm using is already with this bug fixed.

**Comment by Akay7** [comment] 2017-01-19 05:00
I'm get same trouble
`
 kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin
Failed to execute script main
`
I'm look at stack trace and to know about I get that trouble after 
`
SoundsLoader.load('music.ogg')
`

**Comment by matham** [comment] 2017-01-19 05:37
Are you sure you have the fixed pyinstaller version? Because it's not merged yet.

**Comment by matham** [comment] 2017-01-19 05:39
If you do have the fixed version, can you please do what was done in the other issue so we could figure out what the issue is: https://github.com/kivy/kivy/issues/4652#issuecomment-251164457 and https://github.com/kivy/kivy/issues/4652#issuecomment-251313539.

**Comment by taisreis** [comment] 2017-01-24 20:32
Hi martham
It's really this bug. I think so that the bug was already fixed but I was wrong. 
Thank you

**Closed** 2017-01-25 15:16 UTC

**Comment by blurymind** [comment] 2018-03-10 12:56
this is still borked
https://github.com/kivy/kivy/issues/5651

**Comment by hay318** [comment] 2018-10-14 20:06
Try this: `brew install gst-plugins-bad`
