### ISSUE TITLE
P4A is broken with kivy==master

### ISSUE THREAD

**Issue by tito** [kivy/kivy#6419] opened 2019-07-14 19:51 UTC
The recent changes from #6397 make it impossible to compile kivy==master with P4A:

Because setuptools is not installed in P4A by default, and kivy doesn't depend of it, it failed to generate the Cython files, then failed to compile:

```
 armeabi-v7a
[INFO]:    kivy apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in kivy
[INFO]:    -> directory context /home/tito/.build/buildozer-cubes/android/platform/build/build/other_builds/kivy-python3/armeabi-v7a__ndk_target_21/kivy
[INFO]:    -> running python -c import sys; print(sys.path)
[INFO]:    Trying first build of kivy to get cython files: this is expected to fail                                                                              
[INFO]:    -> running python setup.py build_ext -v
Exception in thread background thread for pid 29748:                                                                                                             
Traceback (most recent call last):
  File "/home/tito/.conda/envs/connectage-app3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/tito/.conda/envs/connectage-app3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/tito/.build/buildozer-cubes/android/platform/build/build/other_builds/hostpython3/desktop/hostpython3/native-build/python setup.py build_ext -v

  STDOUT:
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    from setuptools import setup, Extension, find_packages
ModuleNotFoundError: No module named 'setuptools'


  STDERR:


[INFO]:    kivy first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize kivy/_event.pyx
[INFO]:    -> running cython ./kivy/_event.pyx

[INFO]:    Cythonize kivy/properties.pyx                                                                                                                         
[INFO]:    -> running cython ./kivy/properties.pyx
Exception in thread background thread for pid 29761:                                                                                                             
Traceback (most recent call last):
  File "/home/tito/.conda/envs/connectage-app3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/tito/.conda/envs/connectage-app3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/home/tito/.local/lib/python3.7/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /home/tito/.conda/envs/connectage-app3/bin/cython ./kivy/properties.pyx

  STDOUT:
/home/tito/.conda/envs/connectage-app3/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/tito/.build/buildozer-cubes/android/platform/build/build/other_builds/kivy-python3/armeabi-v7a__ndk_target_21/kivy/kivy/properties.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
           'NumericProperty', 'StringProperty', 'ListProperty',
           'ObjectProperty', 'BooleanProperty', 'BoundedNumericProperty',
           'OptionProperty', 'ReferenceListProperty', 'AliasProperty',
           'DictProperty', 'VariableListProperty', 'ConfigParserProperty')

include "include/config.pxi"
^
------------------------------------------------------------

kivy/properties.pyx:272:0: 'include/config.pxi' not found
```

**Comment by matham** [comment] 2019-07-14 21:59
I believe we just need to add setuptools as a dependency of the kivy recipe. @inclement indicated on discord IIRC that this would be the solution if there are issues with the recipe once merged. Similarly for kivy-ios (IIRC, when I looked there setuptools seemed to be available).

**Comment by opacam** [comment] 2019-07-15 11:34
Ei, @tito, what version of p4a did you use?

I've been trying to reproduce this with latest changes in p4a's develop branch and the p4a's testapp (sqlite3_openssl) and I was unable to reproduce this, even modifying the testapp using this requirements:
  - `'requirements':'kivy==master,python3'`

I got this build order:
  - `Recipe build order is ['hostpython3', 'libffi', 'openssl', 'sdl2_image', 'sdl2_mixer', 'sdl2_ttf', 'sqlite3', 'python3', 'sdl2', 'setuptools', 'six', 'pyjnius', 'android', 'kivy']`

as you see `setuptools` is built before kivy, so  the build shouldn't fail.

In latest develop branch we insert some dependencies for all bootstraps (`android`), see it in [here](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/bootstrap.py#L83), and the `android recipe` adds [pyjnius as a dependency](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/android/__init__.py#L17) which [depends on six recipe](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/pyjnius/__init__.py#L14)  which [depends on setuptools](https://github.com/kivy/python-for-android/blob/develop/pythonforandroid/recipes/six/__init__.py#L8)...so we got installed `setuptools` before `kivy` .

**BTW**, this last dependency of `setuptools` was merged yesterday night in this pull request kivy/python-for-android#1913, so you probably tested just before this merge.

@tito, could you check again with current p4a's develop branch and let us know please?

**Comment by inclement** [comment] 2019-07-28 22:16
setuptools is now explicitly listed as a Kivy dependency in p4a master, and tests confirm it's working, so this should definitely be resolved. I think the only reason to see it will be if using kivy==master from an older python-for-android version, in which case adding setuptools explicitly to the requirements should work (technically isn't guaranteed since the graph code won't know what order to do things in, but unlikely to end up backwards).

**Closed by inclement** 2019-07-28 22:16 UTC
Labels: awaiting-reply, important
