### ISSUE TITLE
Markup for TextInput, like Label

### ISSUE THREAD

**Issue by badjano** [kivy/kivy#8318] opened 2023-07-15 21:37 UTC
I want to be able to make any part of my text in different colors or style while writing on TextInput

I tried CodeInput and trying to put Label inside TextInput but could not make it work as I want.

I had to add another issue since no one would re-open [this one](https://github.com/kivy/kivy/issues/459)

**Comment by brvier** [comment] 2023-08-06 18:50
CodeInput is made for that. 

Take a look at : 
- https://github.com/brvier/MOrg/blob/674b903ed49e9b721b947a7f5d25d78e62378f24/main.kv#L34
- https://github.com/brvier/MOrg/blob/674b903ed49e9b721b947a7f5d25d78e62378f24/main.py#L418

**Comment by badjano** [comment] 2023-08-07 02:50
> CodeInput is made for that.

I tried codeinput but was not able to achieve the results I needed, do you have any tutorial on that? your code is kinda confusing

**Comment by Julian-O** [comment] 2023-10-29 16:52
It seems that the advice you were given was in the first Issue was it wasn't provided by Kivy, but you could implement it yourself. If you think it is worth putting into Kivy, please submit a PR.

Closing as a duplicate of #459.

**Closed by Julian-O** 2023-10-29 16:52 UTC
Labels: Type: Feature
