### ISSUE TITLE
Unnecessary black window appears when using Kivy and Multiprocessing

### ISSUE THREAD

**Issue by emoto-yasushi** [kivy/kivy#8499] opened 2023-12-07 21:03 UTC
**Software Versions**
* Python:3.9.10
* OS:Windows11
* Kivy:2.2.1
* Kivy installation method:pip install

**Describe the bug**

 I noticed that when I add some Kivy library Imports, an unwanted black window appears.
This problem seems to occur when using Kivy and Multiprocessing at the same time.

The following code is the normal code. 
The black window does not appear.

```
    from kivy.app import App
    from kivy.uix.widget import Widget
    from multiprocessing import Process, Value
    from kivy.lang import Builder
    """
    from kivy.uix.checkbox import CheckBox
    from kivy.uix.spinner import Spinner
    from kivy.properties import StringProperty,NumericProperty,ObjectProperty, BooleanProperty
    from kivy.core.window import Window
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.popup import Popup
    from kivy.uix.treeview import TreeView, TreeViewLabel, TreeViewNode
    from kivy.uix.label import Label
    from kivy.uix.textinput import TextInput
    from kivy.uix.progressbar import ProgressBar
    from kivy.uix.button import Button
    """
    Builder.load_string("""
    <TextWidget>:
    	BoxLayout:
    		orientation: 'vertical'
    		size: root.size
    
    		Button:
    			id: button1
    			text: "start"
    			font_size: 48
    			on_press: root.buttonClicked()
    		Label:
    			id: lab
    			text: 'result'
    """)
    
    
    class TextWidget(Widget):
    	def __init__(self, **kwargs):
    		super(TextWidget, self).__init__(**kwargs)
    		self.process_test = None
    		self.proc = None
    
    		# shared memory
    		self.count = Value('i', 0)
    		self.proc = start_process(self.count)
    		self.ids.button1.text = "stop"
    		
    	def buttonClicked(self):
    		if self.ids.button1.text == "start":
    			
    			self.ids.button1.text = "stop"
    		else:
    			if self.proc:
    				self.proc.kill()
    			self.ids.button1.text = "start"
    			self.ids.lab.text = str(self.count.value)
    
    
    class TestApp(App):
    	def __init__(self, **kwargs):
    		super(TestApp, self).__init__(**kwargs)
    		self.title = 'testApp'
    
    	def build(self):
    		return TextWidget()
    
    def start_process(count):
    	process_test = Process(target=p_test, args=[count], daemon=True)
    	process_test.start()
    	return process_test
    
    def p_test(count):
    	i = 0
    	while True:
    		print(i)
    		i = i + 1
    		with count.get_lock():
    			count.value = i
    
    if __name__ == '__main__':
    	TestApp().run()
```

However, when uncommented out, a black screen appears, with the GUI hidden behind it, which must be accessed through the Task Manager.

```
    from kivy.app import App
    from kivy.uix.widget import Widget
    from multiprocessing import Process, Value
    from kivy.lang import Builder
    
    from kivy.uix.checkbox import CheckBox
    from kivy.uix.spinner import Spinner
    from kivy.properties import StringProperty,NumericProperty,ObjectProperty, BooleanProperty
    from kivy.core.window import Window
    from kivy.uix.boxlayout import BoxLayout
    from kivy.uix.popup import Popup
    from kivy.uix.treeview import TreeView, TreeViewLabel, TreeViewNode
    from kivy.uix.label import Label
    from kivy.uix.textinput import TextInput
    from kivy.uix.progressbar import ProgressBar
    from kivy.uix.button import Button
    
    Builder.load_string("""
    <TextWidget>:
    	BoxLayout:
    		orientation: 'vertical'
    		size: root.size
    
    		Button:
    			id: button1
    			text: "start"
    			font_size: 48
    			on_press: root.buttonClicked()
    		Label:
    			id: lab
    			text: 'result'
    """)
    
    
    class TextWidget(Widget):
    	def __init__(self, **kwargs):
    		super(TextWidget, self).__init__(**kwargs)
    		self.process_test = None
    		self.proc = None
    
    		# shared memory
    		self.count = Value('i', 0)
    		self.proc = start_process(self.count)
    		self.ids.button1.text = "stop"
    		
    	def buttonClicked(self):
    		if self.ids.button1.text == "start":
    			
    			self.ids.button1.text = "stop"
    		else:
    			if self.proc:
    				self.proc.kill()
    			self.ids.button1.text = "start"
    			self.ids.lab.text = str(self.count.value)
    
    
    class TestApp(App):
    	def __init__(self, **kwargs):
    		super(TestApp, self).__init__(**kwargs)
    		self.title = 'testApp'
    
    	def build(self):
    		return TextWidget()
    
    def start_process(count):
    	process_test = Process(target=p_test, args=[count], daemon=True)
    	process_test.start()
    	return process_test
    
    def p_test(count):
    	i = 0
    	while True:
    		print(i)
    		i = i + 1
    		with count.get_lock():
    			count.value = i
    
    if __name__ == '__main__':
    	TestApp().run()
```

[![enter image description here][2]][2]
[![enter image description here][3]][3]

How can I solve this problem?
I am using Windows11 and WinPython.

  [1]: https://stackoverflow.com/questions/77471934/how-to-get-multiprocessing-working-in-python-with-kivy/77488857?noredirect=1#comment136626921_77488857
  [2]: https://i.stack.imgur.com/FfK41.png
  [3]: https://i.stack.imgur.com/ZuR0B.png

**Comment by ElliotGarbus** [comment] 2023-12-07 21:17
This is a problem with the way multiprocessing works in python, and the way kivy works.  Here is a multiprocessing example using kivy: https://github.com/ElliotGarbus/MidiClockGenerator
Take a look at main.py, notice that most of the code is under a gate: "if __name__ == '__main__':"
This ensures that only the main processes creates a Window.  The import of kivy.app creates a window, so that needs to be under a gate. 
This is discussed briefly in the python docs. https://docs.python.org/3/library/multiprocessing.html#multiprocessing-programming
Read the section titled: "Safe importing of main module"

**Comment by Julian-O** [comment] 2023-12-08 00:44
Duplicate of #8340 and #4744

**Closed by Julian-O** 2023-12-08 00:44 UTC
