### ISSUE TITLE
Select all, Copy and Paste is not reachable on Android if TextInput is first / upper element

### ISSUE THREAD

**Issue by oxidworks** [kivy/kivy#4672] opened 2016-10-15 12:01 UTC
I have this problem with Android 5.0.2

Program code:

```
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.textinput import TextInput
from kivy.uix.label import Label
from kivy.uix.boxlayout import BoxLayout

class DEESCA(App):

    def on_pause(self):
        return True

    def on_translate_button_clicked(self, instance):
        pass

    def build(self):
        self.icon = "data/icon.png"        
        self.inputtext = TextInput(hint_text="insert here")
        self.inputtext.bind(on_text_validate=self.on_translate_button_clicked)
        self.l1 = TextInput(text="DE", readonly=True)
        self.l2 = TextInput(text="ES", readonly=True)
        self.l3 = TextInput(text="CA", readonly=True)
        b = Button(text='Translate')
        b.bind(on_press=self.on_translate_button_clicked)
        layout = BoxLayout(orientation='vertical', padding=10)
        layout.add_widget(self.inputtext)
        layout.add_widget(b)
        layout.add_widget(self.l1)
        layout.add_widget(self.l2)
        layout.add_widget(self.l3)
        return layout 

if __name__ == '__main__':
    DEESCA().run()
```

**Comment by KeyWeeUsr** [comment] 2016-11-12 17:36
Not sure if an issue or not. If I create `TextInput`s with `use_bubble=True` (as it'd work on mobile), the bubble is clearly visible when clicked in the right area i.e.:

* directly under the top = invisible (bubble is too far above widget)
* a little bit lower = visible

Should the `Bubble` in `TextInput` switch its orientation too e.g. when triggered by a touch in upper part of a widget? The default state is body up, arrow down - should the arrow be on the top and body at the bottom + pushed down to the `TextInput`'s area?

If not, then the issue is really only about [`inch(.25)`](https://github.com/kivy/kivy/blob/master/kivy/uix/textinput.py#L1593) being too big and should be changed to let's say `.15`.

**Comment by saqib1707** [comment] 2016-11-29 16:56
@KeyWeeUsr one idea would be to place the bubble right or left of the touch when the touch is made directly under the top(when it becomes invisible).If this has to be done then I want to work on this issue.

**Comment by KeyWeeUsr** [comment] 2016-11-29 17:02
Well, this is the current behavior. The right thing would most likely be to check for the collisions with outer bonds of TextInput and threw the Bubble the other way. I saw some code related to it, maybe it's just still not done or something.

**Comment by saqib1707** [comment] 2016-11-30 08:48
@KeyWeeUsr On long touch anywhere on the textinput box it only shows (select_all ,paste) bubble instead of (cut,copy,paste) . whereas in long_touch() function in textinput.py it invokes _show_cut_copy_paste(). I have used use_bubble=True. Why is this happening ? Also the (select_all , paste) bubble is non-functioning i.e it doesn't selects or pastes anything.

**Comment by KeyWeeUsr** [comment] 2016-11-30 10:54
Yep, seems like it's broken in master. Open another issue if there's not a duplicate if you arenlt going to fix it, because it worked before. Also, the buttons (Select all) don't work too. I wonder why.

Re the right click: Nope, Kivy doesn't use the right click by default. The right click just creates another "touch", e.g. for simulation of multitouch on desktops. If you're trying to do long tap, hust hold the left mouse button, because it's basically the same.

**Comment by saqib1707** [comment] 2016-11-30 16:38
@KeyWeeUsr I am working on this issue.I found out that the "pos" on this line https://github.com/kivy/kivy/blob/master/kivy/uix/textinput.py#L1565 should be the absolute position with respect to the window that is in line 1267 , the argument relative should be 'False'. Otherwise the bubble wouldn't come down the touch point when user clicks near the top. 
Also can u please explain what is  the role of function fbind(*) in line 1574 since I am stuck here.

**Comment by saqib1707** [comment] 2016-12-01 15:10
@KeyWeeUsr I was trying to figure out the reason but unable to find till now.Do u have any idea why in android the select_all and paste options are  not responding ?

**Comment by KeyWeeUsr** [comment] 2016-12-01 15:46
I'm not sure, but the bubblebutton calls `do(self  action)` method. Or should at least. Try to check that and methods that are called from the `do()`.

**Comment by saqib1707** [comment] 2016-12-01 23:53
@KeyWeeUsr  I think there is nothing defined for the finger options here https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L418 and also there is no information dispatching when finger or touch on textinput is done.

**Comment by KeyWeeUsr** [comment] 2016-12-02 00:05
The button reacts to pressing, just the function isn't called(me, sdl2 bootstrap, p4a&kivy master). The sdl2 thingy is something different 😋 if there was no touch when you'd tap in the `TextInput`, it wouldn't even focus. The touch surely works as expected.

**Comment by akshayaurora** [comment] 2016-12-02 11:35
could you please test with setting always_release to false in button behavior? does that seem to fix the issue for you?

**Comment by saqib1707** [comment] 2016-12-02 13:54
@KeyWeeUsr  which function are u talking about here?

**Comment by KeyWeeUsr** [comment] 2016-12-02 14:42
@saqib1707 https://github.com/kivy/kivy/blob/master/kivy/uix/textinput.py#L361 is the function that is dispatched `on_release` of the `BubbleButton`, it should call e.g. [select_all](https://github.com/kivy/kivy/blob/master/kivy/uix/textinput.py#L371) but somehow doesn't. Either `do()` isn't dispatched, or `select_all` called.

I see the `BubbleButton` changing itself (image), casual `Button` dispatches `on_release` correctly, therefore I think the problem is somewhere there.

**Comment by saqib1707** [comment] 2016-12-02 16:37
@akshayaurora perfectly works on both android as well as laptop on setting **always_release=True.**

**Comment by akshayaurora** [comment] 2016-12-02 18:08
@dessant fallout from setting always_release = False by default

**Comment by saqib1707** [comment] 2016-12-02 18:16
@KeyWeeUsr the bubble previously was not coming to the opposite side (with arrow up) when touch is made near the top ,so I have made certain changes in line 1597,1606 and 1615 and It is working as expected. Also there is a confusion that the touch **pos** arguments that is provided to _show_cut_copy_paste is relative or absolute position.because in one call it was absolute position in line https://github.com/kivy/kivy/blob/master/kivy/uix/textinput.py#L1404 so I changed that to relative.

**Comment by KeyWeeUsr** [comment] 2016-12-03 00:18
@saqib1707 I think `touch` always returns a correct pos in the Window (absolute), not in the widget (relative?). Please make a PR if you can, contributions are always nice. 🍡 

@akshayaurora I don't think `always_release` is the issue here, although it fixes it. Why doesn't it fire? I presume touch is at the same position, right? Therefore it should work even with `always_release=False`, because the touch is still in the `BubbleButton`'s area. Or did I miss something?

**Comment by saqib1707** [comment] 2016-12-03 06:50
#4761

**Comment by saqib1707** [comment] 2016-12-05 18:00
@KeyWeeUsr I just realised now that if a textinput is at the bottom (in android or ios) , then once the keyboard comes up it completely or partially hides the textinput. So to avoid that , will it be better to change the **softinput_mode = below_target** in the  kivy/core/__init__.py file ?

**Comment by KeyWeeUsr** [comment] 2016-12-05 18:35
@saqib1707 I know about the issue, but I'm not sure what to do. I think an optimal thing would be either to resize everything properly or to just move everything (root widget) at `pos = [previous X pos, keyboard height]` if there is a way how to get the height of android/ios keyboard. I've seen both behaviors on android before, not sure how it works on ios.

**Comment by dessant** [comment] 2016-12-19 08:32
> Update: For this specific issue we could set always_release = True for the buttons in text input bubbles.

@akshayaurora sorry, missed your message. I think Bubble shouldn't be fundamentally incompatible with `always_release = False`, users are expecting a way for canceling their actions, and that should also hold true for this widget.

**Comment by dessant** [comment] 2016-12-20 13:18
There are two issues discussed in this thread, the bug surfaced by `always_release = False` (bubble buttons doing nothig) is being tracked here https://github.com/kivy/kivy/issues/3961.

**Comment by dessant** [comment] 2016-12-21 17:47
Fixed by https://github.com/kivy/kivy/pull/4836.

**Closed by dessant** 2016-12-21 17:47 UTC
Labels: widgets
