### ISSUE TITLE
kivy Android Camera only select index 0

### ISSUE THREAD

**Issue by pasteurjr** [kivy/kivy#6860] opened 2020-05-04 17:16 UTC
Python: 3.7
OS: android API 27 (Buildozer default)
Kivy:1.11.1
Kivy installation method: pip

**Describe the bug**
In Kv file, the logcat reports an error in parameter " index:"  of Camera Class when index is not "0". That is, it only works for index = 0.

**Comment by Julian-O** [comment] 2023-11-03 00:41
Duplicate of #7732 (even though this one was earlier)

**Closed by Julian-O** 2023-11-03 00:41 UTC
