### ISSUE TITLE
Crashes while playing videos (using ffpyplayer)

### ISSUE THREAD

**Issue by radiolondra** [kivy/kivy#7482] opened 2021-04-16 10:48 UTC
**Software Versions**
* Python: 3.7
* OS: Windows 10
* Kivy: latest
* Kivy installation method: pip

Using ffpyplayer and kivy.core.video Video module to play videos, on some videos from time to time I have the following error:

[ERROR  ] [ffpyplayer  ] [tls @ 145f4b80] Error in the pull function.
[WARNING] [ffpyplayer  ] [mov,mp4,m4a,3gp,3g2,mj2 @ 03692880] Packet corrupt (stream = 0, dts = 3676672)
[WARNING] [ffpyplayer  ] [mov,mp4,m4a,3gp,3g2,mj2 @ 03692880] .
[ERROR  ] [ffpyplayer  ] [mov,mp4,m4a,3gp,3g2,mj2 @ 03692880] stream 0, offset 0x10cc480: partial file
[ERROR  ] [ffpyplayer  ] [tls @ 145f4b80] The specified session has been invalidated for some reason.
[ERROR  ] [ffpyplayer  ] [h264 @ 146d73c0] Invalid NAL unit size (1526 > 246).
[ERROR  ] [ffpyplayer  ] [h264 @ 146d73c0] Error splitting the input into NAL units.

This happens mostly when the video is near the end of its duration or when I pause the video for a time greater than the video duration and I start playing again (immediately crashes with the error above), so I'm suspecting something continues to go on in ffpyplayer or in Video kivy module even if the video is paused. Some wrong sync with ffmpeg?
This happens pratically always streaming a video from an https link. Playing local videos everything seems to work fine (at least up now).
Any idea?

**Comment by matham** [comment] 2021-04-16 16:49
Duplicate of https://github.com/matham/ffpyplayer/issues/105.

**Closed by matham** 2021-04-16 16:49 UTC
