### ISSUE TITLE
python test_backend.py Does not display x-axis and y-axis labels

### ISSUE THREAD

**Issue by luisrodriguezgonzalez** [kivy/kivy#4834] opened 2016-12-20 13:59 UTC
Hello:

I have tried all the distributions of raspberry .
Does not display x-axis and y-axis labels

matplotlib/examples$ python2.7 -c 'import matplotlib; print matplotlib.__version__, matplotlib.__file__'
2.0.0rc1+2670.gbf5aeb5 /usr/local/lib/python2.7/dist-packages/matplotlib-2.0.0rc1_2670.gbf5aeb5-py2.7-linux-armv7l.egg/matplotlib/__init__.pyc

python test_backend.py

**Comment by dessant** [comment] 2016-12-20 14:30
Duplicate of https://github.com/kivy/kivy/issues/4831.

**Closed by dessant** 2016-12-20 14:30 UTC
