### ISSUE TITLE
Resizing in Debug (PyCharm) crashes with "NameError: name 'EventLoop' is not defined" in kivy\core\window\window_sdl2.py

### ISSUE THREAD

**Issue by xmav000** [kivy/kivy#7880] opened 2022-05-11 21:52 UTC
**Software Versions**
* Python: 3.10.4
* OS: Windows 11
* Kivy: 2.1.0
* Kivy installation method: Pycharm (pip?)
* PyCharm 2021.3.2 (Community Edition)

**Describe the bug**
Even the most basic Kivy App crashes when started as "debug" in PyCharm. When "run" in PyCharm, resizing works, but it's not possible to debug anything when you resize.  (most likely at least in Windows because its the windows_sdl2.py)

 Traceback (most recent call last):
   File "[...]\lib\site-packages\kivy\core\window\window_sdl2.py", line 270, in _event_filter
     EventLoop.idle()
 NameError: name 'EventLoop' is not defined"

**Expected behavior**
No crash, debugging should just work after resize.

**To Reproduce**
Create any Kivy App in PyCharm, start the program as debug (with or without break point) and resize the window. -> crash

**Code and Logs and screenshots**

```python
from kivy.app import App


class KivoApp(App):

    def build(self):
        pass


if __name__ == '__main__':
    KivoApp().run()

```

**Additional context**

**Comment by DaytonaJohn** [comment] 2022-05-24 23:32
I see the same behavior under Ubuntu 22.04 with PyCharm 2022.1 (Community Edition)

**Comment by Alyxion** [comment] 2022-07-09 11:53
Kivy 2.1.0 also crashes for me on Ubuntu 22.04 und OS X 12 Montery when either trying to close or resize a window because "EventLoop is None" in more or less every call of _event_filter. I am also using PyCharm.

When running it in Release Mode the Window is resizable but closing the application never finishes.

**Comment by jleaders** [comment] 2022-09-14 16:28
Same on Ubuntu 22.04 PyCharm 2022.2.1 (Professional Edition)

**Comment by FilipeMarch** [comment] 2022-09-30 08:15
I am having the same problem on macOS Monterey 12.6 (chip M1)
Python 3.10.6
Kivy 2.1.0

**Comment by doopath** [comment] 2022-10-07 21:17
Have the same problem on Manjaro with PyCharm 2022.2.2 (Community Edition).
Python 3.10.7
Kivy 2.1.0

Error:
```
 Traceback (most recent call last):
   File "/home/doopath/Files/code/Kivy/kivy_venv/lib/python3.10/site-packages/kivy/core/window/window_sdl2.py", line 270, in _event_filter
     EventLoop.idle()
 NameError: name 'EventLoop' is not defined
python-BaseException
```

**Comment by dwoods** [comment] 2022-10-07 21:46
Same issue here.

PyCharm 2022.2.2 (Professional Edition).
Python 3.10.7
Kivy 2.1.0

```
 Traceback (most recent call last):
   File "[xxxxxxxx]\venv\lib\site-packages\kivy\core\window\window_sdl2.py", line 270, in _event_filter
     EventLoop.idle()
 NameError: name 'EventLoop' is not defined
```

**Comment by doopath** [comment] 2022-10-07 22:18
It seems i fix this (temporary and it's not relieable).
Debugger shows me 2 problems:
1. window_sdl2.py file, WindowSDL._event_filter method. I rewrite the last condition like this:
```python3
elif action == 'windowresized':
    self._size = largs
    self._win.resize_window(*self._size)
    # Force kivy to render the frame now, so that the canvas is drawn.
    try: EventLoop.idle()
    except NameError: pass
```
2.window_sdl2.py file, WindowSDL.mainloop method. I rewrite the condition placed at ~570 line like this:
```python3
if action == 'quit':
    if self.dispatch('on_request_close'):
        continue
    try: EventLoop.quit = True
    except NameError: exit()
    break
```
Dunno if these changes will brake the freck out the kivy module, but now it seems to work nicely.
Hope this issue will be resolved soon.

**Comment by MRuszczycki** [comment] 2022-11-03 01:50
I looked up a bit. Somehow when a window is resized, mainloop in window_sdl2.py looses its scope on EventLoop. 
@doopath solution did not work for me, the window kept open. 

Importing EventLoop again in the if condition will help, but this is not a nice fix: 
`if action == 'quit':
                from kivy.base import EventLoop
                if self.dispatch('on_request_close'):
                    continue
                EventLoop.quit = True
                break`

**Comment by AvihooI** [comment] 2022-11-08 13:29
I noticed that if you place a breakpoint just before the place this error occurs, EventLoop is defined and if you step over the code it behaves as expected.

I would imagine it's a PyCharm quirk and I've seen the debugger doing some weird things before.

**Comment by jleaders** [comment] 2022-12-06 20:44
^ I can confirm the fix mentioned above ^ and I suggest this simple fix:
~~from kivy.base import EventLoop~~

Can we get a PR?

**Comment by FilipeMarch** [comment] 2022-12-06 20:53
Yes, removing that line solves the problem for me too

**Comment by xmav000** [comment] 2023-03-22 23:25
removing that line fixed the problem for me too (OP)

**Closed** 2023-11-04 10:50 UTC
Labels: Component: graphics, Type: Bug
