### ISSUE TITLE
SoundLoader.load cannot load a unicode path

### ISSUE THREAD

**Issue by MichaelCurrie** [kivy/kivy#3604] opened 2015-08-28 22:47 UTC
In Python 3, SoundLoader does not seem to be able to handle file or folder names with non-ASCII characters: 
```
from kivy.core.audio import SoundLoader
#...
***  self.current_sound = SoundLoader.load(sound_path_list[0])
   File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\kivy\core\audio\__init__.py", line 69, in load
     return classobj(source=filename)
   File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\kivy\core\audio\audio_pygame.py", line 47, in __init__
     super(SoundPygame, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 271, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4933)
   File "kivy\properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy\properties.c:4680)
   File "kivy\properties.pyx", line 429, in kivy.properties.Property.set (kivy\properties.c:5203)
   File "kivy\properties.pyx", line 484, in kivy.properties.Property.dispatch (kivy\properties.c:5852)
   File "kivy\_event.pyx", line 1168, in kivy._event.EventObservers.dispatch (kivy\_event.c:12154)
   File "kivy\_event.pyx", line 1074, in kivy._event.EventObservers._dispatch (kivy\_event.c:11451)
   File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\kivy\core\audio\__init__.py", line 147, in on_source
     self.load()
   File "C:\Backup\WinPython-64bit-3.3.2.3\python-3.4.3.amd64\lib\site-packages\kivy\core\audio\audio_pygame.py", line 85, in load
     self._data = mixer.Sound(self.filename)
 pygame.error: Unable to open file 'C:/Users/mcurrie/Desktop/GitHub/Lanki\\media\\Thai\\\u0e2a\u0e35\u0e40\u0e2b\u0e25\u0e37\u0e2d\u0e07\\\u0e2a\u0e35\u0e40\u0e2b\u0e25\u0e37\u0e2d\u0e07.wav'
```

It looks like `pygame` is not properly treating the path as unicode.  It looks like it's doing something like using the `unicode_escape` string literal representation of the path, as in:

```
In [1]: thai_string = 'สีเหลือง'
   ...: thai_string.encode('unicode_escape')
Out[1]: b'\\u0e2a\\u0e35\\u0e40\\u0e2b\\u0e25\\u0e37\\u0e2d\\u0e07'
```

Note that `Image` works fine with non-ASCII characters.  If `image_path` contains non-ASCII characters, the following works fine:

```
from kivy.uix.image import Image
#...
image = Image(source=image_path)
```

**Comment by mondayrain** [comment] 2015-09-18 09:56
If no one else is working on this yet, I'd like to give this a go. I'm new to Kivy but this seems like a fun bug to attempt!

**Comment by mondayrain** [comment] 2015-09-22 08:50
Interestingly, I wasn't able to reproduce this. The following worked just fine:

```
(kivyenv)lariswagger@lariswagger-Lemur:~/Code/kivyenv$ python
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from kivy.core.audio import SoundLoader
[INFO   ] [Logger      ] Record log in /home/lariswagger/.kivy/logs/kivy_15-09-22_20.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
[DEBUG  ] [Audio       ] register SoundPygame
[INFO   ] [Audio       ] Providers: audio_pygame (audio_ffpyplayer ignored)
>>> 
>>> 
>>> sound = SoundLoader.load("Jay_Chou_周杰倫_Simple_Love_簡單愛.wav")
>>> sound.play()
```
I followed the installation instructions for a Python 3 dev Kivy for linux [here](http://kivy.org/docs/installation/installation-linux.html#installation-in-a-virtual-environment). Perhaps this was inadvertently fixed, or I am missing something?

**Comment by mondayrain** [comment] 2015-09-22 08:52
@MichaelCurrie 
Interestingly, I wasn't able to reproduce this. The following worked just fine:

```
(kivyenv)lariswagger@lariswagger-Lemur:~/Code/kivyenv$ python
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from kivy.core.audio import SoundLoader
[INFO   ] [Logger      ] Record log in /home/lariswagger/.kivy/logs/kivy_15-09-22_20.txt
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2]
[DEBUG  ] [Audio       ] register SoundPygame
[INFO   ] [Audio       ] Providers: audio_pygame (audio_ffpyplayer ignored)
>>> 
>>> 
>>> sound = SoundLoader.load("Jay_Chou_周杰倫_Simple_Love_簡單愛.wav")
>>> sound.play()
```
I followed the installation instructions for a Python 3 dev Kivy for linux [here](http://kivy.org/docs/installation/installation-linux.html#installation-in-a-virtual-environment). Perhaps this was inadvertently fixed, or I am missing something?

**Comment by brousch** [comment] 2015-09-22 10:50
The original bug was filed on Windows, so it should be tested against
Windows to see if it's fixed.

**Comment by dessant** [comment] 2015-10-04 05:24
@MichaelCurrie, you could also try out sdl2, pygame is being deprecated.

**Comment by Rajivts** [comment] 2016-02-28 21:49
Same here, wasn't able to reproduce the bug, and this is on Windows. I reckon its already fixed by now, and can be closed.

The Code:
`from kivy.core.audio import SoundLoader
try:
	sound = SoundLoader.load("Jay_Chou_周杰倫_Simple_Love_簡單愛_สีเหลือง.wav");
	sound.play()
	print("All Good in here")
except Exception as Err:
	print("\n\n\n\n" + Err)	`

Execution:
`(Python3Env) C:\Users\Rajiv\Desktop>python TmpScriptForKivy.py
[INFO              ] [Logger      ] Record log in C:\Users\Rajiv\.kivy\logs\kivy_16-02-29_10.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:38:48) [MSC v.1900 32 bit (Intel)]
[INFO              ] [Audio       ] Providers: audio_sdl2 (audio_ffpyplayer ignored)
All Good in here`

**Comment by theaverageguy** [comment] 2016-03-22 14:22
Can't reproduce. Help @MichaelCurrie . Is it ok to be closed?

**Comment by dessant** [comment] 2016-03-22 14:26
The pygame providers were deprecated. Yes, this issue can be closed. Please open a new issue if you can still reproduce the bug with other providers.

**Closed by dessant** 2016-03-22 14:26 UTC
Labels: easy, pygame

**Comment by MichaelCurrie** [comment] 2016-03-23 17:51
Given that the `pygame` providers are deprecated, I agree this issue is moot.  Thanks for closing!

**Comment by MichaelCurrie** [comment] 2016-06-03 19:01
For historical purposes I created a Gist to allow you to reproduce the error on Kivy 1.9.0.

https://gist.github.com/MichaelCurrie/dba9148729ac9e6eae1c4cf79b0b4107
