### ISSUE TITLE
Doubling or halving of size when moving to or from retina display

### ISSUE THREAD

**Issue by GP89** [kivy/kivy#3311] opened 2015-04-29 09:40 UTC
It seems like the dpi of the current monitor is obtained at startup and saved, and isn't obtained again.

I noticed if you move an app from a retina display onto an external monitor, the sizes of everything is doubled still and everything looks twice as big as it should. As well if the program is launched on a standard resolution monitor and is moved to a retina display, everything is drawn again at half the size.

I'm running on mac os 10.10.3 if that helps
##

**Comment by GP89** [comment] 2015-04-29 10:04
I should mention, you need to resize the window to trigger it to redraw to see the issue. Although all the hit boxes double / half even before the redraw.

**Comment by ErenPhayte** [comment] 2017-05-05 14:56
Having same issue. Any resolve for this?

**Comment by janssen** [comment] 2017-08-23 17:13
Same here.  I modified the code in kivy/core/_window_sdl2.py to address this.  Change

```python
        self.win_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN | SDL_WINDOW_ALLOW_HIGHDPI

        IF USE_IOS:
            self.win_flags |= SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_FULLSCREEN_DESKTOP
```

to

```python
        self.win_flags = SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN

        IF USE_IOS:
            self.win_flags |= SDL_WINDOW_BORDERLESS | SDL_WINDOW_RESIZABLE | SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_ALLOW_HIGHDPI
```

I believe that the design is that if you carefully use scale-independent pixels everywhere (kivy.metrics.sp) appropriately when drawing, everything should just work.  But we haven't found that to be quite right (images have their own pixel fixation), particularly with fonts.  Wish I could work up a better bug report on this.

**Comment by matham** [comment] 2020-05-13 21:26
Duplicate of https://github.com/kivy/kivy/issues/6144.

**Closed by matham** 2020-05-13 21:26 UTC
