### ISSUE TITLE
Images strangely distorted when scaled down.

### ISSUE THREAD

**Issue by Julian-O** [kivy/kivy#7944] opened 2022-08-07 22:47 UTC
**Software Versions**
* Python: 3.11
* OS: Windows 11
* Kivy: 2.1.0
* Kivy installation method: pip install kivy

**Describe the bug**
I have buttons with `background_normal` images pointing to .png files.
I specify the height and width to be a moderately small fraction of the size of the original images (e.g. 100-150 px wide where the original is 1400-2000 px wide).

The images are shrunk to size, but have these weird stretched-out protuberances along the middle axes - the more they are shrunk, the more the issue.

e.g. Original image (a Chrome logo) as 2000x2000 png.
![logo_Chrome](https://user-images.githubusercontent.com/945973/183313701-60f6c61b-ef8d-4b73-b40a-12301e57d568.png)

It's appearance in Kivy (as one of 5 buttons) when shrunk to 100x100.

![image](https://user-images.githubusercontent.com/945973/183313728-8838eb9b-c8d3-4046-9cb5-9eb62c40e7b2.png)

**Expected behavior**
Image to be resized with loss of detail but without distortions.

**To Reproduce**

The .kv code is pretty straight forward for this example:

```
GridLayout:
    cols: 2
    width: 250
    padding: 30
    spacing: 30
    [... other buttons ...]
    Button:
        background_normal: 'resources/logo_Chrome.png'
        size_hint: None, None
        width: 100
        height: 100
        on_press:
            guiactions.trigger_app(app, "Chrome")
    [... other buttons ...]
```

**Comment by mp-007** [comment] 2022-08-10 22:59
I had the same problem in the past. I think it's because the image is compressed.

I was using this script to reduce the size of my image (reduce by 20 example)
```
from PIL import Image

im = Image.open("your_image.png")
nx,ny=im.size
im2 = im.resize((int(nx/20), int(ny/20)), Image.BICUBIC)
im2.save("your_image_new.png")
```

The biggest problem with big resolution png/jpg is the memory, If you have 2000x2000 pixel, you will have 400x more RAM than a 100x100 image.
If you want more information, you can check this conversion on discord: https://discord.com/channels/423249981340778496/670954354932449290/870459689790505061

**Comment by HyTurtle** [comment] 2022-08-10 23:33
What you are seeing here is the `BorderImage` due to using the default `border` args.

It can set that to 0's if there is none warranted, or make mix `Image` with `ButtonBehavior`.

**Comment by tshirtman** [comment] 2022-08-11 18:25
closing as it's not a bug, but resulting of the usage of Button to display an image.

**Closed by tshirtman** 2022-08-11 18:25 UTC
Labels: support
