### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by DO7LZ** [kivy/kivy#5463] opened 2017-10-30 15:28 UTC
### Versions

* Python: 3.5.3
* OS: Raspbian Stretch Lite 4.9.59-v7+
* Kivy: v1.10.1.dev0, git-3c88636, 20171030
* Kivy installation method: pip3 install --upgrade --force-reinstall git+https://github.com/kivy/kivy.git@master

### Description

Trying to change keyboard layout from US-English to German:

- Changed **/etc/default/keyboard** to:
```
XKBMODEL="pc105"
XKBLAYOUT="de"
XKBVARIANT=""
XKBOPTIONS=""
BACKSPACE="guess"
```
- Changed **/home/pi/.kivy/config.ini** to:
```
[kivy]
keyboard_layout = qwertz
```

**What happened:** I start the kivy application from bash. In the bash I have the correct keyboard layout (e.g. German umlauts) but when I start my application and try to enter something in a text input field the whole thing switched to some strange behavior.

**What went wrong:** When I enter "z" on the keyboard, it prints out "y".When i enter "<" it prints out "pipe".

**What I expected:** The same behavior of the text input field as when I'm in the bash.

Furthermore I did not find examples or possible values anywhere for keyboard_layout. [Here](https://kivy.org/docs/api-kivy.config.html?highlight=config#module-kivy.config) are no further infos or links for possible layout options.

Please help me. I did not find any more possible solutions.

**Comment by KeyWeeUsr** [comment] 2017-10-30 20:45
Does it happen in your application even on non-RPi devices?

**Comment by DO7LZ** [comment] 2017-10-31 06:18
On OS X 10.12.6 with Kivy 1.10.0 and Python 3.5.2 the problem did not appear.
When I execute examples/demo/showcase/main.py with Python 3 on the Raspberry Pi the problem also occurs. So it may be no problem with my Kivy application.

**Comment by olivier-boesch** [comment] 2020-04-24 12:30
The same problem appears with buster.

**Comment by olivier-boesch** [comment] 2020-04-25 20:09
Okay ! I begin to figure out what's happening.
In a conventional linux system, kivy works with sdl2 as window provider. In this case, sdl2 is the input provider. We can see this : **[INFO   ] [Window      ] auto add sdl2 input provider**

When I start a kivy app on the pi, I can force the use of sdl2 as window provider. I also see this : **[INFO   ] [Window      ] auto add sdl2 input provider**
In this case, the key mapping is corect (azerty for me)

But if I use egl_rpi as window provider, the keyboard inputs are kept by hidinput and it seems that no keymapping is performed. 

The problem is that sdl2 is very painful on the pi for the graphics. egl_rpi is far better.

Two solutions (are they possible ?):
- use egl_rpi for the graphics and sdl2 for the input.
or
- add a key mapping filter on hidinput based on the config.ini (keyboard_layout parameter)

What is possible ?

note : using raspbian buster and kivy master (2.0.0rc1)

**Comment by Julian-O** [comment] 2023-11-07 07:43
Obsoleted by #8434 
Closing.

**Closed by Julian-O** 2023-11-07 07:43 UTC
