### ISSUE TITLE
Line glitch when using stencil mask with alpha less than 1.0

### ISSUE THREAD

**Issue by IagoBeuller** [kivy/kivy#6094] opened 2019-01-07 15:41 UTC
### Versions

* Python: 3.7
* OS: Windows
* Kivy: 1.10.1
* Kivy installation method: pip install kivy pygame

### Description

Already reported but no attention: https://github.com/kivy/kivy/issues/3277
When I Draw a Line with alpha less than 1.0, I get fragments of the line outside the stencil mask. You can see in this example:

### Code:

```python
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.graphics import Color, Rectangle, Line, StencilPush, StencilUse, StencilPop

rounded_rectangle = [(80, 10), (75.13653947143874, 10.39294883015986), (70.52193891782913, 11.530484729457283), (66.21816422594438, 13.35064181111902), (62.28718128255777, 15.791454188371842), (58.790955974442504, 18.7909559744425), (55.791454188371844, 22.28718128255776), (53.35064181111902, 26.218164225944378), (51.530484729457285, 30.521938917829118), (50.39294883015986, 35.13653947143874), (50.0, 39.99999999999999), (50, 180), (50.39294883015986, 184.86346052856132), (51.53048472945729, 189.47806108217094), (53.350641811119026, 193.78183577405562), (55.791454188371844, 197.71281871744225), (58.790955974442504, 201.2090440255575), (62.28718128255777, 204.20854581162817), (66.21816422594438, 206.64935818888097), (70.52193891782912, 208.46951527054273), (75.13653947143874, 209.60705116984013), (79.99999999999999, 210.0), (220, 210), (224.8634605285613, 209.6070511698402), (229.47806108217094, 208.4695152705428), (233.7818357740556, 206.649358188881), (237.71281871744225, 204.2085458116282), (241.2090440255575, 201.2090440255575), (244.2085458116282, 197.71281871744225), (246.64935818888097, 193.78183577405562), (248.46951527054273, 189.47806108217088), (249.60705116984013, 184.8634605285613), (250.0, 180.0), (250, 40), (249.60705116984016, 35.136539471438745), (248.4695152705428, 30.521938917829125), (246.649358188881, 26.218164225944378), (244.20854581162817, 22.28718128255776), (241.2090440255575, 18.7909559744425), (237.71281871744225, 15.791454188371842), (233.78183577405562, 13.350641811119022), (229.47806108217088, 11.530484729457282), (224.86346052856123, 10.39294883015986), (220.0, 10.0), (80, 10)]

class IssueApp(App):
	def build(self):
		widget = Widget()
		with widget.canvas:
			StencilPush()
			Rectangle(pos=(0,0), size=(100,200))
			StencilUse().func_op = 'equal'
			Color(1,0,0,0.5)
			Line(points=rounded_rectangle, width=6.001/2, cap='none', joint='miter')
			StencilPop()
		return widget

if __name__ == '__main__':
    IssueApp().run()

```

**Comment by tshirtman** [comment] 2019-01-15 21:59
Yes, considering how the line is built, it's simpler to set alpha of the widget itself to 0.5 in this situation.

**Comment by IagoBeuller** [comment] 2019-01-20 21:31
Unfortunately the situation I am can't be solved using this way.

**Comment by tito** [comment] 2019-02-12 15:03
Duplicate of #3277 

(Sorry, i understand there was no answer before, but we don't need to also have duplicate on the > 600 issues, thanks for your cooperation!)

**Closed by tito** 2019-02-12 15:03 UTC
