### ISSUE TITLE
gallery image links on kivy.org are broken

### ISSUE THREAD

**Issue by ghostsquad** [kivy/kivy#3916] opened 2016-01-15 03:29 UTC
the images links in the gallery @ https://kivy.org/#gallery are broken. clicking on any of the images opens up a lightbox with "undefined" in the lower left corner.

**Comment by dessant** [comment] 2016-01-15 03:54
Duplicate of https://github.com/kivy/kivy-website/issues/62.

**Closed by dessant** 2016-01-15 03:54 UTC
