### ISSUE TITLE
DropDown touch issue

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4068] opened 2016-03-08 15:49 UTC
Taken from https://github.com/kivy/kivy/pull/4014#issue-134670993.

When a selection is made, the dropdown, being a direct child of window, gets the touch_up first, which dismisses the dropdown. Then the dropdown button gets the touch_up, however, the on_release is not triggered because the dropdown is gone so it doesn't collide anymore.

**Edit**: This one does not appear to be reproducible anymore, below is a different dropdown issue though. :yum: 
https://github.com/kivy/kivy/issues/4068#issuecomment-193883143

**Comment by matham** [comment] 2016-03-08 16:52
Did you experience it? Because I couldn't reproduce it anymore.

**Comment by dessant** [comment] 2016-03-08 17:00
I did not.

**Comment by dessant** [comment] 2016-03-08 17:37
When you run `dropdown.py`, after the dropdown has been opened, the next click on the dropdown button will dismiss the dropdown, but `on_release` is not called. It also becomes a visual issue because the second touch does not change the state of the button.

I would expect the touch to not be eaten, and the dropdown button should act as a toggle for opening and closing.

**Comment by dessant** [comment] 2016-03-08 21:10
@matham, although this is a different issue, since you're talking about a button from the list not getting the dispatch, which i cannot reproduce, but i don't see a commit either which would have fixed it.

With which commit were you able to reproduce your bug? I've tried with master, your pr commit, and its parent commit.

**Comment by matham** [comment] 2016-03-08 21:28
I was able to reproduce it with master before my pr. But it was in a complex app with many layers of scrollviews and things. But I could not reproduce it after the PR was merged.

**Comment by akshayaurora** [comment] 2016-04-08 21:25
Closed by https://github.com/kivy/kivy/pull/4132

**Closed by akshayaurora** 2016-04-08 21:25 UTC
Labels: widgets
