### ISSUE TITLE
FloatLayout inside a BoxLayout doesn't respect the paddings

### ISSUE THREAD

**Issue by Samael-TLB** [kivy/kivy#8504] opened 2023-12-11 14:40 UTC
**Software Versions**
* Python: 3.8
* OS:
* Kivy: 2.2.0
* Kivy installation method: pip

**Describe the bug**
In a boxlayout, which has padding, the floatlayout being a child of the boxlayout, it doesn't respect the padding of the boxlayout. This is only corrected when relative layout is used.

**Expected behavior**
The float layout should also respect its parent boxlayout's paddings.

**Additional context**

![image](https://github.com/kivy/kivy/assets/33490731/c8487470-ad0d-4159-8c6a-915067d42af2)
The top most box shows the designated border with the paddings for the boxlayout's children.
The middle one shows the result when floatlayout is used due to which the contents bleed out and dont respect the paddings.
The last one is the correct behaviour obtained when using relative layout.

**Comment by ElliotGarbus** [comment] 2023-12-11 15:12
Do you have a minimal example?  This does not make sense to me.  The FloatLayout will honor the pos of it's children, making the padding of the parent layout irrelevant.

**Comment by Samael-TLB** [comment] 2023-12-11 17:32
What I mean is that I understand `FloatLayout` will honor the pos of it's children, in this case its (0,0). But this contradicts with the behaviour of the parent which is `BoxLayout`. Boxlayout guarantees that the children shall respect the paddings. 
Now there comes the issue, boxlayout makes the starting of the widget to be after the padding but the float layout should not ignore that when the children did not ask it to . That is by default, the float layout's (0,0), should start after the padding of its parent BoxLayout.

If the FloatLayout doesn't regard the padding for positioning its children, then it should also not regard the padding for its own sizing. If it takes its sizing from its parent then its positioning should also take that into consideration. Like that should be the case right, any layouts boundary denotes the (0,0) inside this layout ( please note I'm not referring it to be relative coordinates, but just conveying the idea of the starting position). Then it can obviously regard child position as requested.

**Comment by Samael-TLB** [comment] 2023-12-11 17:39
> output:
> fl.pos=[10, 253.33333333333334] fl.size=[980, 243.33333333333334] self.size=[980, 243.33333333333334] self.pos=[10, 496.6666666666667] fl_child.pos=[0, 0]

Yes, as seen the fly pos is at 10,253.333 and fl_child pos is 0,0.
This denotes the notion that the float layout is letting the child to be at the 0,0 of the root relative widget( here window).
This though it behaves normally like the float layout is stated to be, but doesn't it negates the padding constraint of the boxlayout. This behaviour disregards the expected one, but upon investigation we see that this is how float layout behaves.

i think there's a need for some clear descriptions in the docs or we should have the constraints being followed.

**Comment by ElliotGarbus** [comment] 2023-12-11 19:31
There is not a bug here.  I suggest closing this issue.  If you would like to continue this discussion on Discord, I'd be happy to continue.

**Closed** 2023-12-11 23:56 UTC

**Comment by Samael-TLB** [comment] 2023-12-12 08:23
Thanks @Julian-O for closing the issue.

**Comment by Samael-TLB** [comment] 2023-12-12 08:24
> There is not a bug here. I suggest closing this issue. If you would like to continue this discussion on Discord, I'd be happy to continue.

Surely.
