### ISSUE TITLE
Size hint is not honored if set to zero

### ISSUE THREAD

**Issue by 0x4A-0x41-0x4B** [kivy/kivy#7281] opened 2020-12-19 18:51 UTC
**Software Versions**
* Python: 3.7.9
* OS: Windows 10 Version 1909 (Build 18363.1256)
* Kivy: 2.0.0
* Kivy installation method: pip (pip install kivy)

**Describe the bug**
The size_hint seems to not be honored/used if it is set to 0. Only if it is the second widget inside its parent.

**Expected behavior**
The expected behavior of setting (for example) size_hint_x to 0 is that the width should equal zero at all times.

**To Reproduce**
Set any size_hint attribute to zero.

**Code and Logs and screenshots**
```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

Builder.load_string("""
<TestPage>:
    BoxLayout:
        id: test_box
        size_hint_x: 0
        canvas:
            Color:
                rgba: (1,0,0,1)
            Rectangle:
                pos: self.pos
                size: self.size
    BoxLayout:
        id: test_box_two
        size_hint_x: 1
        canvas:
            Color:
                rgba: (0,0,1,1)
            Rectangle:
                pos: self.pos
                size: self.size
""")


class TestPage(BoxLayout):
    pass


if __name__ == '__main__':
    from kivy.app import App

    class TestPageApp(App):
        def build(self):
            return TestPage()

    TestPageApp().run()
```
![image](https://user-images.githubusercontent.com/31889834/102697169-100dbb00-4234-11eb-940e-2dd63b911081.png)

**Additional context**
The code above should result in a blue filled screen, instead it shows a red rectangle with the default size/width (of 100) and a blue rectangle filling up all additional space.
This was reproducible on all of my machines (including a Raspberry PI 4 running the latest Debian and a virtual machine running Ubuntu)

**Comment by matham** [comment] 2020-12-19 19:37
A size of hint of zero means the worst of both worlds and should never really be used.

When setting size hint to None, we set aside enough space for the widget's `width` and use the size hint to layout out the remaining widgets. When size hint is zero, we don't set any space for that widget. So e.g. `test_box_two` gets the full width.

However, like setting it to None, when you set `test_box` size hint to zero, `test_box` width will not be set manually, so it's real size will be `100`, the default. Therefore the layout will place `test_box_two` at 100 pixels to the right.

You can see this by adding `on_size: print(self.size, self.pos)` to the various widgets.

Ideally when size_hint is zero, we do set the widget width to zero, but I guess that fell through the cracks since at least 1.9.0 (which I checked). However, I expect no one uses it this way, since the canonical way for what you're trying to do would be:

```
size_hint_x: None
width: 0
```

**Comment by 0x4A-0x41-0x4B** [comment] 2020-12-19 19:57
Hello @matham ,
thank you for the fast reply, your explanation would make sense but it breaks apart when you start changing the size_hint_x of the second widget (instead of the first) to zero. Then it works with no issues (eg. zero width). This should at least be consistent and documented.

Example:
`python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

Builder.load_string("""
<TestPage>:
    BoxLayout:
        id: test_box
        size_hint_x: 1
        canvas:
            Color:
                rgba: (1,0,0,1)
            Rectangle:
                pos: self.pos
                size: self.size
    BoxLayout:
        id: test_box_two
        size_hint_x: 0
        canvas:
            Color:
                rgba: (0,0,1,1)
            Rectangle:
                pos: self.pos
                size: self.size
""")


class TestPage(BoxLayout):
    pass


if __name__ == '__main__':
    from kivy.app import App

    class TestPageApp(App):
        def build(self):
            return TestPage()

    TestPageApp().run()

`

![image](https://user-images.githubusercontent.com/31889834/102698297-a2b25800-423c-11eb-93f3-a989b65f4214.png)

**Comment by matham** [comment] 2020-12-19 20:41
>Then it works with no issues (eg. zero width). This should at least be consistent and documented.

Not quite. If you look at the size and pos of the widgets you'll see my analysis is correct even in this case. What happens is that the first widget takes up the full width, followed by the second widget but with size 100. However, the second widget is displayed to the right of the window (i.e. you can't see it).

**Comment by 0x4A-0x41-0x4B** [comment] 2020-12-19 20:51
That means that a size_hint_x of 0 is exactly the same as size_hint_x: None, (even though bool(0) is False and not None) which should still be documented. (Or maybe it is and i was just unable to find it)

**Comment by matham** [comment] 2020-12-19 20:55
>That means that a size_hint_x of 0 is exactly the same as size_hint_x: None

But it isn't. Because when a widget's size  hint is None, the other widgets whose size hint is not None are given sizes to fill up the **remaining** spaces after dedicating space for all the widgets that are None. But when the size hint is zero, we don't not include this widget's size when computing how much space remains.

The proper fix IMO is to make a size hint of 0, set the widget's size to zero, like you expected.

**Comment by 0x4A-0x41-0x4B** [comment] 2020-12-19 21:04
That would indeed make sense because then the claim in the documentation:
"The size_hint is a tuple of values used by layouts to manage the sizes of their children. **It indicates the size relative to the layout’s size** instead of an absolute size (in pixels/points/cm/etc)." ([LINK](https://kivy.org/doc/stable/api-kivy.uix.layout.html)) would be correct as well as improving mathematical correctness (because 0% of any given width is 0 width and with that zero area)

**Comment by 0x4A-0x41-0x4B** [comment] 2020-12-19 22:54
@matham There still seems to be another issue with the size_hint 0 that we have not explored.
If the size_hint_x's value is chosen using an inline if statement even weirder behavior can be observed, when the else value (from the if statement) is used (because the statement is equal to False) then the size_hint_x (If set to 0 inside the else block) and the width seem to not be used.

Example:
```python
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout

Builder.load_string("""
<TestPage>:
    orientation: "horizontal"
    some_statement: root.width > root.height
    BoxLayout:
        id: test_box
        size_hint_x: 1 if root.some_statement else 0  # This is the important part!
        width: 0  # This gets ignored at all times, for some reason
        canvas:
            Color:
                rgba: (1,0,0,1)
            Rectangle:
                pos: self.pos
                size: self.size
    BoxLayout:
        id: test_box_two
        size_hint_x: 1
        canvas:
            Color:
                rgba: (0,0,1,1)
            Rectangle:
                pos: self.pos
                size: self.size
""")


class TestPage(BoxLayout):
    pass


if __name__ == '__main__':
    from kivy.app import App

    class TestPageApp(App):
        def build(self):
            return TestPage()

    TestPageApp().run()

```

![image](https://user-images.githubusercontent.com/31889834/102701238-25dfa800-4255-11eb-949a-c8bb36b0abd9.png)

The two print statements represent the width and position of the red boxlayout. The first one is before the if statement is False.

**Comment by matham** [comment] 2020-12-19 23:27
No, that is expected based on how kv rules work. When the widget is initially loaded and kv rules applied, width is set to zero because of `width: 0`. But then as because `some_statement` is True and the size hint is 1, the width will be then set to whatever the parent sets it to.

From then on, `width: 0` is never again executed, because it's not a dynamic rule. So when `some_statement` becomes False, the width simply remains whatever it was at that point. Exactly like in the initial examples. To prove it to you, simply make `width: 0` into a dynamic rule with `width: self.width if root.some_statement else 0` and you'll see that it does get reset to zero. as expected.

**Comment by Julian-O** [comment] 2023-11-02 03:01
Working as designed. Closing as Wont Fix.

**Closed by Julian-O** 2023-11-02 03:01 UTC
Labels: Component: Widgets, Priority: Medium

**Comment by jalalnouri72** [comment] 2026-02-11 11:29
Hi
Do not set the `size_hint_x` (or `size_hint_y`) value  to zero. Set it to a value close to zero (depending on what you are doing, it may be different. For example, I set it to 0.001 in my project).
