### ISSUE TITLE
Text elements do not appear

### ISSUE THREAD

**Issue by fgassen** [kivy/kivy#6331] opened 2019-05-24 15:46 UTC
### Versions

* Python: 3.7.3
* OS: Windows 10
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

Hello All,

Few days ago some users started reporting a strange issue in a simple RPA application developed by myself.

For some reason, sometimes the texts inside buttons and inputs are not showing up (see below):

![issues](https://user-images.githubusercontent.com/20006008/58339945-f5eadb80-7e4a-11e9-906c-285c4946ed5c.PNG)

I recall when I developed the tool, I was facing the same problem, however, after adding the following line, the issue was solved:

os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'

I tried to use:

Config.set('graphics', 'multisamples', '0')

But the problem remains.

Does anybody has an idea on how to fix it?

Thanks a lot!

**Comment by scjv** [comment] 2019-05-24 16:04
The text is there, but poorly visible due to an error in color or transparency.
![6331](https://user-images.githubusercontent.com/23345150/58341269-23855400-7e4e-11e9-8ed1-42e234fe7aac.png)

**Comment by matham** [comment] 2019-05-24 17:01
Duplicate of https://github.com/kivy/kivy/issues/6318.

**Closed by matham** 2019-05-24 17:01 UTC
