### ISSUE TITLE
race condition in Popup dismiss() animation

### ISSUE THREAD

**Issue by janssen** [kivy/kivy#4491] opened 2016-07-25 20:27 UTC
For the last year, I've been seeing an occasional problem with dismissal of Popups.  I'm seeing this in 1.9.1, for instance.  About 1 in 6 times, the popup window remains on-screen, and the modal background over the rest of the screen (the gray overlay) is lightened a bit, but not all the way to alpha=0.  Doing anything to some other element of the display which causes a graphics change (pressing a button, for instance) will fix this (the popup window disappears, and the overlay goes all the way to alpha=0, or is gone entirely).  However, I can eliminate this problem by using "animation=False" in my call to Popup.dismiss().

Given that, it sure looks like the animation in modalview is not being completely finished, for some reason.

Unfortunately, I have no simple test case.

**Comment by janssen** [comment] 2016-07-25 20:29
I might change the code in modalview.py from this:

```
    def on__anim_alpha(self, instance, value):
        if value == 0 and self._window is not None:
            self._real_remove_widget()
```

to this:

```
    def on__anim_alpha(self, instance, value):
        if value <= 0.0 and self._window is not None:
            self._real_remove_widget()
```

**Comment by matham** [comment] 2016-07-25 23:30
If this fixes it for you then it should be easily merged.

**Comment by janssen** [comment] 2016-07-26 10:04
I'm not convinced this is the problem.  It's Programming 101, sure, "don't compare a floating point value for equality to another value, only for inequality", but if this is the issue, why does the window disappear when I do something with some other element of the display?  Auto-dismiss is set to False.  Clicking outside the popup does not cause it to dismiss, but doing anything that requires a graphics update will.

It's more as if the last frame of the animation is never processed, or never scheduled, so the last `on__anim_alpha` event is never delivered, so the `_real_remove_widget method` is never called.  Somehow doing the graphics update triggers that last animation frame.

All of this is Python 2.7.12 on Ubuntu 16.04, by the way.

**Comment by janssen** [comment] 2016-07-26 10:06
Yeah, I just tried this in my code.  It doesn't fix the problem.

**Comment by janssen** [comment] 2016-07-26 10:38
I've tried tinkering a bit more.  I added an animation `on_complete` callback to ModalView, and it doesn't get triggered either.  Somehow the events aren't being dispatched.  Since `Animation` is a subclass of `EventDispatcher`, the problem is probably in the C code, and maybe in Clock.

**Comment by janssen** [comment] 2016-07-26 10:50
I added some print statements; the event *is* being dispatched.

```
 on__anim_alpha 0.87094206037
 on__anim_alpha 0.743021830218
 on__anim_alpha 0.614931610413
 on__anim_alpha 0.407577040256
 on__anim_alpha 0.210461360053
 on__anim_alpha 0.0
 on__anim_complete
```
So now I think this is purely a screen update problem.  `remove_widget` has been called on the Window for the Popup, but whatever is supposed to update the drawing of the screen isn't firing.  An OpenGL buffering issue?

**Comment by janssen** [comment] 2016-07-27 02:43
I suspect we haven't seen more of this bug because it's rare for a window to be removed from the root window, the SDL2 Window.  Note that Widget and Window have two different implementations of `remove_widget` (though they look -- to me -- substantially the same).

**Comment by janssen** [comment] 2016-07-28 01:38
Looking at the code for remove_widget(), it looks to me as if nothing done there will trigger a redraw of the graphics, even though they've been modified.  I think the code there should call self.canvas.ask_update().  I'll see if I can test that hypothesis.

**Comment by Helder-Tomas** [comment] 2016-08-09 10:47
Hey guys I've seen this happening a fair bit too.
It seems to be confined to the usage of clocks ans carousel (and other modal views)

This one should always work, the second button is a simplistic short/long press button.
`# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.clock import Clock
from kivy.uix.popup import Popup
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button

from kivy.clock import Clock

class measureButtonOnTouch(Button):
    #this one actually only works on release rather than on press. uses only a
    #time delta

    global go

    def __init__(self, **kwargs):
        super(measureButtonOnTouch, self).__init__(**kwargs)
        #self.bind(on_press=self.on_press1)

    def on_press(self, *args):
        print 'on press'
        #callback = partial(self.menu, touch)
        global go
        go = True
        Clock.schedule_once(self.menu, 0.5)

    def on_release(self, *args):
        global go
        if go:
            print 'this is a short touch'
        go = False

    def menu(self, *args):
        global go
        if go:
            go = False

            box = BoxLayout()
            popup = Popup(title='test', content=box, size_hint=(0.5, 0.5))
            but = Button(text='Press Dismiss, every once in a while it does not work.\nTry to swipe regardless...', size_hint=(1, None))
            but.bind(on_press=popup.dismiss)
            box.add_widget(but)
            popup.open()




class pressTest(BoxLayout):
    def __init__(self, **kwargs):
        super(pressTest, self).__init__(**kwargs)


        self.orientation='vertical'
        #button
        but = Button(text='get a popup')
        but.bind(on_press=self.get_a_popup)
        self.add_widget(but)
        #add to box
        self.add_widget(measureButtonOnTouch(text='menu on long press'))



    def get_a_popup(self,*args):
        box = BoxLayout()
        popup = Popup(title='test', content=box, size_hint=(0.5, 0.5))
        but = Button(text='Press Dismiss, every once in a while it does not work.\nTry to swipe regardless...', size_hint=(1, None))
        but.bind(on_press=popup.dismiss)
        box.add_widget(but)
        popup.open()

class Test(App):
    def build(self):
        return pressTest()

if __name__ == '__main__':
    Test().run()`

This one uses a carousel and fails in about 80% of cases for me:

`# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.clock import Clock
from kivy.uix.popup import Popup
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from functools import partial
from kivy.uix.label import Label
from kivy.uix.gridlayout import GridLayout
from kivy.uix.textinput import TextInput
from kivy.uix.carousel import Carousel


from kivy.clock import Clock

class measureButtonOnTouch(Button):
    #this one actually only works on release rather than on press. uses only a
    #time delta

    global go

    def __init__(self, **kwargs):
        super(measureButtonOnTouch, self).__init__(**kwargs)
        #self.bind(on_press=self.on_press1)

    def on_press(self, *args):
        print 'on press'
        #callback = partial(self.menu, touch)
        global go
        go = True
        Clock.schedule_once(self.menu, 0.5)

    def on_release(self, *args):
        global go
        if go:
            print 'this is a short touch'
        go = False

    def menu(self, *args):
        global go
        if go:
            go = False

            box = BoxLayout()
            popup = Popup(title='test', content=box, size_hint=(0.5, 0.5))
            but = Button(text='Press Dismiss, every once in a while it does not work.\nTry to swipe regardless...', size_hint=(1, None))
            but.bind(on_press=popup.dismiss)
            box.add_widget(but)
            popup.open()

class pressTest(BoxLayout):
    def __init__(self, **kwargs):
        super(pressTest, self).__init__(**kwargs)

        #carousel
        car = Carousel()

        box1 = BoxLayout(orientation='vertical')
        #button
        but = Button(text='get a popup')
        but.bind(on_press=self.get_a_popup)
        box1.add_widget(but)
        #add to box
        box1.add_widget(measureButtonOnTouch(text='measureButtonOnTouch'))

        car.add_widget(box1)

        self.add_widget(car)


    def get_a_popup(self,*args):
        box = BoxLayout()
        popup = Popup(title='test', content=box, size_hint=(0.5, 0.5))
        but = Button(text='Press Dismiss, every once in a while it does not work.\nTry to swipe regardless...', size_hint=(1, None))
        but.bind(on_press=popup.dismiss)
        box.add_widget(but)
        popup.open()


class Test(App):
    def build(self):
        return pressTest()

if __name__ == '__main__':
    Test().run()`

Hopefully these examples will help to solve this nuisance.
Thanks for making kivy awesome guys!

**Comment by tshirtman** [comment] 2016-09-04 16:58
Can't seem to reproduce with either of these examples, which platform and version of kivy are you on?

**Comment by dessant** [comment] 2016-12-27 01:26
@janssen, is it still reproducible with kivy master?

**Comment by janssen** [comment] 2016-12-28 18:26
I'll check.

**Comment by janssen** [comment] 2016-12-28 19:02
I cannot get Helder-Tomas' examples to fail, using kivy master with Python2 and Ubuntu 16.04 on a Lenovo laptop.  So maybe some of the other changes to the Clock have fixed this.  I'll check it on my Mac and Windows machines when I get access to them.

**Closed** 2017-01-20 11:31 UTC
Labels: awaiting-reply, needs-analysis

**Comment by krkeegan** [comment] 2017-08-01 02:09
I am seeing this exact issue.  I am on 16.04.2 and Kivy==1.10.0.  I have a not super fast machine. 
Disabling animations in the dismiss does prevent the problem.

I ended up changing my maxfps in my kivy config.ini file to 10 from 60 and this also solves it.  Not sure if this works because the animation duration at .1 second is now equal to the screen fps which may disable the animation.

**Comment by schoolsplay** [comment] 2018-02-01 08:06
We have the same issue on kivy 1.10 when running on intel grafics *and* gnome-shell. We don't have this issue when running on the same hardware in xfce4.
We deploy 500+ machines with our kivy based software and we wanted to move from a xfce4 based desktop to gnome-shell and only with gnome-shell we have these problems :-(

**Comment by schoolsplay** [comment] 2018-02-01 09:00
Here is some test code including the kivy stack taken from Debian stable.
I would say in about 50% of the time it will not dismiss the popup or won't react to hitting the close button.
After running the test code a couple of times it looks like the following.
When you start the test code and it works the first time it works all the time but when it doesn't work the first time it has issue all the time.

This is tested on Debian stable with a minimal gnome-shell running on xorg (not wayland)
[test-kivy.tar.gz](https://github.com/kivy/kivy/files/1684782/test-kivy.tar.gz)
