### ISSUE TITLE
Feature Request: Section on debugging Kivy apps, esp. kvlang portions, in the Prog. Guide

### ISSUE THREAD

**Issue by OlyDLG** [kivy/kivy#3017] opened 2015-02-10 21:55 UTC
Hi!  I'd like to suggest/request that a section on methods for debugging Kivy apps, especially those portions that rely on kvlang files, be added to the "Programming Guide."  Example topics: strategic places to put breakpoints; which Python attributes of Kivy objects to "worry" about (i.e., examine the values of); etc.  (Suggestions from people with experience (trying to) debug Kivy apps encouraged.)  Thanks!

**Comment by victor-rene** [comment] 2015-03-03 17:56
I second this. I write all my code by hand, because kvlang scares me to the bones after a few bad experiences. It's easier to debug code that you write than to try to understand what magic goes behind the scenes of kv builder.

Can someone add the label important? Because all the questions we have on kivy IRC, are most of the time, kv lang questions. How to do this or that in kv lang... like everyday almost.

**Comment by Zen-CODE** [comment] 2015-12-28 16:42
This seems to be a duplicate of https://github.com/kivy/kivy/issues/3018

@victor-rene. Please add your suggestions to ticket 3018, but in more concrete form. What exactly do you want if these sections? What is lacking? "How to do this or that" is very vague. What is "this or that'?

**Closed by Zen-CODE** 2015-12-28 16:42 UTC
Labels: documentation
