### ISSUE TITLE
Fix HIDMotionEvent log formatting

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3075] opened 2015-02-24 04:31 UTC
This was posted by C_D on irc, seems to be a py3 issue, but not tested.

``` python
[INFO              ] Logger: Record log in /home/fpg/.kivy/logs/kivy_14-12-10_0.txt
[INFO              ] Kivy: v1.9.0-dev
[INFO              ] Python: v3.4.2 (default, Jan 11 2015, 22:16:42) 
[GCC 4.9.2 20141224 (prerelease)]
[INFO              ] Factory: 173 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] Text: Provider: sdl2
[INFO              ] Window: Provider: egl_rpi
[INFO              ] GL: OpenGL version <b'OpenGL ES 2.0'>
[INFO              ] GL: OpenGL vendor <b'Broadcom'>
[INFO              ] GL: OpenGL renderer <b'VideoCore IV HW'>
[INFO              ] GL: OpenGL parsed version: 2, 0
[INFO              ] GL: Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO              ] GL: Texture max size <2048>
[INFO              ] GL: Texture max units <8>
[INFO              ] Shader: fragment shader: <b'Compiled'>
[INFO              ] Shader: vertex shader: <b'Compiled'>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] ProbeSysfs: device match: /dev/input/event0
[INFO              ] HIDInput: Read event from </dev/input/event0>
[INFO              ] ProbeSysfs: device match: /dev/input/event1
[INFO              ] HIDInput: Read event from </dev/input/event1>
[INFO              ] ProbeSysfs: device match: /dev/input/event2
[INFO              ] HIDInput: Read event from </dev/input/event2>
[INFO              ] Base: Start application main loop
[WARNING           ] stderr: Exception in thread Thread-1:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
[WARNING           ] stderr: Exception in thread Thread-3:
[INFO              ] GL: NPOT texture support is available
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr: Exception in thread Thread-2:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 869, in run
[WARNING           ] stderr:     self._target(*self._args, **self._kwargs)
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/input/providers/hidinput.py", line 594, in _thread_run
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:     " " * 256).split('\x00')[0]
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 869, in run
[WARNING           ] stderr:     self._target(*self._args, **self._kwargs)
[WARNING           ] stderr: TypeError: Type str doesn't support the buffer API
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 869, in run
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/input/providers/hidinput.py", line 594, in _thread_run
[WARNING           ] stderr: 
[WARNING           ] stderr:     self._target(*self._args, **self._kwargs)
[WARNING           ] stderr:     " " * 256).split('\x00')[0]
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/input/providers/hidinput.py", line 594, in _thread_run
[WARNING           ] stderr: TypeError: Type str doesn't support the buffer API
[WARNING           ] stderr:     " " * 256).split('\x00')[0]
[WARNING           ] stderr: 
[WARNING           ] stderr: TypeError: Type str doesn't support the buffer API
[WARNING           ] stderr: 
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "main.py", line 14, in <module>
[WARNING           ] stderr:     TutorialApp().run()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/app.py", line 824, in run
[WARNING           ] stderr:     runTouchApp()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 484, in runTouchApp
[WARNING           ] stderr:     EventLoop.window.mainloop()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/core/window/window_egl_rpi.py", line 77, in mainloop
[WARNING           ] stderr:     self._mainloop()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/core/window/window_egl_rpi.py", line 72, in _mainloop
[WARNING           ] stderr:     EventLoop.idle()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 333, in idle
[WARNING           ] stderr:     Clock.tick_draw()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/clock.py", line 490, in tick_draw
[WARNING           ] stderr:     self._process_events_before_frame()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/clock.py", line 634, in _process_events_before_frame
[WARNING           ] stderr:     for event in events[:]:
[WARNING           ] stderr: KeyboardInterrupt
```
##

**Comment by cdrose** [comment] 2015-02-25 22:33
I can confirm that it works in python2 and not in python3. I dont know if this is specific to my hardware or not. I can recreate the bug running any of the kivy example code.

Hardware is Raspberry Pi (armv6) using this touch screen: http://www.dfrobot.com/index.php?route=product/product&product_id=1062

**Comment by matham** [comment] 2015-03-01 01:59
Can you check whether changing in kivy/input/providers/hidinput.py", line 594 `" " * 256).split('\x00')[0]` to `b" " * 256).split(b'\x00')[0]` fixes it?

**Comment by cdrose** [comment] 2015-03-01 21:50
Making progress, got slightly further before the next error.

[INFO              ] Logger: Record log in /home/fpg/.kivy/logs/kivy_14-12-10_3.txt
[INFO              ] Kivy: v1.9.0-dev
[INFO              ] Python: v3.4.2 (default, Jan 11 2015, 22:16:42)
[GCC 4.9.2 20141224 (prerelease)]
[INFO              ] Factory: 173 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] Text: Provider: sdl2
[INFO              ] Window: Provider: egl_rpi
[INFO              ] GL: OpenGL version <b'OpenGL ES 2.0'>
[INFO              ] GL: OpenGL vendor <b'Broadcom'>
[INFO              ] GL: OpenGL renderer <b'VideoCore IV HW'>
[INFO              ] GL: OpenGL parsed version: 2, 0
[INFO              ] GL: Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO              ] GL: Texture max size <2048>
[INFO              ] GL: Texture max units <8>
[INFO              ] Shader: fragment shader: <b'Compiled'>
[INFO              ] Shader: vertex shader: <b'Compiled'>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] GL: NPOT texture support is available
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] ProbeSysfs: device match: /dev/input/event0
[INFO              ] HIDInput: Read event from </dev/input/event0>
[INFO              ] ProbeSysfs: device match: /dev/input/event1
[INFO              ] HIDInput: Read event from </dev/input/event1>
[INFO              ] ProbeSysfs: device match: /dev/input/event2
[INFO              ] HIDInput: Read event from </dev/input/event2>
[INFO              ] Base: Start application main loop
[INFO              ] HIDMotionEvent: using <b'Logitech USB Keyboard'>
[INFO              ] HIDMotionEvent: using <b'Logitech USB Keyboard'>
[INFO              ] HIDMotionEvent: using <b'RoboPeakUSBDisplayTS'>
[INFO              ] HIDMotionEvent: <b'RoboPeakUSBDisplayTS'> range ABS X position is 0 - 320
[INFO              ] HIDMotionEvent: <b'RoboPeakUSBDisplayTS'> range ABS Y position is 0 - 240
[INFO              ] HIDMotionEvent: <b'RoboPeakUSBDisplayTS'> range ABS pressure is 0 - 1
[WARNING           ] stderr: Exception in thread Thread-3:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 869, in run
[WARNING           ] stderr:     self._target(*self._args, **self._kwargs)
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/input/providers/hidinput.py", line 673, in _thread_run
[WARNING           ] stderr:     for i in range(len(data) / struct_input_event_sz):
[WARNING           ] stderr: TypeError: 'float' object cannot be interpreted as an integer
[WARNING           ] stderr:
[WARNING           ] stderr: Exception in thread Thread-1:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 921, in _bootstrap_inner
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python3.4/threading.py", line 869, in run
[WARNING           ] stderr:     self._target(*self._args, **self._kwargs)
[WARNING           ] stderr:   File "main.py", line 150, in <module>
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/input/providers/hidinput.py", line 673, in _thread_run
[WARNING           ] stderr:     for i in range(len(data) / struct_input_event_sz):
[WARNING           ] stderr:     TouchtracerApp().run()
[WARNING           ] stderr: TypeError: 'float' object cannot be interpreted as an integer
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/app.py", line 824, in run
[WARNING           ] stderr:
[WARNING           ] stderr:     runTouchApp()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 484, in runTouchApp
[WARNING           ] stderr:     EventLoop.window.mainloop()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/core/window/window_egl_rpi.py", line 77, in mainloop
[WARNING           ] stderr:     self._mainloop()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/core/window/window_egl_rpi.py", line 72, in _mainloop
[WARNING           ] stderr:     EventLoop.idle()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/base.py", line 333, in idle
[WARNING           ] stderr:     Clock.tick_draw()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/clock.py", line 490, in tick_draw
[WARNING           ] stderr:     self._process_events_before_frame()
[WARNING           ] stderr:   File "/usr/lib/python3.4/site-packages/kivy/clock.py", line 634, in _process_events_before_frame
[WARNING           ] stderr:     for event in events[:]:
[WARNING           ] stderr: KeyboardInterrupt

**Comment by matham** [comment] 2015-03-01 22:20
Try it with master because in master it seems to have int(...): https://github.com/kivy/kivy/blob/master/kivy/input/providers/hidinput.py#L673.

**Comment by cdrose** [comment] 2015-03-04 03:58
Hi, sorry it took me so long to test.

I can confirm that this update ( https://github.com/kivy/kivy/pull/3072) seems to have fixed the issue.

One comment though, the HIDMotionEvents log messages are now little odd:

[INFO              ] HIDMotionEvent: using <b'Logitech USB Keyboard\x00                                                                                                                                                                                                                                          '>
[INFO              ] HIDMotionEvent: using <b'Logitech USB Keyboard\x00                                                                                                                                                                                                                                          '>

There is a trailing "\x00" followed by many (256?) space characters before the closing ''>"

**Comment by matham** [comment] 2015-03-04 04:59
@cdrose You should consider doing a PR with a fix :).

**Comment by cdrose** [comment] 2015-03-04 05:06
Ive been a bit hesitant to play with the kivy code yet, as I havent dug into it enough to really know how it all fits together. But I'll see what i can do =) Happy to help out where I can!

**Comment by matham** [comment] 2015-03-04 05:08
Well, this is a perfect place to start because the issue here is mostly with manipulating python strings/bytes. So it doesn't involve that much kivy itself.

**Closed** 2018-10-25 22:56 UTC
Labels: Hacktoberfest, easy, py3
