### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by pdsavas** [kivy/kivy#6143] opened 2019-02-08 12:13 UTC
* Python: 3.x
* OS: Raspbian Stretch
* Kivy: 
* Kivy installation method: manual

### Description
I have tried installing Kivy on two different RPi's. Used the manual method and tried compiling locally first. On one system I was able to compile but unable to run any of the demo programs.

Then I tried using the git+install...@master instruction and was able to get Kivy installed. However, on one system, when I try to run the demo programs, I get the following output:

[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_19-02-08_3.txt
[INFO   ] [Logger      ] v1.11.0.dev0, git-775cd93, 20190208
[INFO   ] [Logger      ] v2.7.13 (default, Sept 26, 2018, 18:42:22)
[GCC 6.3.0.20170516]
[INFO   ] [Logger      ] 184 symbols loaded
[INFO   ] [Logger      ] Providers: img_tex, img_dds, img_pil, img_gif (img_sdl2, img_ffpyplayer ignored)
[INFO   ] [Logger      ] Provider: egl_rpi
[INFO   ] [Logger      ] Using the "openGL ES 2" graphics system
[INFO   ] [Logger      ] Backend used (sdl2)
Segmentation fault

On the other RPi, I get the following:

Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from kivy.app import App
ImportError: No module named kivy.app

What did I do wrong?

Thanks,
pete

**Comment by tito** [comment] 2019-02-10 22:22
Duplicate of #6007

**Closed by tito** 2019-02-10 22:22 UTC

**Comment by pdsavas** [comment] 2019-02-12 09:45
Pointing me to that other ticket only addresses one of the issues I had; what about the other?

```
Traceback (most recent call last):
File "main.py", line 15, in 
from kivy.app import App
ImportError: No module named kivy.app
```
Thanks,
pete
