### ISSUE TITLE
Unnecessary raise?

### ISSUE THREAD

**Issue by baseplate-admin** [kivy/kivy#8463] opened 2023-11-16 06:10 UTC
Hi, This raise method is not needed. If python fails to find the package it will automatically raise `ImportError`

https://github.com/kivy/kivy/blob/6ae4fc292373f39ce34563d6c448e8ee7c8fa193/kivy/core/video/video_ffpyplayer.py#L48-L53

**Comment by Julian-O** [comment] 2023-11-16 06:14
Closing as duplicate of #8429 (which I raised, so YEAH! I AGREE!)

**Closed by Julian-O** 2023-11-16 06:14 UTC

**Comment by baseplate-admin** [comment] 2023-11-16 06:16
XD
