### ISSUE TITLE
App's on_stop method gets called twice

### ISSUE THREAD

**Issue by Leva7** [kivy/kivy#4577] opened 2016-09-01 17:00 UTC
If one closes the running app using the OS native cross button, everything goes as expected. However, if one decides to stop the application using the `stop` method, the `on_stop` will be triggered twice. Here's a quick sample to demonstrate the issue:
```
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def on_stop(self):
        print('Stopping!')

    def build(self):
        b = Button(on_release = app.stop)
        return b

app = TestApp()
app.run()
```

Issue seen on Kivy 1.9.2-dev0 for Linux

**Comment by LogicalDash** [comment] 2016-09-01 17:06
I think this is actually to do with how touch events work. Sometimes the user will release the button "between frames" and the touch will get dispatched twice. The standard widgets routinely check if they've handled a given touch object already by storing it in a Property and comparing.

**Comment by Leva7** [comment] 2016-09-01 17:16
@LogicalDash I highly doubt that's the case. Try running the script a few times, the issue persists. I suspect the issue to be in the following.
These are the last lines of code of the `app.py` `run` method:
```
        runTouchApp()
        self.stop()
```

These are the last lines of code of the `base.py` `runTouchApp` method:
```
try:
        if EventLoop.window is None:
            _run_mainloop()
        else:
            EventLoop.window.mainloop()
    finally:
stopTouchApp()
```

And finally, those are the last lines of code of the `app.py` `stop` method:
```
    def stop(self, *largs):
        '''Stop the application.
        If you use this method, the whole application will stop by issuing
        a call to :func:`~kivy.base.stopTouchApp`.
        '''
        self.dispatch('on_stop')
        stopTouchApp()

        # Clear the window children
        for child in self._app_window.children:
self._app_window.remove_widget(child)
```

It seems odd to me that the `stopTouchApp` gets called twice. Perhaps, instead of explicitly calling `stop` at the end of `runTouchApp`, we could dispatch the `on_stop` method and be done with it?

**Comment by dessant** [comment] 2016-09-04 05:08
Duplicate of https://github.com/kivy/kivy/issues/2397.

**Closed by dessant** 2016-09-04 05:08 UTC
