### ISSUE TITLE
kivy 1.8.0 on OSX won't play OGG files [$50]

### ISSUE THREAD

**Issue by winstonwolff** [kivy/kivy#1908] opened 2014-02-21 06:17 UTC
I think the OGG plugin is missing in the 1.8.0 release on Mac. My code worked nicely with 1.7.2. But upon upgrading to 1.8.0, it's complaining: 

[INFO              ] [AudioGstplayer] Using Gstreamer 1.2.1.0
...
[WARNING           ] [AudioGstplayer] No decoder available for type 'audio/ogg'.
[ERROR             ] [AudioGstplayer] Your GStreamer installation is missing a plug-in.
[ERROR             ] [AudioGstplayer] A Ogg demuxer plugin is required to play this stream, but not installed.
[ERROR             ] [AudioGstplayer] GStreamer encountered a general stream error.

**Comment by merriam** [comment] 2015-01-29 00:47
FYI.  This is still open as of v1.9dev.  It causes a 'click' which causes some tests to fail.

FAIL: test_length_simple (kivy.tests.test_audio.AudioGstreamerTestCase)
FAIL: test_length_stopped (kivy.tests.test_audio.AudioGstreamerTestCase)
FAIL: test_length_playing (kivy.tests.test_audio.AudioPygameTestCase)

This is under OS/X.

**Comment by tito** [comment] 2015-01-29 00:50
It's about a packaging issue, not the kivy code itself. This is resolved in the next packaging, but the issue is still open until new packaging is completed.

**Comment by tito** [comment] 2015-01-29 00:51
If you are interested, contact me directly for having a new .dmg.

**Comment by merriam** [comment] 2015-01-29 01:16
I'm interested, but I actually need to work in the dev version.  Simply having a .dmg does not fix the issue in the least; I can't run what I can't build.

**Comment by winstonwolff** [comment] 2015-01-29 05:10
Hi Charles—

I was able to build Kivy from the github repo and run it after a lot of reading of various websites. It was only trying to build a PyInstaller bundle that killed me. Do you want instructions on that?

Winston Wolff
Stratolab - Games for Learning

Play  Electropocalypse -- our new game about electricity -- http://stratolab.com/electropocalypse/

**Comment by merriam** [comment] 2015-01-29 07:40
Thank you.  Would that get ogg to play?   Currently, my OS/X just clicks when trying to play Ogg, gives up on MP3, and plays WAV fine.

**Comment by tito** [comment] 2015-01-29 16:43
More info at https://groups.google.com/forum/#!topic/kivy-dev/rRLeWgLa0LY

**Comment by tito** [comment] 2015-03-02 10:27
This is fixed with the new kivy/kivy-osx packaging tools. Next packaged version will contain the fixes :)

**Closed by tito** 2015-03-02 10:27 UTC
Labels: bounty, core, important, needs-analysis
