### ISSUE TITLE
Cannot build kivy. Dependency error on raspi.

### ISSUE THREAD

**Issue by mm5m** [kivy/kivy#8240] opened 2023-05-12 10:27 UTC
**Software Versions**
* Python: 3.10
* OS: raspus (puppylinux on raspberry pi)
* Kivy: 2.1.0
* Kivy installation method: installed dependencies then python3 -m pip install "kivy[base]" kivy_examples

**Describe the bug**
I have installed all the deps as mentioned [here](https://kivy.org/doc/stable/installation/installation-rpi.html#install-source-rpi)

**Expected behavior**
kivy should be installed.

**To Reproduce**
```python
python3 -m pip install "kivy[base]" kivy_examples
```

**Code and Logs and screenshots**
```python
python3 -m pip install "kivy[base]" kivy_examples
Collecting kivy[base]
  Using cached Kivy-2.1.0.tar.gz (23.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting kivy_examples
  Using cached Kivy_examples-2.1.0-py2.py3-none-any.whl (9.2 MB)
Collecting Kivy-Garden>=0.1.4
  Using cached Kivy_Garden-0.1.5-py3-none-any.whl (4.6 kB)
Collecting pygments
  Using cached Pygments-2.15.1-py3-none-any.whl (1.1 MB)
Collecting docutils
  Using cached docutils-0.20-py3-none-any.whl (577 kB)
Collecting pillow
  Using cached Pillow-9.5.0.tar.gz (50.5 MB)
  Preparing metadata (setup.py) ... done
Collecting requests
  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-py3-none-any.whl (46 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Using legacy 'setup.py install' for pillow, since package 'wheel' is not installed.
Building wheels for collected packages: kivy
  Building wheel for kivy (pyproject.toml) ... error
  error: subprocess-exited-with-error

× Building wheel for kivy (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [88 lines of output]
      [INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_23-05-12_2.txt
      [INFO   ] [Kivy        ] v2.1.0
      [INFO   ] [Kivy        ] Installed at "/initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a/kivy/__init__.py"
      [INFO   ] [Python      ] v3.10.8 (main, May 11 2023, 21:24:20) [GCC 8.3.0]
      [INFO   ] [Python      ] Interpreter at "/initrd/mnt/dev_save/codelab/kivydev/bin/python310"
      [INFO   ] [Logger      ] Purge log fired. Processing...
      [INFO   ] [Logger      ] Purge finished!
       <string>:370: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:373: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       <string>:377: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
       warning: kivy/graphics/common.pxi:9:4: 'const_char_ptr' redeclared
       warning: kivy/graphics/common.pxi:23:4: 'size_t' redeclared
      Current directory is: /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a
      Source and initial build directory is: /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a
      Python path is:
      /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a
      /initrd/mnt/dev_save/codelab/kivydev/lib/python3.10/site-packages/pip/_vendor/pep517/in_process
      /initrd/mnt/tmpfs/tmp/pip-build-env-u3ixeptz/site
      /usr/lib/python310.zip
      /usr/lib/python3.10
      /usr/lib/python3.10/lib-dynload
      /initrd/mnt/tmpfs/tmp/pip-build-env-u3ixeptz/overlay/lib/python3.10/site-packages
      /initrd/mnt/tmpfs/tmp/pip-build-env-u3ixeptz/normal/lib/python3.10/site-packages
      /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a/kivy/modules
      /root/.kivy/mods


      Found Cython at /initrd/mnt/tmpfs/tmp/pip-build-env-u3ixeptz/overlay/lib/python3.10/site-packages/Cython/__init__.py
      Detected supported Cython version 0.29.28
      Using this graphics system: OpenGL ES 2
      GStreamer found via pkg-config
      SDL2 found via pkg-config
      Found brcmEGL and brcmGLES library files for rpi platform at /opt/vc/lib
      SDL2: found SDL header at /usr/include/SDL2/SDL.h
      SDL2: found SDL_mixer header at /usr/include/SDL2/SDL_mixer.h
      SDL2: found SDL_ttf header at /usr/include/SDL2/SDL_ttf.h
      SDL2: found SDL_image header at /usr/include/SDL2/SDL_image.h
      Pango: pangoft2 found via pkg-config
	  {'libraries': ['pangoft2-1.0', 'pango-1.0', 'gobject-2.0', 'glib-2.0', 'fontconfig', 'freetype'], 'include_dirs': ['/initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a/ki
vy/include', '/usr/include/pango-1.0', '/usr/include/harfbuzz', '/usr/include/pango-1.0', '/usr/include/fribidi', '/usr/include/glib-2.0', '/usr/lib/arm-linux-gnueabihf/glib-2.0/include', '/usr/include/uui
d', '/usr/include/freetype2', '/usr/include/libpng16'], 'library_dirs': [], 'extra_link_args': [], 'extra_compile_args': [], 'depends': ['lib/pango/pangoft2.pxi', 'lib/pango/pangoft2.h']}
      ERROR: Dependency for context.pyx not resolved: config.pxi
      ERROR: Dependency for compiler.pyx not resolved: config.pxi
      ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for fbo.pyx not resolved: config.pxi
      ERROR: Dependency for gl_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for instructions.pyx not resolved: config.pxi
      ERROR: Dependency for opengl.pyx not resolved: config.pxi
      ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
      ERROR: Dependency for shader.pyx not resolved: config.pxi
      ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for texture.pyx not resolved: config.pxi
      ERROR: Dependency for vbo.pyx not resolved: config.pxi
      ERROR: Dependency for vertex.pyx not resolved: config.pxi
      ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
      ERROR: Dependency for cgl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
      ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
      ERROR: Dependency for svg.pyx not resolved: config.pxi
      Building extensions in parallel using 4 cores
      Updated build directory to: build/lib.linux-armv7l-cpython-310
      Build configuration is:
       * use_rpi = 1
       * use_egl = 0
       * use_opengl_es2 = 1
       * use_opengl_mock = 0
       * use_sdl2 = 1
       * use_pangoft2 = 1
       * use_ios = 0
       * use_android = 0
       * use_mesagl = 0
       * use_x11 = 0
       * use_wayland = 0
       * use_gstreamer = 1
       * use_avfoundation = 0
       * use_osx_frameworks = 0
       * debug_gl = 0
       * kivy_sdl_gl_alpha_size = 0
       * debug = False
      Updated build/lib.linux-armv7l-cpython-310/kivy/include/config.h
      Updated /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a/kivy/include/config.h
      Updated build/lib.linux-armv7l-cpython-310/kivy/include/config.pxi
      Updated /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a/kivy/include/config.pxi
      Updated build/lib.linux-armv7l-cpython-310/kivy/setupconfig.py
      Updated /initrd/mnt/tmpfs/tmp/pip-install-ef3d3z_m/kivy_a9ecefc27eaf4320b892d32149f6657a/kivy/setupconfig.py
      Detected compiler is unix
	[end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kivy
Failed to build kivy
ERROR: Could not build wheels for kivy, which is required to install pyproject.toml-based projects
```

**Additional context**
I had python 3.11 installed which gave the same error. Then from some Stackoverflow answers and then [official kivy page](https://kivy.org/doc/stable/gettingstarted/installation.html) I learnt that for kivy 2.1.0, python 3.7 to 3.10 is supported. I installed the 3.7 and then 3.10. But I am having the same problem of dependency for both python version. The exact python 3.10  is 3.10.8. Do I need to take a much lower version of 3.10.

kindly help.

**Comment by misl6** [comment] 2023-05-12 17:14
Hi @mm5m !

The pre-release version of Kivy (`2.2.0rc1`) supports Python `3.11` (and we also have `aarch64` pre-built wheels if you want to switch to a 64 bit OS on the RPi)

Pre-built wheels for RPi are only available for `3.7` and `3.9`, via piwheels, and kivy.org/downloads .

Unfortunately, the provided log is not verbose enough to find the root cause of the issue. Can you please try to produce (and attach) a more verbose log? (See: https://pip.pypa.io/en/stable/cli/pip/#cmdoption-v)

**Comment by mm5m** [comment] 2023-05-12 18:47
Thanks for ur reply.
Didn't try the pre-release but have executed the -v with python 3.10. Please have a look at the log https://pastebin.com/2gGMM2Ke
On first line python310 is symlink to the python3.10.8

**Comment by misl6** [comment] 2023-05-13 06:57
From your verbose logs:
```
/usr/bin/ld: cannot find -lgstreamer-1.0
collect2: error: ld returned 1 exit status
```

Is `gstreamer` installed?

And, is `gstreamer` needed in your use-case?

if not:
`USE_GSTREAMER=0 python3 -m pip install "kivy[base]" kivy_examples`

(closing the issue as support, but feel free to jump in one of our support channels.)

**Closed** 2023-05-13 06:57 UTC
Labels: support
