### ISSUE TITLE
Terrible and stupid function on video:               seek(self, percent, precise=True)

### ISSUE THREAD

**Issue by veyron-github** [kivy/kivy#7309] opened 2021-01-04 10:29 UTC
I don't understand why just a stupy function can't set there!  I have search for some operation on  video ,not one use percent to change the position of the video, but most of is using second to change the position.  

I don't think the kivy team doesn't have that capability to set this to second, but why use percent? To show how diffirent you are? I will just think that the guy who set this may have some problem or foolish guy!

Not only this, when I use  'video.seek(percent)', it was amazing that it does't work if the interval is less than 10 seconds. Yes, this is easier to see, when you go to the kivy's examplies about videoplayer, go ahead and play it ,let's change the position by the  ProgressBar or Slider. Don't you see that you can't move the position you want? Is there a 10 second difference? Let's thanks the guy who make it !

platform：Win10； tools: Pycharm or Python IDLE

**Comment by veyron-github** [comment] 2021-01-04 12:10
When I search the history problem of video, I find that this the problem will not be solved soon. I wish there will be  a wise man can solve this problem someday. This the first time I use kivy into my project. There is no time for me to choose another tools. So I have to accept that my project has a shortcoming that could not be solved soon.

**Comment by veyron-github** [comment] 2021-01-04 12:41
Therefore, I suggest adding these temporarily unsolved problems in the official documents to corresponding methods and locations. That way, when someone encounters the problem, they'll know it's not a bug, so they won't spend time trying to fix it.
    I don't want others to have the unhappy experience I had.

**Comment by matham** [comment] 2021-01-05 07:31
This is a duplicate of https://github.com/kivy/kivy/issues/6292.

Also, your tone is not appreciated. This is a community project, so if you find a issue that we haven't fixed, you're welcome to try to fix it. Or make a doc PR indicating that precision seeking is not fully supported.

**Closed by matham** 2021-01-05 07:31 UTC
