### ISSUE TITLE
Scrolling freezes if the cursor goes beyond the window

### ISSUE THREAD

**Issue by Leva7** [kivy/kivy#4381] opened 2016-06-10 13:10 UTC
I've noticed strange behaviour of the default `ScrollView`'s overscroll effect. When I started dragging the content and overscrolled, then, without releasing the mouse button, moved the cursor outside the window and then released, the content stayed overscrolled. It went back to the usual position only when I moved the cursor back into the window (not pressing the mouse button)

**Comment by dessant** [comment] 2016-06-10 13:12
Duplicate of https://github.com/kivy/kivy/issues/2529.

**Closed by dessant** 2016-06-10 13:12 UTC
