### ISSUE TITLE
Linebreaks inside word after closing tags.

### ISSUE THREAD

**Issue by hscpy** [kivy/kivy#7323] opened 2021-01-10 16:04 UTC
**Software Versions**
* Python: 3.6.9
* OS: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic
* Kivy: 1.11.1 and 2.0.0

**Describe the bug**
In markup, when a closing tag is followed by text without space, the line can be broken.

**Expected behavior**
Markup tags should not break lines inside words and before punctuation, or, at least they should not affect the way lines are broken.

**Code and Logs and screenshots**
```python
from kivy.app import App
from kivy.config import Config
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.label import Label

Config.set('graphics', 'width', 368)
Config.set('graphics', 'height', 500)
Config.set('graphics', 'resizable', 1)

Builder.load_string('''
<MyLabel>:
    text_size: self.width, None
    size: self.texture_size
    font_size: 30
''')

class MyLabel(Label):
    pass

class MyApp(App):
    def build(self):
        text0 = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
        text1 = 'Lorem ipsum dolor sit [color=ff0000ff]amet[/color], consectetur adipiscing [i]eli[/i]t.'
        text2 = 'Lorem ipsum dolor sit [color=00ff00ff]amet,[/color] consectetur adipiscing elit.'
        b = BoxLayout(orientation='vertical')
        b.add_widget(MyLabel(text=text0))
        b.add_widget(MyLabel(text=text1, markup=True))
        b.add_widget(MyLabel(text=text2, markup=True))
        return b

MyApp().run()
```
![image](https://user-images.githubusercontent.com/77178604/104128042-61faba00-5376-11eb-88d4-3a33badafef2.png)

**Comment by Julian-O** [comment] 2023-11-02 02:48
This is a duplicate of #7496. [I know: This was earlier, but closing anyway]

**Closed by Julian-O** 2023-11-02 02:48 UTC
