### ISSUE TITLE
kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin on Mac

### ISSUE THREAD

**Issue by yanlb** [kivy/kivy#6521] opened 2019-07-04 07:31 UTC
When I click on the button that calls the function (v_player) to play the corporate video I get this error:

```File "kivy/lib/gstplayer/_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin```

I'm developing on a Mac (Mojave version: 10.14.5) using PyCharm (2019.1.1).

Project Interpreter: (Python 3.7) 
Cython 0.29.7 
Kivy 1.10.1 
Kivy-Garden 0.1.4
Pygments 2.3.1
certifi 2019.3.9
chardet 3.0.4
docopt 0.6.2
docutils 0.14
future 0.17.1 
gstreamer-player 1.1.2
idna 2.8
mutagen 1.42.0 openstep-parser
pbxproj 2.5.1
pip 19.0.3 
requests 2.21.0 
setuptools 40.8.0 
urllib3 1.24.2 
wheel 0.33.1

I have reviewed the installation, updated or reinstalled the packages: 
```
     gstreamer 
     gst-plugins-base 
     gst-plugins-good 
     gst-plugins-bad 
     gst-plugins-ugly
```

I also did this: (What did work was removing the 'gstplayer' in my kivy install. Where ever you kivy install is some where in 'site-packages/kivy/lib/gstplayer' Do rm -R site-packages/kivy/lib/gstplayer Again, this path should be replaced with your local installation path.

Based on the comments here in this issue on the kivy github site. There the directory is called 'gstreamer'. In my installation it was called 'gstplayer'.) And not work for me.

Ptyhon code:

class Presentation(Screen):
```

    def v_player(self):
        if App.get_running_app().play == 0:
            App.get_running_app().play = 1
            App.get_running_app().video = Video(source='data/video/video.mp4')
            App.get_running_app().video.state = 'play'
            App.get_running_app().video.allow_stretch = True
            self.add_widget(App.get_running_app().video)
        else:
            App.get_running_app().play = 1
```
.kv Code:

```
        FloatLayout:
            ImageButton:
                source: 'data/icons/playback_play_icon48.png'
                size_hint: .5, .5
                pos_hint: {'center_y': 0.50, 'center_x': 0.50}
                on_press: root.v_player()
```
I have read a lot on Google, I have reinstalled everything, I have tried several solutions like those described above but I have not been able to solve the problem

Any idea? Thanks in advance

---------------------------------------

if I try to play the video using this command I also get error: 
```
python3 -m kivy.uix.videoplayer Library/Python/3.7/share/kivy-examples/widgets/cityCC0.mpg 
```

I get this error:

```
[INFO   ] Logger: Record log in /Users/PC/.kivy/logs/kivy_19-07-05_6.txt
[INFO   ] Kivy: v1.10.1
[INFO   ] Python: v3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_imageio, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] VideoGstplayer: Using Gstreamer 1.10.4.0
[INFO   ] Video: Provider: gstplayer
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <b'2.1 INTEL-12.9.22'>
[INFO   ] GL: OpenGL vendor <b'Intel Inc.'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) Iris(TM) Plus Graphics 640'>
[INFO   ] GL: OpenGL parsed version: 2, 1
[INFO   ] GL: Shading version <b'1.20'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[ERROR  ] Image: Error loading texture Library/Python/3.7/share/kivy-examples/widgets/cityCC0.mpg
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[WARNING] stderr:     "__main__", mod_spec)
[WARNING] stderr:   File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[WARNING] stderr:     exec(code, run_globals)
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/uix/videoplayer.py", line 677, in <module>
[WARNING] stderr:     runTouchApp(player)
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/base.py", line 502, in runTouchApp
[WARNING] stderr:     EventLoop.window.mainloop()
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
[WARNING] stderr:     self._mainloop()
[WARNING] stderr:   File "/Users/PCLibrary/Python/3.7/lib/python/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
[WARNING] stderr:     EventLoop.idle()
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/base.py", line 346, in idle
[WARNING] stderr:     Clock.tick_draw()
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/clock.py", line 588, in tick_draw
[WARNING] stderr:     self._process_events_before_frame()
[WARNING] stderr:   File "kivy/_clock.pyx", line 427, in kivy._clock.CyClockBase._process_events_before_frame
[WARNING] stderr:   File "kivy/_clock.pyx", line 467, in kivy._clock.CyClockBase._process_events_before_frame
[WARNING] stderr:   File "kivy/_clock.pyx", line 465, in kivy._clock.CyClockBase._process_events_before_frame
[WARNING] stderr:   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/uix/video.py", line 183, in _do_video_load
[WARNING] stderr:     self._video = CoreVideo(filename=filename, **self.options)
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/core/video/video_gstplayer.py", line 56, in __init__
[WARNING] stderr:     super(VideoGstplayer, self).__init__(**kwargs)
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/core/video/__init__.py", line 84, in __init__
[WARNING] stderr:     self.filename = kwargs.get('filename')
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/core/video/__init__.py", line 116, in <lambda>
[WARNING] stderr:     lambda self, x: self._set_filename(x),
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/core/video/__init__.py", line 113, in _set_filename
[WARNING] stderr:     self.load()
[WARNING] stderr:   File "/Users/PC/Library/Python/3.7/lib/python/site-packages/kivy/core/video/video_gstplayer.py", line 68, in load
[WARNING] stderr:     self.player.load()
[WARNING] stderr:   File "kivy/lib/gstplayer/_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load
[WARNING] stderr: kivy.lib.gstplayer._gstplayer.GstPlayerException: Unable to create a playbin
```
Any idea? Thanks...

-------------

I have debugged step by step and the only problem that I have seen before the error jumped and hang up the app is:

'NoneType' object has no attribute 'get_duration'

On file: video_gsplayer.py 
In sefl properties: 
```
duration: = {str} 'Traceback (most recent call last):\n File "/Aplications/PyCharm CE.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 178, in _getPyDictionary\n'attr = getattr(var...
```

Any idea?

**Comment by matham** [comment] 2019-09-16 21:05
Duplicate of https://github.com/kivy/kivy/issues/5886.

**Closed by matham** 2019-09-16 21:05 UTC
