### ISSUE TITLE
External Link with Button not Working

### ISSUE THREAD

**Issue by NisargJani** [kivy/kivy#3287] opened 2015-04-21 09:10 UTC
I am using this code to attach a link with button and when button got pressed by user a link will be directly open in a web browser....

but the problem is that when i am launching the app it just directly lauch link...without clicking on button

code  is :

from kivy.app import App
from kivy.uix.button import Button
import webbrowser
 

class TestApp(App):
    def build(self):
        Button(text='help button')
    Button.bind(on_press=webbrowser.open('http://www.google.com')
    return Button

 
TestApp().run()

**Comment by dessant** [comment] 2015-04-21 09:15
This is not a bug, you're calling the function on that line instead of assigning it to an event. This should be done instead, when you must pass arguments to the function:
```python
from functools import partial
Button.bind(on_press=partial(webbrowser.open, 'http://www.google.com'))
```

**Closed by dessant** 2015-04-21 09:15 UTC

**Comment by dessant** [comment] 2015-04-21 09:17
Also, the rest of your code does not make much sense either, i would advise you to read the programming guide in the docs.

**Comment by NisargJani** [comment] 2015-04-21 09:25
Its not working bro...please help me

**Comment by dessant** [comment] 2015-04-21 09:26
https://github.com/kivy/kivy/issues/3264#issuecomment-92020945
