### ISSUE TITLE
Copying unicode string to clipboard on Android goes wrong

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy#3606] opened 2015-08-31 16:48 UTC
Copying a string with Unicode characters like '愛' on Android results into 'æ ' (works on Ubuntu 14.04 though).
It is irrelevant whether Clipboard.copy() or select text in a textinput with native android copy option is used, but don't work properly.

According to @kived the relevant code for this is:
https://github.com/kivy/kivy/blob/master/kivy/core/clipboard/clipboard_android.py#L82

It would be nice to be able to copy unicode strings properly :)

**Comment by Ramalus** [comment] 2015-08-31 21:20
I'm having a problem that when sending an android notification using plyer where it should show the string "São Paulo" it shows "SÃ£o Paulo". 
This is probably related to this issue. 
The problem is that I have no idea how to debug this...

**Comment by NumesSanguis** [comment] 2015-09-05 14:02
Might be related to earlier issue I posted:  #2345

**Comment by NumesSanguis** [comment] 2016-09-23 12:40
I thought switching to Python 3.5 would solve the case, but it still crashes on Android 6. (I build my app with `python3 -m buildozer android debug deploy run`, with buildozer-master cloned today.

Here is an example of the problem: https://github.com/SurafuSoft/kivy_doubletap_clipboard

Print statement crash: https://github.com/SurafuSoft/kivy_doubletap_clipboard/blob/master/main.py#L58
Copy to clipboard crash: https://github.com/SurafuSoft/kivy_doubletap_clipboard/blob/master/main.py#L67

**Comment by tshirtman** [comment] 2019-04-22 18:42
I can copy/paste unicode text in recent kivy apps, i assume this is fixed, at least for python3, closing, feel free to reopen or open a new one if similar bugs are observed.

**Closed by tshirtman** 2019-04-22 18:42 UTC
Labels: important, needs-analysis, platform-android
