### ISSUE TITLE
inspector not working in kivy-1.10.0 Popup

### ISSUE THREAD

**Issue by rjungbeck** [kivy/kivy#5369] opened 2017-09-06 17:12 UTC
Opening inspector (Ctrl+E) on a Popup window shows the fields from the underlying window (and not from the Popup). 

This makes using inspector on Popups (which could be the bigger part of an application) impossible.

**Comment by bionoid** [comment] 2017-09-07 09:14
I cannot reproduce this on Windows, can you be more specific about the context in which this fails? I tested with this code:

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
#:import F kivy.factory.Factory

<TestPopup@Popup>:
	size_hint: .5, .5
	Button:
		on_press: root.dismiss()

Button:
	on_press: F.TestPopup().open()
'''))
```

**Comment by rjungbeck** [comment] 2017-09-07 14:08
The context is a bit more complicated:

`````
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
#:import F kivy.factory.Factory


<TestPopup2@Popup>:
    title: "test2"
    size: 300, 300
    size_hint: None, None
    Button:
        size: 100, 100
        size_hint: None, None
        on_press: root.dismiss()
        
<TestPopup@Popup>:
    title: "test"
    size: 300, 300
    size_hint: None, None
    Button:
        size: 200, 200
        size_hint: None, None
        on_press: F.TestPopup2().open()

BoxLayout:
    size: 800,480
    size_hint: None, None

    Label:
        size: 200, 500
        size_hint: None, None
        text: "Root"
        
    Button:
        size: 200, 500
        size_hint: None, None
        on_release: F.TestPopup().open()
    
    
    '''))

`````
Try to activate the inspector on the button on the second popup (where the button overlap with the underlaying popups button)  It activates the wrong field..

(Test on Mac)

**Comment by rjungbeck** [comment] 2017-09-10 09:05
From looking at the source:
* Each additional Popup (which is a ModalView) is added as the first child widget to the parent window (in uix/modalview.py 180)
* But the search in modules/inspector.py 391 reverses this order before searching (with pick) and takes the first match.

So although the 2nd Popup is displayed on top, the widget on the underlaying popup is found.

So one of these seems to be wrong .

But which one?

**Comment by KeyWeeUsr** [comment] 2017-09-10 21:11
It's definitely a problem in the Inspector module as the `ModalView` / `Popup` should by default add itself as a child to the `Window` on top of everything (i.e. as the *first* child).

**Comment by KeyWeeUsr** [comment] 2017-09-12 21:30
Fixed in master branch.

**Closed by KeyWeeUsr** 2017-09-12 21:30 UTC
Labels: confirmed, unittested
