### ISSUE TITLE
White empty window: random chance, no error logs, system specific.

### ISSUE THREAD

**Issue by Ansebi** [kivy/kivy#5974] opened 2018-10-07 10:14 UTC
### Versions

* Python: 3.7.0
* OS: Windows 10 64 bit
* Kivy: 1.10.1
* Kivy installation method: standard 
    (cmd as admin,
    python -m pip install --upgrade pip wheel setuptools
    python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
    python -m pip install kivy)

### Description
My kivy apps are **working fine on windows 7** 64 bit,
on Windows 10 64 bit I have a random chance to run the app and get it working.
But most of the times
I get an empty white kivy window
responsive in terms of sound and the command line.

There are no error logs occuring.

**Kivy examples** are working the same way
(random (about 10-20%) chance of success,
mostly white window)

(seems to be a duplicate of #5931, but my is white only and there's a chance of success)

### Code and Logs

```python

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.image import Image


class MyApp(App):
    def build(self):
        my_layout = BoxLayout()

        background=Image(
            source="background.png"
            )
        my_layout.add_widget(background)

        return my_layout

if __name__ == "__main__":
    MyApp().run()



I get NO error logs, only the usual stuff:
[INFO   ] [Logger      ] Record log in C:\Users\Anthony\.kivy\logs\kivy_18-10-07_3.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.5.13521 Compatibility Profile Context 24.20.11016.4'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon HD 7800 Series'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop

```

**Comment by matham** [comment] 2018-10-07 17:42
Duplicate of https://github.com/kivy/kivy/issues/5949. Please see that issue for possible solutions, although we couldn't figure out the actual issue. There isn't really much we can do without access to the system and doesn't seem like a bug in kivy itself.

I would suggest you go to the menufacturer's website and update the graphics drivers to the latest and see if it fixes it. It could be an issue with the dependencies, but I'm not sure what we can do.

**Closed by matham** 2018-10-07 17:42 UTC
