### ISSUE TITLE
Show/hide mouse cursor

### ISSUE THREAD

**Issue by Moshtael** [kivy/kivy#3735] opened 2015-10-29 17:16 UTC
The configuration token 'show_cursor' in the section 'graphics' does not work in Kivy 1.9. 
http://kivy.org/docs/api-kivy.config.html?highlight=show_cursor 

Run any Kivy 1.9 app, F1 to get to settings, turn 'Mouse cursor' off - does not hide the mouse. This worked in previous versions of Kivy. 

Also, the solution to make the cursor transparent also no longer works:
from pygame import cursors, mouse
cursor = cursors.load_xbm('transparent_mouse.xbm', 'transparent_mouse-mask.xbm')
mouse.set_cursor(*cursor)

This issue is discussed here: https://groups.google.com/forum/#!searchin/kivy-users/cursor%7Csort:date/kivy-users/_XIstTbEP4o/SjQ_hjRGAwAJ

**Comment by dessant** [comment] 2015-10-29 17:21
Duplicate of https://github.com/kivy/kivy/issues/3735. You could use the development version, it is fixed in master. Pygame has been deprecated in favor of sdl2.

**Closed by dessant** 2015-10-29 17:21 UTC
