### ISSUE TITLE
Animation Sequence Fails on Second Use

### ISSUE THREAD

**Issue by DaytonaJohn** [kivy/kivy#6795] opened 2020-03-24 16:26 UTC
**Software Versions**
* Python: v3.6.9
* OS: Ubuntu 18.04 
* Kivy: v1.11.1
* Kivy installation method: pip

When an Animation is created using `+`, producing a Sequence, it works fine when calling `start()` on one Widget. However, if `start()` is called for a second Widget before the first gets very far, then the second Widget will only be animated by the first part of the Sequence.

Having searched known bugs, it appears that this may have been addressed in prior releases, but it is still in version 1.11.1.

**Expected behavior**
When `start()` is used more than once, all Widgets passed in the `start()` calls should be animated through the entire sequence.

Here is a simple example that demonstrates the problem:

```
from kivy.animation import Animation
from kivy.app import App
from kivy.clock import Clock
from kivy.lang import Builder

kv = '''
FloatLayout:
    Label:
        id: one
        text: 'One'
        size_hint: None, None
        size: 50, 50
        pos: 10, 10
    Label:
        id: two
        text: 'Two'
        size_hint: None, None
        size: 50, 50
        pos: 600, 500
'''

class AnimBugApp(App):
    def build(self):
        Clock.schedule_once(self.start_anim)
        return Builder.load_string(kv)

    def start_anim(self, dt):
        one = self.root.ids.one
        two = self.root.ids.two
        anim = Animation(font_size=40, d=2) + Animation(pos=(300, 200), d=2)
        anim.start(one)
        anim.start(two)

AnimBugApp().run()

```
When the above code is run, Label `one` is animated as expected, but Label `two` only gets the first Animation of the Sequence (the `font_size` is animated), but the second Animation of the Sequence is not applied to Label `two`.

I suspect this is due to this code from `Sequence':

    def on_anim1_complete(self, instance, widget):
        self.anim1.unbind(on_complete=self.on_anim1_complete)
        self.anim2.start(widget)

When `anim1` completes on Label `one`, the above code unbinds the `on_complete` method for `anim1`. Now, when `anim1` completes on Label `two`, the above code is not triggered (since the `on_complete` was unbound) and `anim2` is not started for Label `two`.

Here is the log:

> /usr/bin/python3 /home/jra/PycharmProjects/kivyPlay/AnimationBug.py
> [INFO   ] [Logger      ] Record log in /home/jra/.kivy/logs/kivy_20-03-24_9.txt
> [INFO   ] [Kivy        ] v1.11.1
> [INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.6/dist-packages/kivy/__init__.py"
> [INFO   ] [Python      ] v3.6.9 (default, Nov  7 2019, 10:44:02) 
> [GCC 8.3.0]
> [INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
> [INFO   ] [Factory     ] 184 symbols loaded
> [INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.0
> [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif 
> [INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
> [INFO   ] [GL          ] Using the "OpenGL" graphics system
> [INFO   ] [GL          ] Backend used <sdl2>
> [INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 390.116'>
> [INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
> [INFO   ] [GL          ] OpenGL renderer <b'GeForce 840M/PCIe/SSE2'>
> [INFO   ] [GL          ] OpenGL parsed version: 4, 6
> [INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
> [INFO   ] [GL          ] Texture max size <16384>
> [INFO   ] [GL          ] Texture max units <32>
> [INFO   ] [Window      ] auto add sdl2 input provider
> [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
> [INFO   ] [Text        ] Provider: sdl2
> [INFO   ] [ProbeSysfs  ] device match: /dev/input/event5
> [INFO   ] [MTD         ] Read event from </dev/input/event5>
> [INFO   ] [ProbeSysfs  ] device match: /dev/input/event4
> [INFO   ] [MTD         ] Read event from </dev/input/event4>
> [INFO   ] [Base        ] Start application main loop
> [WARNING] [MTD         ] Unable to open device "/dev/input/event5". Please ensure you have the appropriate permissions.
> [INFO   ] [GL          ] NPOT texture support is available
> [WARNING] [MTD         ] Unable to open device "/dev/input/event4". Please ensure you have the appropriate permissions.
> [INFO   ] [WindowSDL   ] exiting mainloop and closing.
> [INFO   ] [Base        ] Leaving application in progress...
> 
> Process finished with exit code 0
>

**Comment by gottadiveintopython** [comment] 2020-03-25 09:16
The issue is fixed in #5926 .
You need to merge it by yourself though.

**Comment by gottadiveintopython** [comment] 2020-03-26 11:00
You can use #5926

**Comment by gottadiveintopython** [comment] 2020-05-07 12:22
#5926 was merged.

**Closed by gottadiveintopython** 2020-05-07 12:22 UTC
