### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by Kanfit** [kivy/kivy#7331] opened 2021-01-16 07:50 UTC
Any reason kivy doesn't have tooltip? Yes, can be done using a workaround. Would be nice to have tooltip as a standard feature.

**Comment by matham** [comment] 2021-01-22 00:08
This is a duplicate of https://github.com/kivy/kivy/issues/6717

**Closed by matham** 2021-01-22 00:08 UTC

**Comment by pythonic64** [comment] 2022-02-02 15:51
Feature #7658 enables writing of hover behavior and that's not far from tooltip behavior mixin. 

You can find working hover event manager and hover behavior at https://github.com/pythonic64/hover.
