### ISSUE TITLE
Crash with unicode_literals: expected str, got unicode

### ISSUE THREAD

**Issue by Fak3** [kivy/kivy#4379] opened 2016-06-09 22:01 UTC
Hi. I am using current master kivy version and python2.7 on linux. I am experiencing a crash with following error:

```
 Traceback (most recent call last):
   File "mmain0.py", line 27, in <module>
     MyApp().run()
   File "/home/u1/.virtualenvs/rest/lib/python2.7/site-packages/kivy/app.py", line 802, in run
     root = self.build()
   File "mmain0.py", line 24, in build
     return Label()
   File "/home/u1/.virtualenvs/rest/lib/python2.7/site-packages/kivy/uix/label.py", line 275, in __init__
     super(Label, self).__init__(**kwargs)
   File "/home/u1/.virtualenvs/rest/lib/python2.7/site-packages/kivy/uix/widget.py", line 345, in __init__
     Builder.apply(self, ignored_consts=self._kwargs_applied_init)
   File "/home/u1/.virtualenvs/rest/lib/python2.7/site-packages/kivy/lang/builder.py", line 447, in apply
     self._apply_rule(widget, rule, rule, ignored_consts=ignored_consts)
   File "/home/u1/.virtualenvs/rest/lib/python2.7/site-packages/kivy/lang/builder.py", line 492, in _apply_rule
     rule.create_missing(widget)
   File "/home/u1/.virtualenvs/rest/lib/python2.7/site-packages/kivy/lang/parser.py", line 281, in create_missing
     widget.create_property(name, value)
 TypeError: Argument 'name' has incorrect type (expected str, got unicode)
```

This happens every time if an app has **from ____future____ import unicode_literals** in the beginning of the .py file and it has undefined property assignment in the kv language. As written in the docs, kivy should automatically create the ObjectProperty, but it crashes.

Example app: 

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from kivy.app import App
from kivy.uix.label import Label

from kivy.lang import Builder


Builder.load_string('''
<Label>:
    lol: True
    text: 'Hello World'
''')


class MyApp(App):
    def build(self):
        return Label()

if __name__ == '__main__':
    MyApp().run()
```

**Comment by Abysselene** [comment] 2018-04-20 09:42
An old post but I get the same problem.
It doesn't do that for me when I use python3.5 but I get the same error with python2.7.

Debugging shows me that the problem is when builder imports the kv file (or in your case a part of your file) then IF the file is in utf-8 in this case even though the value 'Hell world' is str, the property (called name in widget.create_property(name, value)) text is imported as a u'text' so an Unicode, not a str.
I don't have a solution yet if we keep utf-8 but at least we know why it crashes.
At worse in the parser file you could test if type is unicode then decode('utf-8') to get a str.

**Comment by kuzeyron** [comment] 2018-04-20 11:15
Remove `from __future__ import unicode_literals`.

**Comment by Julian-O** [comment] 2023-11-09 09:08
Closing because we no longer support Python 2.x

**Closed by Julian-O** 2023-11-09 09:08 UTC
