### ISSUE TITLE
Properties within f-string not binded

### ISSUE THREAD

**Issue by damienflament** [kivy/kivy#6297] opened 2019-05-11 07:29 UTC
### Versions

* Python: 3.7.3
* OS: ArchLinux (kernel 5.0.11)
* Kivy: 1.10.1
* Kivy installation method: Poetry (pip)

### Description

Within KV files, the syntax `"{}".format(object.property)` binds correctly, but the syntax `f"{object.property}"` does not.

In the example below:
 - the first label is just a raw binding,
 - the second label uses the `format()` function,
 - the third label uses a `f-string`.

### Code and Logs

```python

from kivy.app import App
from kivy.lang import Builder

kv = r"""
BoxLayout:
    orientation: 'vertical'

    TextInput:
        id: text_input
        text: "foo"
    Label:
        text: text_input.text
    Label:
        text: "text input value using `format()`: {}".format(text_input.text)
    Label:
        text: f"text input value using f-string: {text_input.text}"

"""
class SandboxApp(App):
    def build(self):
        return Builder.load_string(kv)

def main():
    SandboxApp().run()

if __name__ == '__main__':
    main()
```

![image](https://user-images.githubusercontent.com/2023682/57566872-8b10bd80-73d1-11e9-82ba-a7eb4a0b10cc.png)

**Comment by matham** [comment] 2019-05-11 15:01
I took a quick look and python ast has a new node for f-strings (called `FormattedValue`). This means that we should be able to implement using the ast parser.

If I have time in the future, I plan to update the kv compiler branch to drop the python syntax and instead stick only with traditional kv syntax and try to get that into kivy. Then it should be easy to add support for this in the ast parsing step.

**Comment by brady-ds** [comment] 2020-08-10 20:04
Duplicate of #6108?

**Comment by tshirtman** [comment] 2020-08-13 16:54
closing as duplicate of #6108

**Closed by tshirtman** 2020-08-13 16:54 UTC
Labels: feature
