### ISSUE TITLE
color[3] value ignored

### ISSUE THREAD

**Issue by jligeza** [kivy/kivy#4233] opened 2016-04-27 13:26 UTC
The alpha channel isn't respected as it [should](https://kivy.org/docs/api-kivy.uix.label.html#kivy.uix.label.Label.color)

This label should be gray, but is bright white:

```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.lang import Builder

x = Builder.load_string('''
Label:
    text: 'test'
    color: 1, 1, 1, .3
''')


class Test(App):
    def build(self):
        return x

Test().run()
```

**Comment by dessant** [comment] 2016-04-27 13:28
@jligeza, which version of kivy are you using?

**Comment by jligeza** [comment] 2016-04-27 13:29
The current master branch.

**Comment by dessant** [comment] 2016-04-27 13:30
@jligeza, please set logging to debug and share the console output. I could not reproduce the issue with the sdl2 text provider.

**Comment by jligeza** [comment] 2016-04-27 13:35
@dessant I just ran it with python 3, and it works fine, but breaks on python 2.

http://pastebin.com/7Lv3BXAy

**Comment by dessant** [comment] 2016-04-27 13:37
```
[INFO   ] [Text        ] Provider: pygame
```
The pygame provider was deprecated (it should be `Provider: sdl2` by defalut), how did you install kivy?

**Comment by dessant** [comment] 2016-04-27 13:42
There was a pr for pygame text alpha, but i don't know if it was confirmed to work.
https://github.com/kivy/kivy/pull/4047

**Comment by jligeza** [comment] 2016-04-27 13:43
I've installed it by cloning master branch, then `sudo python setup.py install`. However, I might have overriden some older installation, where I used the ppa key from the linux installation page.

**Comment by dessant** [comment] 2016-04-27 13:48
Try uninstalling everything kivy for Python 2, install cython and these dependencies:
https://kivy.org/docs/installation/installation-linux.html#dependencies-with-sdl2

Then clone again and compile/install kivy, the installation logs will have to mention `USE_SDL2=1`.

**Comment by dessant** [comment] 2016-04-27 13:51
@akshayaurora, was #4047 working? Or are we closing the issue anyway because of the deprecation?

**Comment by jligeza** [comment] 2016-04-27 14:17
It works with sdl2, thank you.

**Comment by jligeza** [comment] 2016-04-28 13:11
@dessant I have to use pygame on android, because sdl2 there is too buggy/problematic, so personally I wouldn't call the problem depreciated.

**Comment by dessant** [comment] 2016-04-28 13:17
@jligeza, I understand your situation, but the pygame providers were deprecated, and that means we are not tracking pygame specific issues anymore, but patches may be accepted.

Try pinging @akshayaurora about #4047, it was supposed to fix the issue you're facing.

**Comment by inclement** [comment] 2016-04-28 13:24
I'm not sure if we should really call pygame deprecated on android without actually formally announcing it...but on the other hand, maybe we should just do that!

**Comment by akshayaurora** [comment] 2016-04-28 14:00
We need to fix these issues till we officially do deprecate it.

**Comment by dzmitrykrukouski** [comment] 2016-05-04 12:46
Hi. 

I try to change background color in ActionBar and ScreenManager, but it's doesn't work.
In ActionBar i type `background_color: 234, 40, 0, 1` and color must be RED, but color is YELLOW

In ScreenManager i try to use this code. It's work  with python 3.4, but not with 2.7
```
<ScreenManager>:
    pos_hint: {'top': 0.9}
    canvas:
        Color:
            rgb: 224/255, 245/255, 238/255, 1
        Rectangle:
            size: self.size
            pos: self.pos
```

My debug logging 
http://pastebin.com/BT4ndmd2

**Comment by inclement** [comment] 2016-05-04 12:49
You should declare colours in the range 0-1, not 0-255, following OpenGL
conventions.

When you do divide appropriately with 224/255, with python2 this uses
integer division in which case the answer is 0, while in python3 it uses
float division. You can replace 255 with 255.0, or float(255), or a
number of other options, or (probably best) add 'from __future__ import
division'.

**Comment by dzmitrykrukouski** [comment] 2016-05-04 12:54
Thanks for the quick response.

**Comment by Julian-O** [comment] 2023-11-11 10:10
PyGame has long been deprecated now. #6313

Closing as won't fix.

**Closed by Julian-O** 2023-11-11 10:10 UTC
Labels: PyGame
