### ISSUE TITLE
Backticks in strings are incorrectly handled in Kivy 2.1.0

### ISSUE THREAD

**Issue by sanderland** [kivy/kivy#7839] opened 2022-03-09 10:31 UTC
This does not happen in the default font, but does in e.g. NotoSans.
I initially thought it was creating accented characters, but on closer inspection it is simply offset.

```import kivy
import kivy
from kivy.app import App
from kivy.uix.button import Button

class ButtonApp(App):
    def build(self):
        btn = Button(text="`push` Me!",font_name="NotoSans-Regular.ttf")
        return btn


root = ButtonApp()
root.run()
```

Kivy 2.0.0
![image](https://user-images.githubusercontent.com/48946947/157423993-6f14c8fc-f9f5-4914-8a8e-24ce67a9c5a5.png)

Kivy 2.1.0

![image](https://user-images.githubusercontent.com/48946947/157423829-885e9665-01e8-47ff-a711-4067874aa149.png)

My current workaround is to simply use ' instead of ` for quoting

**Comment by p0lygun** [comment] 2022-03-10 12:45
@sanderland , I am unable to reproduce the error 
```py
Button(text="`Test`")
```

![image](https://user-images.githubusercontent.com/22869882/157664024-ae331199-54d5-4e95-9a19-8dd5f86b0592.png)

```py
Button(text="`Test`", font_name="CascadiaMonoPL-Regular.ttf")
```

![image](https://user-images.githubusercontent.com/22869882/157664280-f8d63595-5578-4361-83f7-ea2b697b4122.png)

```py
Button(text="`Test`", font_name="NotoSans-Regular.ttf")
```

![image](https://user-images.githubusercontent.com/22869882/157664148-55bcfca9-e552-4bb9-acbd-7382881f489d.png)

```py
Button(text="`Test` Test", font_name="NotoSans-Regular.ttf")
```

![image](https://user-images.githubusercontent.com/22869882/157664487-eb085a7e-d909-4398-9257-d6427532c2df.png)

**Comment by sanderland** [comment] 2022-03-10 12:54
Do you have this in the same directory as the app (or otherwise available?)
[NotoSans-Regular.zip](https://github.com/kivy/kivy/files/8223497/NotoSans-Regular.zip)

**Comment by p0lygun** [comment] 2022-03-10 13:03
tried both ways, same result

**Comment by Julian-O** [comment] 2023-10-31 10:17
Problem happens for me: back ticks overlaying push Me!

Windows 11
SDL2
Kivy 2.2.1

**Comment by Julian-O** [comment] 2023-10-31 10:21
It is a bug in the font: https://github.com/google/fonts/issues/3094

A new version is available, and when I used it the problem was fixed.

Closing as not Kivy's fault!

**Closed by Julian-O** 2023-10-31 10:21 UTC
Labels: Status: Needs-analysis, Priority: Medium
