### ISSUE TITLE
Kivy- Black screen in Label

### ISSUE THREAD

**Issue by rupjyoti10** [kivy/kivy#5090] opened 2017-03-31 05:56 UTC
I am new in kivy , trying to fetch 38000 length single string in a label but its not working, comes black screen. I am trying to do in scrolllabel also but I can't do it . Can you help me please. My Sample code is

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.scrollview import ScrollView
kv = """

<Test>:
    ScrollView:
        center_x: (root.width/2)
        top: (root.top/2)+dp(130)
        size: dp(320), dp(395)
        Label:
            text:"String goes here"
            size_hint_y: None
            text_size: self.width, None
            height: self.texture_size[1]
            color:(1,1,1,1)
"""

class Test(BoxLayout):
    pass
class TestApp(App):
    def build(self):
        return Test()

if __name__ == '__main__':
    Builder.load_string(kv)
    TestApp().run()

**Comment by KeyWeeUsr** [comment] 2017-03-31 06:42
Duplicate of #2119.

**Closed by KeyWeeUsr** 2017-03-31 06:42 UTC
