### ISSUE TITLE
ModalView Borders bug

### ISSUE THREAD

**Issue by alexg93333** [kivy/kivy#8539] opened 2023-12-29 17:17 UTC
The borders of the ModalView seem to be bugged. The RecycleView items are exceeding them.

```
from kivy.app import App
from kivy.uix.recycleview import RecycleView
from kivy.uix.recyclegridlayout import RecycleGridLayout
from kivy.uix.modalview import ModalView

class MyApp(App):
    def build(self):
        recycle_layout = RecycleGridLayout(cols=3)
        recycle_layout.size_hint_y = None
        recycle_layout.bind(minimum_height=recycle_layout.setter("height"))

        recycle_view = RecycleView()
        recycle_view.add_widget(recycle_layout)
        recycle_view.viewclass = 'Label'
        recycle_view.data = [{'text': str(x)} for x in range(123)]

        modal_view = ModalView()
        modal_view.size_hint=(0.5,0.5)        
        modal_view.add_widget(recycle_view)

        from kivy.uix.button import Button
        return Button(text="Open Modal", on_release=lambda x: modal_view.open())

if __name__ == '__main__':
    MyApp().run()
```

![](https://i.gyazo.com/28c08c28aec53774e5f22ac554b241a4.png)

**Comment by ElliotGarbus** [comment] 2023-12-29 18:42
This is not a bug.  The background Image of the ModalView is slightly smaller than the widget to provide the 3D effect.  Add padding to the ModalView.  I suggest you close this issue.

```python
from kivy.app import App
from kivy.uix.recycleview import RecycleView
from kivy.uix.recyclegridlayout import RecycleGridLayout
from kivy.uix.modalview import ModalView


class MyApp(App):
    def build(self):
        recycle_layout = RecycleGridLayout(cols=3)
        recycle_layout.size_hint_y = None
        recycle_layout.bind(minimum_height=recycle_layout.setter("height"))

        recycle_view = RecycleView()
        recycle_view.add_widget(recycle_layout)
        recycle_view.viewclass = 'Label'
        recycle_view.data = [{'text': str(x)} for x in range(123)]

        modal_view = ModalView(padding='10dp')
        modal_view.size_hint = (0.5, 0.5)
        modal_view.add_widget(recycle_view)

        from kivy.uix.button import Button
        return Button(text="Open Modal", on_release=lambda x: modal_view.open())


if __name__ == '__main__':
    MyApp().run()
```

**Closed** 2023-12-30 00:40 UTC
