### ISSUE TITLE
How To run Python script In background In android?

### ISSUE THREAD

**Issue by CodeWithVallabh** [kivy/kivy#7894] opened 2022-06-08 08:29 UTC
I want to run a specific Python file(for example, main.py) in android device using my android application made using Python, Kivy and Buildozer.

**Comment by misl6** [comment] 2022-06-08 11:24
Duplicate of https://github.com/kivy/python-for-android/issues/2618.

Please don't cross-post on multiple GitHub issues.

**Closed** 2022-06-08 11:24 UTC
Labels: support
