### ISSUE TITLE
Install kivy in venv failed: windows 10 + python 3.8.1

### ISSUE THREAD

**Issue by evanxlh** [kivy/kivy#7187] opened 2020-10-30 01:26 UTC
**Software Versions**
* Python: 3.8.1
* OS: windows 10
* Kivy: 1.11.1
* Kivy installation method: pip install kivy

I just enter my venv, and pip install kivy, and almost downloaded then failed. please see the below screenshots. Thanks very much.

![kivy-install-issue1](https://user-images.githubusercontent.com/28790093/97649220-bf7aac80-1a91-11eb-97a1-98e60e3e307d.png)
![kivy-install-issue2](https://user-images.githubusercontent.com/28790093/97649233-c6a1ba80-1a91-11eb-8655-f7d9865a37fb.png)

**Comment by matham** [comment] 2020-10-30 01:34
Duplicate of https://github.com/kivy/kivy/issues/6806.

**Closed by matham** 2020-10-30 01:34 UTC
