### ISSUE TITLE
Kivy Windows Py3.5 ImportError: cannot import name 'kivy_config_fn' 

### ISSUE THREAD

**Issue by NumesSanguis** [kivy/kivy#4829] opened 2016-12-19 11:52 UTC
I just tried with the latest nightly wheel to install Kivy for Python 3.5, but unfortunately I got this error:
`ImportError: cannot import name 'kivy_config_fn' `
https://gist.github.com/NumesSanguis/ddff440103cd0984d19725c24ac47e48

The nightly on the same day for py2.7 worked for me, but the nightly for py3.4 didn't even want to install:
`py -3.4 -m pip install Kivy-1.9.2.dev0-cp34-cp34m-win_amd64.whl`
Kivy-1.9.2.dev0-cp34-cp34m-win_amd64.whl is not a supported wheel on this platform.
Storing debug log for failure in C:\Users\*user*\pip\pip.log
https://gist.github.com/NumesSanguis/97d1a4d74d0bd2436e49455d047f7282

**edit2**: py3.4 error was because I forgot to install the dependencies for this version, now py3.4 gives the same error as py3.4 (.whl tested from 17 t/m 19-12-2016) from here:
https://drive.google.com/drive/folders/0B1_HB9J8mZepOV81UHpDbmg5SWM

Platform: Windows 7 64-bit

edit1: Installing dev dependencies form here didn't work (except sdl2_dev, because no py35 64-bit):
https://drive.google.com/drive/folders/0B1_HB9J8mZepdUl0bEZubXZiSUE

**Comment by Bloodyline** [comment] 2016-12-19 14:44
Got the same error, uninstall the newer deps and install those : https://pypi.python.org/pypi/kivy.deps.sdl2/0.1.12
https://pypi.python.org/pypi/kivy.deps.glew/0.1.4
And uninstall completly gstreamer it's the main reason it won't work, at least for me.

**Comment by snuq** [comment] 2016-12-19 17:52
I'm having the same issue, using python 2.7, python 3.4, kivy 1.9.1, 1.9.2 dev....
Got it working using those deps that Bloodyline posted (python 2.7 64bit, kivy 1.9.1, win8.1).
Unfortunately tho, I really need gstreamer for one of my projects, and installing it breaks the kivy import again...

**Comment by dessant** [comment] 2016-12-19 17:55
The previous gstreamer wheels can be fetched from here:
https://kivy.org/downloads/packages/simple/kivy-deps-gstreamer/

**Comment by snuq** [comment] 2016-12-19 18:02
dessant's gstreamer works! thanks!

**Comment by matham** [comment] 2016-12-19 18:28
The problem is with the pth files generated when built with pip. I'm not yet sure what changed in pip too cause this.

For comparison, here's the old file:

```
import sys, types, os;p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('kivy',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and sys.modules.setdefault('kivy', types.ModuleType('kivy'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('kivy', 'deps'));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and sys.modules.setdefault('kivy.deps', types.ModuleType('kivy.deps'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['kivy'], 'deps', m)

```

Here's the new one:

```
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('kivy',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('kivy', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('kivy', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('kivy', types.ModuleType('kivy'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('kivy',));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('kivy', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('kivy', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('kivy', types.ModuleType('kivy'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
import sys, types, os;has_mfs = sys.version_info > (3, 5);p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('kivy', 'deps'));importlib = has_mfs and __import__('importlib.util');has_mfs and __import__('importlib.machinery');m = has_mfs and sys.modules.setdefault('kivy.deps', importlib.util.module_from_spec(importlib.machinery.PathFinder.find_spec('kivy.deps', [os.path.dirname(p)])));m = m or not has_mfs and sys.modules.setdefault('kivy.deps', types.ModuleType('kivy.deps'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p);m and setattr(sys.modules['kivy'], 'deps', m)

```

**Comment by matham** [comment] 2016-12-20 08:07
I think this should be fixed now.

**Comment by KeyWeeUsr** [comment] 2016-12-20 11:54
Latest deps now work just fine. Problem is now only with SDL2 loading an image:

```
[INFO   ] [Logger      ] Record log in <root>\.kivy\logs\kivy_16-12-20_16.txt
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Kivy        ] v1.9.2-dev0.20122016.f640ddf
[INFO   ] [Python      ] v3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.2.0 - Build 10.18.10.3316'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 4400'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 2
[INFO   ] [GL          ] Shading version <b'4.20 - Build 10.18.10.3316'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[WARNING] [Image       ] Unable to load image <<root>\Desktop\testpy3x64\lib\site-packages\kivy\data\glsl\default.png>
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - Exception: SDL2: Unable to load image
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\__init__.py", line 67, in core_select_lib
    cls = cls()
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\window\window_sdl2.py", line 139, in __init__
    super(WindowSDL, self).__init__()
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\window\__init__.py", line 795, in __init__
    self.create_window()
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\window\window_sdl2.py", line 284, in create_window
    super(WindowSDL, self).create_window()
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\window\__init__.py", line 947, in create_window
    self.render_context = RenderContext()
  File "kivy\graphics\instructions.pyx", line 758, in kivy.graphics.instructions.RenderContext.__init__ (kivy\graphics\instructions.c:12580)
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\image\__init__.py", line 538, in __init__
    self.filename = arg
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\image\__init__.py", line 734, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\image\__init__.py", line 435, in load
    im = loader(filename, **kwargs)
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\image\__init__.py", line 201, in __init__
    self._data = self.load(filename)
  File "<root>\Desktop\testpy3x64\lib\site-packages\kivy\core\image\img_sdl2.py", line 41, in load
    raise Exception('SDL2: Unable to load image')

[CRITICAL] [App         ] Unable to get a Window, abort.
```

sdl2+angle+glew bins are on `PATH`

**Comment by matham** [comment] 2016-12-21 00:31
I just tested on a clean system and it worked for me. I wonder if your path
is messed up. Also you should check that visual studio redistributable for
2015 is installed.

**Comment by matham** [comment] 2016-12-21 16:56
I checked again on a win 7 system and it also works with 64 bit Python 3.5.
Does anyone else have this issue?

**Comment by KeyWeeUsr** [comment] 2016-12-21 17:12
Same result even after multiple reinstalls of python. I used the latest deps from drive + the latest (`Kivy-1.9.2_dev0.21122016.f640ddf-cp35-cp35m-win_amd64`) wheel. Win8.1 64bit.

**Comment by matham** [comment] 2016-12-21 18:01
Try using the wheel without the extended version. Also, can you use
dependency walker (http://www.dependencywalker.com/) to figure out which
dlls are missing? You'll have to to add to the path the glew/sdl2/gstreamer
dlls manually before running it though.

**Comment by snuq** [comment] 2016-12-21 19:20
The import error is fixed for me now, but im getting the same error as KeyWeeUsr now, using python 2.7 and the latest nightly wheel.
Im also on win 8.1 64bit, interestingly enough, and the visual studio redistributables are installed.
I got dependancy walker, but im not entirely sure what to do with it, I opened python.exe and it says its missing 6 dlls:
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
IESHIMS.DLL

and sdl2.dll isnt even listed tho

**Comment by KeyWeeUsr** [comment] 2016-12-21 20:23
`zlib.dll` in `C:\Program Files\Intel\WiFi\bin\` colliding, ou yeah.

**Comment by matham** [comment] 2016-12-22 02:45
I think the zlib issues for the dependencies should now be fixed on pypi. Kivy wheel still needs to be rebuilt, but it should fix it even for older kivy wheels.

**Comment by KeyWeeUsr** [comment] 2016-12-22 19:19
@matham I'm closing it, because the original issue was resolved and if something similar happens again, we know it was about colliding dlls.

**Closed by KeyWeeUsr** 2016-12-22 19:19 UTC
