### ISSUE TITLE
windows kivy issue

### ISSUE THREAD

**Issue by princedoodle** [kivy/kivy#6327] opened 2019-05-22 14:45 UTC
### Versions

* Python:
* OS:
* Kivy:
* Kivy installation method:

### Description

'First Name' Text isn't showing up, but works for other people when they run it.

### Code and Logs

```python
https://stackoverflow.com/questions/56259248/how-do-i-restart-kivy
https://stackoverflow.com/questions/56248912/widget-text-isnt-showing-up-in-one-of-the-column
```

**Comment by matham** [comment] 2019-05-22 19:20
Duplicate of https://github.com/kivy/kivy/issues/6318. See the last comment there.

**Closed by matham** 2019-05-22 19:20 UTC
