### ISSUE TITLE
AttributeError in kivy.graphics.context.Context.*

### ISSUE THREAD

**Issue by casperlehmann** [kivy/kivy#3226] opened 2015-04-03 16:06 UTC
No idea whether this is even worth reporting, but better safe than sorry.
I've never seen these errors before, and I have not been able to reproduce them.
What happened is I hit a button to change screens, and a number of functions are fired to prepare the state of the application for the shift.
- Just now, I wanted to time one of these functions, so I entered a couple of print(time()) into it, and run it.
- I then end up with the AttributeErrors below.
- After seeing the error message, I returned to the menu and entered the screen again (which is the reason there are timestamps after the errors.
- Then I manually quit.

```
[INFO              ] [Logger      ] Record log in /Users/Lasper/.kivy/logs/kivy_15-04-03_66.txt
[INFO              ] Kivy v1.9.0-dev
[INFO              ] [Python      ] v2.7.8 (default, Oct 15 2014, 22:04:42) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)]
[INFO              ] [Factory     ] 172 symbols loaded
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [Image       ] Providers: img_imageio, img_tex, img_dds, img_pygame, img_gif (img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO              ] [GL          ] OpenGL version <2.1 INTEL-8.28.30>
[INFO              ] [GL          ] OpenGL vendor <Intel Inc.>
[INFO              ] [GL          ] OpenGL renderer <Intel HD Graphics 5000 OpenGL Engine>
[INFO              ] [GL          ] OpenGL parsed version: 2, 1
[INFO              ] [GL          ] Shading version <1.20>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: pygame
[INFO              ] [GL          ] NPOT texture support is available
1428076422.78
1428076422.8
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Base        ] Start application main loop
[INFO              ] [Context     ] Reloading graphics data...
[INFO              ] [Context     ] Reloading done in 0.1911s
1428076431.27
1428076431.27
1428076431.3
1428076431.31
 Exception AttributeError: "'array.array' object has no attribute 'append'" in 'kivy.graphics.context.Context.dealloc_vertexbatch' ignored
 Exception AttributeError: "'array.array' object has no attribute 'append'" in 'kivy.graphics.context.Context.dealloc_vbo' ignored
 Exception AttributeError: "'array.array' object has no attribute 'append'" in 'kivy.graphics.context.Context.dealloc_texture' ignored
 Exception AttributeError: "'array.array' object has no attribute 'append'" in 'kivy.graphics.context.Context.dealloc_vertexbatch' ignored
 Exception AttributeError: "'array.array' object has no attribute 'append'" in 'kivy.graphics.context.Context.dealloc_vbo' ignored
1428076457.55
1428076457.55
[INFO              ] [Base        ] Leaving application in progress...
```
##

**Comment by matham** [comment] 2016-01-29 05:58
I cannot seem to reproduce it, other the one time I hit this issue. I don't even understand how this is possible to occur as array clearly has an append method which I verified in cython.

**Comment by tshirtman** [comment] 2016-03-28 21:57
Such impossible error can happen when a section of C code doesn't do proper exception checking, and python discover error aften

**Comment by Julian-O** [comment] 2023-11-13 23:40
Given the risk of misattribution, the lack of test code and the elapse of 7 years, there isn't enough information here to debug the cause. Closing as can't repro, but if anyone can, please let us know all the details.

**Closed by Julian-O** 2023-11-13 23:40 UTC
Labels: Component: graphics, Status: Needs-analysis, Status: Confirmed
