### ISSUE TITLE
Incorrect behavior keyboard_suggestions

### ISSUE THREAD

**Issue by idevo89** [kivy/kivy#7337] opened 2021-01-19 23:27 UTC
**Software Versions**
* Python: 3.8
* OS: Android 9
* Kivy: master
* Kivy installation method: python-for-android develop with kivy==master

**Describe the bug**
Keyboard suggestions for TextInput do not work correctly on android. Words are inputted twice when you use a suggestion or swipe as you can notice when you delete the words or press enter. Setting keyboard_suggestions to false does not deactivate suggestions.

**Expected behavior**
Keyboard suggestions or swiping should input words correctly and it should be possible to deactivate the suggestions feature with keyboard_suggestions set to false.

**To Reproduce**
```python
from kivy.app import App
from kivy.lang import Builder


kv = """
Screen:
    TextInput:
        size_hint_y: None
        height: dp(45)
        hint_text: "keyboard_suggestions: False"
        write_tab: False
        keyboard_suggestions: False
        pos_hint: {"top": 0.9}
    TextInput:
        size_hint_y: None
        height: dp(45)
        hint_text: "keyboard_suggestions: True"
        write_tab: False
        keyboard_suggestions: True
        pos_hint: {"top": 0.7}
"""


class Test(App):
    def build(self):
        return Builder.load_string(kv)


Test().run()

```

**Gif**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48392636/105105400-51ec8400-5ab4-11eb-80cf-7c3ab896c822.gif)

**Comment by matham** [comment] 2021-01-19 23:57
I'm wondering if it's due to https://github.com/kivy/kivy/pull/7231. Can you try a commit before that? Or maybe 2.0.0?

@dwmoffatt could you take a look?

**Comment by dwmoffatt** [comment] 2021-01-20 01:23
I'll take a look

**Comment by misl6** [comment] 2021-02-11 12:29
GBoard:

- Issue confirmed when using swipe or suggestions.

Samsung Keyboard:

- The first inputted character, keeps into TextInput.

Reverting #7231 fixed the issue.

It could potentially disrupt the UX for multiple users. @dwmoffatt any news?

**Comment by dwmoffatt** [comment] 2021-02-11 16:41
I think I know what the problem is. There are some other variations/flags that need to get set for some of the autocomplete and suggestions to work properly based on how you are entering the data. 

https://developer.android.com/reference/android/text/InputType

I haven't had a chance to try anything out yet. Hopefully next week I will have some time.

**Comment by misl6** [comment] 2021-09-12 16:01
Update:
Looks like some device vendors and keyboards are de-facto ignoring the `InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS` flag, so we can't really rely on this one to disable suggestions.

**Comment by Alspb** [comment] 2022-01-06 01:00
I'd also add that for Gboard and other keyboards its built-in "Copy" and "Paste" buttons don't work: "Copy" is disabled even if text is selected, "Paste" just does nothing.
Probably "Copy" just can't detect that something is selected, but seems that "Paste" should work fine.

**Comment by karmabIT** [comment] 2022-04-21 10:35
Hi,
   I would like to help you in solving the poblem, since I need it to find a solution quickly.
   May you tell me which files (and/or part of codes) I have to check and modify (including the event on keyboard) to try to find a solution?
   
   Thank you

**Comment by NomadDemon** [comment] 2022-04-22 08:23
i have same problem
kivy 2.1.0
on Android [2 differend phones, 4y difference + gboard] if i go to next word it keep repeating last suggested on spacebar

iam too short to help with keyboard or even files where to look :(

i owe you beer if you fix it somehow :)

**Comment by brvier** [comment] 2022-10-08 09:28
Kivy master
Python-for-android develop

No suggestion or swipe.

**Comment by misl6** [comment] 2022-11-28 19:03
Fixed via https://github.com/kivy/python-for-android/pull/2692

**Closed by misl6** 2022-11-28 19:03 UTC
Labels: Priority: High
