### ISSUE TITLE
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\arp.wav: Protocol not found

### ISSUE THREAD

**Issue by estikf** [kivy/kivy#6964] opened 2020-06-24 17:32 UTC
**Software Versions**
* Python: 3.6.7
* OS: Windows 8.1
* Kivy: 1.11.0
* Kivy installation method: pip

**Describe the bug**

I cannot play my arp.wav file with ffpyplayer. I have installed ffpyplayer with pip (pip install ffpyplayer) but I couldn't compiled it (https://matham.github.io/ffpyplayer/installation.html) and I guess thats why it gives an error. I need a simple instruction of installing ffpyplayer because I am new to Kivy :(.

By the way I have tried SDL2 but it does not have get_pos() and seek() methods available (I need them). Gstplayer starts songs with noticable delay so I have to use ffpyplayer guys... 

**Expected behavior**

I expect to play my audio file when I click the button with ffpyplayer.

**Code and Logs and screenshots**
```python
// import os
os.environ['KIVY_AUDIO'] = 'ffpyplayer'

from kivymd.app import MDApp
from kivymd.uix.screen import Screen
from kivy.uix.togglebutton import ToggleButton
from kivymd.uix.gridlayout import MDGridLayout
from kivy.core.audio import Sound,SoundLoader
from kivy.clock import Clock
from kivy.lang import Builder

kv = """
<MyScreen>:
    MDGridLayout:
        cols:2
        id: mdgridlayout
        ToggleButton
            id:button_arp
            text:"arp"
            on_state:root.play_or_stop(self.state,root.arp)
"""

class MyScreen(Screen):
    
    def __init__(self, **kw):
        super().__init__(**kw)
        
        self.arp = SoundLoader.load("data\\arp.wav")
        self.a = 0

    def play_or_stop(self,state,song):
        if state == "down":
            song.play()
            song.seek(self.a)
            song.loop = True
        else:
            song.stop()

    def show_song_pos(self,*args):

        self.a = self.arp.get_pos()
        self.ids.button_arp.text = "Arp" + str(self.a)

class DemoApp(MDApp):
    def build(self):
        root = MyScreen()
        Clock.schedule_interval(root.show_song_pos,0.1)
        return root

if __name__ == "__main__":
    Builder.load_string(kv)
    DemoApp().run()
```

**Comment by sanderland** [comment] 2020-06-26 20:53
Also encountered this issue on windows and reverted back to SDL2

**Comment by matham** [comment] 2020-06-28 15:37
There's no log so there's no way to debug.

**Comment by estikf** [comment] 2020-06-28 16:20
@matham Sorry I have forgot the logs. Here they are.
```

[INFO   ] [deps        ] Successfully imported "kivy_deps.gstreamer" 0.1.18
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.1.12
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.1.23
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "c:\Users\Furkan\Desktop\music_project\kivy_venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "c:\Users\Furkan\Desktop\music_project\kivy_venv\Scripts\python.exe"
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.1
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <b'4.4.0 - Build 20.19.15.4835'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) HD Graphics 5500'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 4
[INFO   ] [GL          ] Shading version <b'4.40 - Build 20.19.15.4835'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [SoundFFPy   ] Using ffpyplayer 4.3.1
[INFO   ] [Audio       ] Providers: audio_ffpyplayer (audio_gstplayer, audio_sdl2 ignored)
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\arp.wav: Protocol not found
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\bass.wav: Protocol not found
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\clap.wav: Protocol not found
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\hihat.wav: Protocol not found
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\kick.wav: Protocol not found
[ERROR  ] [ffpyplayer  ] C:\Users\Furkan\Desktop\music_project\data\lead.wav: Protocol not found
[INFO   ] [Base        ] Start application main loop

```

**Comment by sanderland** [comment] 2020-07-03 08:29
Example non-working file (windows, .wav)
[countdownbeep.zip](https://github.com/kivy/kivy/files/4868629/countdownbeep.zip)

**Comment by matham** [comment] 2020-07-03 19:37
Hmm I'm unable to reproduce using the latest ffpyplayer on py3.7 x64.

I suspect this is an issue with your environment (dll hell) where somehow it's pulling another ffmpeg dll from a different package. 

Could you try the following in a empty script without importing anything else:

```
from ffpyplayer.player import MediaPlayer
ff_opts = {'vn': True, 'sn': True}
ffplayer = MediaPlayer(filename)
```

and see if it plays the audio? If it doesn't, look in the folder `join(sys.prefix, 'share', 'ffpyplayer', 'ffmpeg', 'bin')`, you'll find `ffplay.exe`. try playing the file using `ffplay filename` and see if it has an issue.

**Comment by sanderland** [comment] 2020-07-03 21:29
That works, except for some weird looping at the end.

This reproduces the protocol not found:

```python
import os
os.environ["KIVY_AUDIO"] = "ffpyplayer"
import time
from kivy.core.audio import SoundLoader

beep = SoundLoader.load("sounds/countdownbeep.wav")
beep.play()
time.sleep(10)

```

**Comment by matham** [comment] 2020-07-03 22:32
That works for me, still.

I installed master (`python -m pip install kivy[base] --pre --extra-index-url  https://kivy.org/downloads/simple/`) and ffpyplayer (`pip install ffpyplayer`) in a clean virtualenv and ran the code and it worked fine.

**Comment by sanderland** [comment] 2020-07-03 23:14
interestingly creating a new conda env on windows (which now defaults to 3.7.7) and installing those results in working audio. 

* Also when using 2.0.0rc2.
* Upgrading kivy deps on the original env did not help.
* Installing every package from the original env  (from list explicit/install --file) in the new env did not break it.
* Creating a new environment with py3.7.3 like the original and installing packages (from list explicit/install --file) and then kivy+ffpyplayer -> back to non working audio.
* Creating a new environment with py3.7.3 and just installing kivy --pre and ffpyplayer from pypi -> working audio.
* Started a binary search of the package list, but both the top half and the bottom half result in working audio.

I'm very puzzled!

**Comment by matham** [comment] 2020-07-03 23:28
You entered [dll hell!!](https://en.wikipedia.org/wiki/DLL_Hell). This used to be very common for kivy gstreamer until we switched to using msvc gstreamer builds and started pushing users to only install into a clean virtualenv.

**Comment by BaggioMarco** [comment] 2020-12-17 15:39
I had the same problem. News on how to fixed? [ERROR ] [ffpyplayer ]video.mp4: Protocol not found

**Comment by estikf** [comment] 2020-12-17 15:50
> I had the same problem. News on how to fixed? [ERROR ] [ffpyplayer ]video.mp4: Protocol not found

I have stop continuing to my project, because python's execution speed did not satisfy for my case. So the answer is unfortunately no :( .

**Comment by matham** [comment] 2020-12-17 16:29
I'm going to close this because there's nothing for us to do here. Either something is wrong with the environment and you need to test it from a clean virtual environment, or the ffpyplayer binaries used just don't support the type of media in this file. In which case I'd convert the file to a different format. Either way we can't do anything about this.

**Closed by matham** 2020-12-17 16:29 UTC

**Comment by BaggioMarco** [comment] 2020-12-17 16:35
my objective was simply to drag the control bar of the VideoPlayer and see  changes in the video, with no stop of 5 seconds. Is it possible to do that in whatever way in kivy? thank you

**Comment by BaggioMarco** [comment] 2020-12-17 18:35
I answer to your message here because I've seen you marked the other post as duplicate. Your question was:
"Do you have a colon in the filename? What is the exact full filename of the video?". My answer is simply "video" with mp4 extension, thank you

**Comment by matham** [comment] 2020-12-17 18:43
Unfortunately, as I explained, there's nothing we can do about this as it's not a Kivy problem but with the underlying video decoder. And it's either because your environment has conflicts and you need to try this in a clean virtual environment, or the player doesn't support whatever data is in your file so you may want to try converting the video file to a different format. Otherwise, there isn't anything for us to do.

**Comment by BaggioMarco** [comment] 2020-12-17 18:48
thank you very much @matham . Regarding my objective of simply to drag the control bar of the VideoPlayer and see changes in the video, with no stop of 5 seconds... Do you think is it possible to do that in whatever way in kivy? PS: If you think that would be better post this as a new topic please let me know, I don't want mess this thread, please let me know which is the best way for me to receive support for this question, I can also delete my comments in this page if you find it more reasonable, please let me know your thoughts about that, thank you in advance

**Comment by matham** [comment] 2020-12-17 19:09
About seeking to a more precise frame, that issue is already open [here](https://github.com/kivy/kivy/issues/4648), but no one has worked on it so it hasn't been resolved. The cause of that is explained [there](https://github.com/kivy/kivy/issues/4648#issuecomment-250774189).

About the other stuff, for support, we use [discord](https://chat.kivy.org/).

**Comment by BaggioMarco** [comment] 2020-12-17 20:45
thank you @matham

**Comment by radiolondra** [comment] 2021-03-04 19:25
About the ffpyplayer error "Protocol not found", try to remove kivy_deps.gstreamer dependancy (if you use PyCharm for your project this is very simple) or reinstall kivy[base] only. And it shoul work.
