### ISSUE TITLE
Cross-thread kivy ExceptionHandler

### ISSUE THREAD

**Issue by wolfikk2** [kivy/kivy#4988] opened 2017-02-10 15:14 UTC
### Versions

* Python: 3.5.2
* OS: Raspberry Pi 2 / Archlinux 4.4.47-1-ARCH #1 SMP armv7l
* Kivy:  v1.9.1
* Kivy installation method: pip

### Description

Assume that I have kivy ExceptionHandler registered. When I throw an exception that is unhandled in my code, the kivy ExceptionHandler does not catch the exception and worker thread exits. The exactly same program runs on PC without problems. I have noticed that on PC is running only the threads created by my code (two, including main thread) and on Raspberry Pi are active 4 threads.

### Code and Log
This is log of raised debug exception generated by key shortcut.

```
[WARNING           ] stderr: Exception in thread Thread-3:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python3.5/threading.py", line 862, in run
[WARNING           ] stderr:     self._target(*self._args, **self._kwargs)
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/input/providers/hidinput.py", line 701, in _thread_run
[WARNING           ] stderr:     process_as_mouse_or_keyboard(*infos)
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/input/providers/hidinput.py", line 553, in process_as_mouse_or_keyboard
[WARNING           ] stderr:     Window._modifiers)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-5w6qva0z/kivy/kivy/_event.c:7725)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-5w6qva0z/kivy/kivy/_event.c:13484)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (/tmp/pip-build-5w6qva0z/kivy/kivy/_event.c:13013              )
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/core/window/__init__.py", line 159, in _on_window_key_down
[WARNING           ] stderr:     return self.dispatch('on_key_down', keycode, text, modifiers)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-5w6qva0z/kivy/kivy/_event.c:7725)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-5w6qva0z/kivy/kivy/_event.c:13484)
[WARNING           ] stderr:   File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (/tmp/pip-build-5w6qva0z/kivy/kivy/_event.c:13013              )
[WARNING           ] stderr:   File "/opt/yolk/YolkScreens/IdleScreen.py", line 121, in _on_key_down
[WARNING           ] stderr:     raise Exception("Debug chyba pre zobrazenie dialogu.")
[WARNING           ] stderr: Exception: Debug chyba pre zobrazenie dialogu.
[WARNING           ] stderr:

```

and this is same condition on PC, ExceptionHandler catches the exception and print info out to log:

```
[ERROR             ] [Exception   ] Debug chyba pre zobrazenie dialogu.
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
    EventLoop.idle()
  File "C:\Python34\lib\site-packages\kivy\base.py", line 327, in idle
    Clock.tick()
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 515, in tick
    self._process_events()
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 406, in tick
    ret = callback(self._dt)
  File "C:\Python34\lib\site-packages\kivy\clock.py", line 701, in callback_func
    func(*args, **kwargs)
  File "D:\Sources\Repos\YellowMachineSystem\YolkScreens\IdleScreen.py", line 124, in _on_key_down
    raise Exception("Debug chyba pre zobrazenie dialogu.")
Exception: Debug chyba pre zobrazenie dialogu.
```

**Comment by FeralBytes** [comment] 2017-02-12 03:03
Example code please; I don't have enough context to grasp what you are trying to achieve let alone as to why? Thank you.
What is the OS of the PC?
What version of kivy & python is running on the PC and what is the version of kivy & python on the Raspberry PI?
What is the Kernel version for the Raspberry PI?

**Comment by wolfikk2** [comment] 2017-02-16 13:18
On PC I have Windows 10 / Python v3.4.2 / kivy v1.9.1

here is throwed exception, it's direct keyboard input
``` 
class YolkIdleScreen(Screen):
    def _on_key_down(self, keyboard, keycode, text, modifiers):
        if keycode[1] == 'f5':
            self.manager.current = "AdminScreenMulti"
        if keycode[1] == 'f6':
            with YolkDataModel():
                import_source = YolkDataModel.YSetting.read("import_source", join(getcwd(), './YolkUpdate'))
            YolkDataModel("import").register(import_source)
            self.manager.current = "ImportProductScreen"
        if keycode[1] == 'f7':
            self.manager.current = "AdminScreenVouchers"
        if keycode[1] == 'f10':
            raise Exception("Debug chyba pre zobrazenie dialogu.")
        if keycode[1] == 'f11':
            os.popen("reboot")
        if keycode[1] == 'f12':
            os.popen("shutdown -P now")
        if self.manager.current == "SellScreen" and keycode[1] == 'f8': # debug payment
            self.manager.current_screen.on_product_payed()
        if self.manager.current == "SellScreen" and keycode[1] == 'f9': # debug
            App.get_running_app().dispatch("on_vending_done", 0x12, 100)
            pass
```

here is _build_ of App class, _YolkIdleScreen_ is the first screen opened after application start

```
class Yolk(App):
    __sm = None
    def build(self):
        app_layout = FloatLayout()
        status_ovelay = YStatusOverlay()

        self.__sm.add_widget(YolkIdleScreen())

        self.__sm.add_widget(YolkSellScreen())
        self.__sm.add_widget(YolkProductDetailScreen())
        self.__sm.add_widget(YolkProductsScreen())

        self.__sm.add_widget(YolkCategoryScreen())

        self.__sm.add_widget(YolkFaqScreen())
        self.__sm.add_widget(YolkContactInfoScreen())
        self.__sm.add_widget(YolkHowToBuyScreen())
        self.__sm.add_widget(YolkReclaimScreen())
        self.__sm.add_widget(YolkTermsOfUseScreen())

        # Administration screens
        self.__sm.add_widget(YolkImportProductScreen())
        self.__sm.add_widget(YolkAdminScreenMulti())
        self.__sm.add_widget(YolkAdminScreenVouchers())

        # Start happyhour refresh timer after creating all screens
        # so the screens catch first start event if it happens.
        self.happyhour.start()

        self.__sm.bind(on_touch_down=self.on_touch_down, on_touch_move=self.on_touch_move, on_touch_up=self.on_touch_up)

        app_layout.add_widget(self.__sm)
        app_layout.add_widget(status_ovelay)
        return app_layout
```

... the _init_ of App class, notice that there registered the _YolkExceptionHandler_ with _ExceptionManager_

```
    def __init__(self):
        self.register_event_type("on_emitting_product_change")
        self.register_event_type("on_vending_start")
        self.register_event_type("on_vending_done")
        self.register_event_type("on_vending_error")
        self.register_event_type("on_product_sold")
        super(Yolk, self).__init__()
        resource_add_path("res/")
        resource_add_path("res-default/")

        transition = NoTransition()
        YolkDataModel().register(join(getcwd(), './res'))
        self.__sm = ScreenManager(transition=transition)
        ExceptionManager.add_handler(YolkExceptionHandler())

        self.happyhour = YolkHappyHour()

        self.__gdb = GestureDatabase()
        self.__gdb.add_gesture(YolkGestures.import_page_gesture)

        YolkSystemController().init("/dev/P150218")

```

and here is the _YolkExceptionHandler_

```
class YolkExceptionHandler(ExceptionHandler):

    def __init__(self):
        super(YolkExceptionHandler, self).__init__()

    def handle_exception(self, inst):
        args = list(inst.args)
        trace = traceback.format_exc()
        message = args[0]
        Logger.error("Exception: " + message + "\n" + trace)
        YolkExceptionHandler.showError(message, trace)
        return ExceptionManager.PASS

    @staticmethod
    def showError(message, trace):
        sm = App.get_running_app().get_sm()
        sm.get_root_window().add_widget(YErrorOverlay(sm, YError("Toto sa nemalo stať", message, trace)), -1)
```

**Comment by matham** [comment] 2017-02-16 18:27
Are you using kivy from multiple threads? Because that is not supported.

**Comment by FeralBytes** [comment] 2017-02-18 17:47
@wolfikk2 if you were using Kivy from multiple threads, please close this bug.

**Comment by citruslee** [comment] 2017-02-20 10:27
Actually, we do not use kivy from multiple threads. And also this behaviour happens if there are no threads use whatsoever (completely single thread program execution)

**Comment by dessant** [comment] 2017-02-20 10:43
Please reopen with a short, runnable example which reproduces the bug. The new issue template will contain some suggestions, and a link with an app template that you can edit.

**Closed by dessant** 2017-02-20 10:43 UTC
Labels: awaiting-reply
