### ISSUE TITLE
Setting max FPS has no effect

### ISSUE THREAD

**Issue by HaMM4R** [kivy/kivy#6781] opened 2020-03-15 12:51 UTC
**Software Versions**
* Python: 3.4
* OS: Ubuntu 16.04
* Kivy: Latest
* Kivy installation method: pip

Setting max FPS in the config has no effect on the framerate. The code for doing this is below. 
from kivy.config import Config
Config.set('graphics', 'maxfps', '30')

No matter where in the kivy file (even before all the imports as suggested) the framerate is never locked to 30 which is causing performance issues on mobile. I've seen others have this error and there seems to be no fix available.

**Comment by Lauszus** [comment] 2020-03-26 08:05
I believe you need to set it as an integer and not a string:

```python
Config.set('graphics', 'maxfps', 30)
```

That works for me at least.

**Comment by Lauszus** [comment] 2020-03-26 08:09
I can not reproduce this. However the FPS is not exactly the specified value. For instance when I set the maxfps to 30, then the FPS reported by `Config.set('modules', 'monitor', '')` is ~40 FPS.

**Comment by TheRedLady** [comment] 2020-03-26 15:20
**Software Versions**

Python: 3.7
OS: Windows 10
Kivy: Latest (==1.11.1)
Kivy installation method: pip

Setting the 'maxfps' setting with Config has no result. The application under development requires fast update rate and the events scheduled with Kivy's clock are executed with a 10ms delay each time, which is unacceptable in terms of our requirements. Experimenting with the 'kivy_clock' **and** 'maxfps' settings makes absolutely no change.

**Comment by matham** [comment] 2020-03-26 17:00
There could be multiple reasons. 

First, the GPU may be blocking the kivy thread if the GPU locks you to its frame rate. I have seen this on some computers. You may be able to disable it by setting vsync (but i never managed to get it working - https://github.com/kivy/kivy/pull/4854). You can tell if this is the case by running a app that updates a simple label with a new value on each clock frame and measure the clock rate. The control experiment is to do the same, but don't update the label, thereby the GPU won't be engaged. This will tell you the GPU vs. CPU clock speeds and whether they are different.

The other could be simply that your app is too heavy or that you need to try different clocks. BTW, to try different clock classes, you should set the environment variable `KIVY_CLOCK` - https://kivy.org/doc/master/api-kivy.clock.html#summary.

**Comment by pietervandermeer** [comment] 2020-04-08 14:54
* Python: 3.7
* OS: Ubuntu Raspbian Buster
* Kivy: 2.0.0rc1
* Kivy installation method: pip
* Computer: Raspberry Pi 4B
* Custom built SDL KMSDRM, running on console

Same issue here. Clock.get_fps() reports 82 fps, but maxfps set to 60 in configuration. There's also tearing artifacts on the display. It looks slower than 60 too.. Hmm.

**Comment by pjimenezmateo** [comment] 2020-05-01 13:33
* Python: 3.7.4
* OS: Ubuntu 18.04
* Kivy Version: 1.11.1
* Kivy installation method: pip

Same issue here, do we have any idea on how to fix this or any workaround?

**Comment by tshirtman** [comment] 2020-05-06 19:39
```python
from kivy.config import Config

Config.set('graphics', 'maxfps', 1)

from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.clock import Clock
from kivy import properties as P


KV = '''
#:import Clock kivy.clock.Clock

BoxLayout:
    orientation: 'vertical'
    Label:
        text: str(app.counter)
    Label:
        text: str(app.age)
    Label:
        text: str((app.counter / max(app.age, 1), Clock.get_fps()))
'''

class Application(App):
    counter = P.NumericProperty()
    age = P.NumericProperty()

    def build(self):
        Clock.schedule_interval(self.update_counter, 0)
        return Builder.load_string(KV)

    def update_counter(self, dt):
        self.counter += 1
        self.age += dt


if __name__ == "__main__":
    Application().run()
```

running this **without the monitor module**, gives me the expected result.

![image](https://user-images.githubusercontent.com/22759/81220496-abbe2400-8fe1-11ea-9938-a0c80779e2e9.png)

it does overshoot, but the maxfps setting has an very significant effect.

system: ubuntu 18.04
python: 3.7.5
kivy: 1.11.1 (from wheels)
```
[INFO   ] [Logger      ] Record log in /home/gabriel/.kivy/logs/kivy_20-05-06_23.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/gabriel/.virtualenvs/kivywheels/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.5 (default, Nov  7 2019, 10:50:52) 
```

**Comment by pietervandermeer** [comment] 2020-05-06 20:27
@tshirtman Looks like a good diagnostic tool, and perfect for comparing oranges with oranges, thanks!

**Comment by matham** [comment] 2020-05-13 21:19
I'll close this issue, because kivy's `max_fps` is not expected to precisely set the fps and some over/undershoot is expected. If you need an exact fps, you should let kivy's fps be unlimited and implement your own more precise clock on top of kivy (that's what kivent did).

**Closed by matham** 2020-05-13 21:19 UTC
