### ISSUE TITLE
OpenGL detect the version as 1.1

### ISSUE THREAD

**Issue by sakku116** [kivy/kivy#7834] opened 2022-03-06 04:29 UTC
**Software Versions**
* Python: 3.9
* OS: windows 10
* Kivy: 2.0.0
* Kivy installation method: pip

i dont know how to create an issue properly, but i hope there is someone who knows exactly my problem. also im sorry if my english is bad. 

so, when i run my app, in the command line show me that my opengl version is 1.1, **but yesterday** thats all are fine, and it show me that my opengl version is above 2. i ran the code in same machine but in the different days.

**Expected behavior**
i expected my code will run properly as before, before this error exist.

**Logs**
so, this is the log on 4 march:
```
[INFO   ] Logger: Record log in C:\Users\Thosiba\.kivy\logs\kivy_22-03-04_14.txt
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "C:\py_venv\kivy_venv\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "C:\py_venv\kivy_venv\Scripts\python.exe"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'4.0.0 - Build 10.18.10.4425'>
[INFO   ] GL: OpenGL vendor <b'Intel'>
[INFO   ] GL: OpenGL renderer <b'Intel(R) HD Graphics'>
[INFO   ] GL: OpenGL parsed version: 4, 0
[INFO   ] GL: Shading version <b'4.00 - Build 10.18.10.4425'>
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[WARNING] Both Window.minimum_width and Window.minimum_height must be bigger than 0 for the size restriction to take effect.
[INFO   ] GL: NPOT texture support is available
[INFO   ] Base: Start application main loop
[INFO   ] Base: Leaving application in progress...
```

and this is kivy log on 5 march:

```
[INFO   ] Logger: Record log in C:\Users\Thosiba\.kivy\logs\kivy_22-03-05_0.txt
[INFO   ] deps: Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] deps: Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] Kivy: v2.0.0
[INFO   ] Kivy: Installed at "C:\py_venv\kivy_venv\lib\site-packages\kivy\__init__.py"
[INFO   ] Python: v3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
[INFO   ] Python: Interpreter at "C:\py_venv\kivy_venv\Scripts\python.exe"
[INFO   ] Factory: 186 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL" graphics system
[INFO   ] GL: GLEW initialization succeeded
[INFO   ] GL: No framebuffers extension is supported
[INFO   ] GL: Backend used <glew>
[INFO   ] GL: OpenGL version <b'1.1.0'>
[INFO   ] GL: OpenGL vendor <b'Microsoft Corporation'>
[INFO   ] GL: OpenGL renderer <b'GDI Generic'>
[INFO   ] GL: OpenGL parsed version: 1, 1
[CRITICAL] GL: Minimum required OpenGL version (2.0) NOT found!

OpenGL version detected: 1.1

Version: b'1.1.0'
Vendor: b'Microsoft Corporation'
Renderer: b'GDI Generic'

Try upgrading your graphics drivers and/or your graphics hardware in case of problems.

The application will leave now.
```

**Additional context**
i tried to change the `multisample` to 0, and yeah its work. **but**, when i do that, the log showing that opengl version is above 2.0. but when i change it back to 2, i got opengl version is 1.1.

**Comment by misl6** [comment] 2022-03-09 18:07
Looks like the driver is changing between the generic one and the Intel specific.
The issue still persists with Kivy 2.1.0?

**Comment by sakku116** [comment] 2022-03-10 04:08
> Looks like the driver is changing between the generic one and the Intel specific. Does the issue still persist with Kivy 2.1.0?

i didnot change the driver. i got 2 item of driver list shown up when i check driver update in device manager. that are "intel(r) HD graphic" and "microsoft basic display adapter", even i change the driver it still doesnot work.

by the way, how do i get 2.1.0 version of kivy? please tell me

**Comment by sakku116** [comment] 2022-03-10 04:58
also, since that error exist. when i set `multisamples` to 2, my terminal shows that my OpenGL vendor is "microsoft corporation". **but**, if i set the `multisamples` to 0, which is how my code works, my terminal shows that my OpenGL vendor is "intel hd graphic"

**Comment by misl6** [comment] 2022-03-13 09:43
If you `pip` installed Kivy, 
Looks like a duplicate of https://github.com/kivy/kivy/issues/3576
Can you post your PC configuration

**Comment by misl6** [comment] 2022-03-13 09:45
If you `pip` installed Kivy, `pip install --upgrade kivy` updates it to `2.1.0`

BTW, looks like a duplicate of https://github.com/kivy/kivy/issues/3576

Can you post your PC configuration over there so we can close this issue and keep only one?

**Comment by sakku116** [comment] 2022-03-13 10:57
by the way, I just found the solution recently. I think turning off anti aliasing could cause this error to appear. and i tried to turn the aliasing on, and yah it works.
![image_2022-03-13_175543](https://user-images.githubusercontent.com/88846365/158056248-1094dcf8-e306-4214-bc42-9ba766f796ab.png)

**Closed** 2022-04-06 19:22 UTC

**Comment by ChristTech** [comment] 2023-03-02 01:46
I went to my file manager and located my present working directory, opened up the venv folder and then opened up the share folder. I pasted the file I downloaded from the link below (extract first to get the opengl32.dll) into all the bin folder (for angle, gstreamer e.t.c). it also works when you try to package your application with pyinstaller

https://www.dll-files.com/download/b8db21516b088afd9b0242741f435c71/opengl32.dll.html?c=VHRPVEJkcGJ2ZGx4V0JOdlZoYlhSZz09

![opendll](https://user-images.githubusercontent.com/86727542/222309338-482e01a5-7246-4db6-874f-518de998aaa8.PNG)
