### ISSUE TITLE
window_sdl2.screenshot uses pygame

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2514] opened 2014-09-26 13:55 UTC
https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L147

**Comment by akshayaurora** [comment] 2015-01-17 09:19
I can't reproduce the issue using sdl2 from mercurial on a mac or a window machine.

**Comment by tito** [comment] 2015-01-18 01:01
same for me, not reproducable on my osx / linux / windows.

**Comment by tito** [comment] 2015-01-18 01:01
Closing, unless we have a way to reproduce.

**Closed by tito** 2015-01-18 01:01 UTC
Labels: sdl2
