### ISSUE TITLE
WipeTransition() in kivy dose not work

### ISSUE THREAD

**Issue by pd-Shah** [kivy/kivy#5236] opened 2017-06-25 06:33 UTC
### Versions

* Python: 3.5
* OS: ubuntu 16.4
* Kivy: 1.10

### Description

WipeTransition() in kivy dose not work.

## **hue.py file:**

```
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen, WipeTransition
from kivy.properties import ObjectProperty
from kivy.uix.widget import Widget

class MenuScreen(Screen):
    pass

class NewGameScreen(Screen):
    class XY(Widget):
        def on_touch_down(self, touch):
            with self.canvas:
                sm.current="load"


class LoadGameScreen(Screen):
    class YX(Widget):
        def on_touch_down(self, touch):
            with self.canvas:
                sm.current="menu"

buildKV = Builder.load_file("hue.kv")
sm=ScreenManager()
sm.add_widget(MenuScreen(name="menu"))
sm.add_widget(LoadGameScreen(name="load"))

class HueApp(App):
    def build(self):
        return sm

if __name__ == "__main__":
    HueApp().run()

```

## **hue.kv file:**

```
<MenuScreen>:
    NewGameScreen:

<NewGameScreen>:
    XY:
        canvas:
    BoxLayout:
        Label:
            text:"NewGameScreen"

<LoadGameScreen>:
    YX:
        canvas:
    BoxLayout:
        Label:
            text: 'LoadGameScreen'
            font_size: 30

```

this code works fine. but after adding WipeTransition() it dose not work. and it close.

```

from kivy.app import App
from kivy.lang import Builder
from kivy.uix.screenmanager import ScreenManager, Screen, WipeTransition
from kivy.properties import ObjectProperty
from kivy.uix.widget import Widget

class MenuScreen(Screen):
    pass

class NewGameScreen(Screen):
    class XY(Widget):
        def on_touch_down(self, touch):
            with self.canvas:
                sm.current="load"


class LoadGameScreen(Screen):
    class YX(Widget):
        def on_touch_down(self, touch):
            with self.canvas:
                sm.current="menu"

buildKV = Builder.load_file("hue.kv")
sm=ScreenManager(transition=WipeTransition())
sm.add_widget(MenuScreen(name="menu"))
sm.add_widget(LoadGameScreen(name="load"))

class HueApp(App):
    def build(self):
        return sm

if __name__ == "__main__":
    HueApp().run()

```

**Comment by bionoid** [comment] 2017-07-10 10:56
There are numerous problems with your code, I don't think this is a Kivy issue. For example, the nested class declarations are not normal and probably related to your problem:

```python
class NewGameScreen(Screen):
    class XY(Widget):
```

The [ScreenManager example](https://github.com/kivy/kivy/blob/master/examples/widgets/screenmanager.py) example demonstrates transitions

**Comment by KeyWeeUsr** [comment] 2017-08-15 16:53
This is very very very strange syntax and I've never seen it used with Kivy, especially in this way (and with canvas!). Anyway, it's not the `WipeTransition`, it's `ShaderTransition`, which for some reason triggered I guess a segfault.

It's because of [this line](https://github.com/kivy/kivy/blob/f66f340236419a6e8856c06b1e429ae2bd9fd285/kivy/uix/screenmanager.py#L476)(`fbo.add(screen.canvas))` i.e. probably trying to add a canvas that wasn't prepared, or is somehow invalid (I wouldn't wonder). If you make the code more sane than the current state, there's no such thing present.

Notice the changes:

```python
sm=ScreenManager(transition=ShaderTransition())
class MenuScreen(Screen):
    pass

class NewGameScreen(Screen):
    class XY(Widget): pass

class LoadGameScreen(Screen):
    class YX(Widget): pass

buildKV = Builder.load_file("hue.kv")
sm.add_widget(MenuScreen(name="menu"))
sm.add_widget(LoadGameScreen(name="load"))
```

```
<XY>:
    on_touch_down:
        app.root.current = 'load'
<YX>:
    on_touch_down:
        app.root.current = 'menu'
```

Anyway, the bug has nothing to do with the transitions themselves, rather with trying to add a new(uninitialized properly perhaps?) `Canvas` to the `Fbo` when it wasn't supposed to. I can't reproduce it in other way, so I'm closing it. Feel free to trace the bug and reopen with a proper example related to it.

Also, please check our tutorials, demos and examples, because your code shows some misunderstood concepts of how we handle things in here. Notice [Kivy Crash Course](http://inclem.net/pages/kivy-crash-course/) and [many other talks/videos/etc](https://github.com/kivy/kivy/wiki/Talks-and-tutorials) related to Kivy.

**Closed by KeyWeeUsr** 2017-08-15 16:53 UTC
