### ISSUE TITLE
SDL2 - on_touch_down is fired when focusing the window by dragging a file on the taskbar icon

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#2609] opened 2014-10-23 18:06 UTC
See it in action: https://vid.me/Bfp

``` python
(<kivy.core.window.window_sdl2.WindowSDL object at 0x04AE6DF8>, <MouseMotionEvent button="left" device="mouse" double_tap_time="0" dpos="(0.0, 0.0)" dsx="0.0" dsy="0.0" dsz="0.0" dx="0.0" dy="0.0" dz="0.0" grab_current="None" grab_exclusive_class="None" grab_list="[]" grab_state="False" id="mouse8" is_double_tap="False" is_mouse_scrolling="False" is_touch="True" is_triple_tap="False" opos="(29.0, 189.0)" osx="0.19727891156462585" osy="1.0" osz="0.0" ox="29.0" oy="189.0" oz="0.0" pos="(29.0, 189.0)" ppos="(29.0, 189.0)" profile="['pos', 'button']" psx="0.19727891156462585" psy="1.0" psz="0.0" push_attrs="('x', 'y', 'z', 'dx', 'dy', 'dz', 'ox', 'oy', 'oz', 'px', 'py', 'pz', 'pos')" push_attrs_stack="[]" px="29.0" py="189.0" pz="0.0" shape="None" spos="(0.19727891156462585, 1.0)" sx="0.19727891156462585" sy="1.0" sz="0.0" time_end="-1" time_start="1414087174.188792" time_update="1414087174.188792" triple_tap_time="0" ud="{}" uid="8" x="29.0" y="189.0" z="0.0">)
```
##

**Comment by KeyWeeUsr** [comment] 2017-01-19 00:17
I can't reproduce with latest version a bare app (`runTouchApp(Button())`), app with single `on_dropfile` and neither with the example `multiple_dropfile.py`. The same even for bindings at `on_release`, `on_press`, `on_touch_*`. I wonder what it was fixed with.

**Comment by KeyWeeUsr** [comment] 2017-05-29 08:21
Seems like it's Win8 and I can't reproduce it in the way it was done in the video. Reopen with the code and instructions that can reproduce it.
```python
from kivy.app import runTouchApp
from kivy.uix.button import Button

class B(Button):
    def on_touch_down(self, touch):
        print(touch)
        super(B, self).on_touch_down(touch)
        print(touch)

runTouchApp(B(text='Test'))
```

**Closed by KeyWeeUsr** 2017-05-29 08:21 UTC
Labels: core, platform-win, sdl2
