### ISSUE TITLE
Nested ScrollView touch transformation is broken for horizontal scrollbars

### ISSUE THREAD

**Issue by lmNt** [kivy/kivy#4444] opened 2016-07-01 10:41 UTC
If you have a nested horizontal ScrollView which uses bars as scroll type, inside a vertical ScrollView, then the touch transformation is broken for the horizontal scroll-bar inside the horizontal ScrollView. It is only noticeable though, if the vertical ScrollView is not starting at `x=0` in window coordinates.

I have added a code snippet to reproduce the error (see below). It is based on kived's nested ScrollView example ([from here](https://gist.github.com/kived/2aa1b6814979340598a7)).

What I also found out was:
- The issue does not occur if the horizontal ScrollView is using content as scroll type.
- The issue does not appear (as already mentioned above) if the vertical ScrollView is starting at `x=0` in window coordinates
- Also the issue does not appear on Kivy 1.8.0. On 1.9.0 and 1.9.1 it appears. (Thanks @bionoid for hinting me to test the different versions.)

```
import kivy

from kivy.app import App
from kivy.lang import Builder

import sys

if 'horizontal' in sys.argv:
    sys.argv.remove('horizontal')
    fmt = {
        'horizontal': 'vertical',
        'x': 'y',
        'y': 'x',
        'width': 'height',
        'height': 'width',
        'col': 'row',
        'row': 'col',
    }
else:
    fmt = {
        'horizontal': 'horizontal',
        'x': 'x',
        'y': 'y',
        'width': 'width',
        'height': 'height',
        'col': 'col',
        'row': 'row',
    }

root = Builder.load_string('''
BoxLayout:
    orientation: 'horizontal'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_x: None
        width: 150
        canvas.before:
            Color:
                rgba: 0, 0, 1, 1
            Rectangle:
                pos: self.pos
                size: self.size
        Label:
            text: "I mess up the nested horizontal scrollbar."
            size_hint_x: None
            width: self.parent.width
            text_size: self.parent.width, None
            max_lines: 5
    BoxLayout:
        orientation: '{horizontal}'
        BoxLayout:
            orientation: '{horizontal}'
            size_hint_{x}: None
            {width}: 0
            Widget:
                id: quarter
            Widget
            Widget
            BoxLayout:
                orientation: '{horizontal}'
                Widget:
                    id: eighth
                Widget
        ScrollView:
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 0.3
                Rectangle:
                    pos: self.pos
                    size: self.size
            scroll_type: ['bars']
            bar_width: 50
            GridLayout:
                {col}s: 1
                size_hint_{y}: None
                {height}: self.minimum_{height}
                {row}_default_{height}: quarter.{height}
                {row}_force_default: True
                Widget
                BoxLayout:
                    orientation: '{horizontal}'
                    canvas.before:
                        Color:
                            rgba: 1, 0, 0, 0.5
                        Rectangle:
                            pos: self.pos
                            size: self.size
                    Widget
                    ScrollView:
                        scroll_type: ['bars']
                        bar_width: 50
                        GridLayout:
                            {col}s: 1
                            size_hint_{y}: None
                            size_hint_{x}: 2.0
                            {height}: self.minimum_{height}
                            {row}_default_{height}: eighth.{height}
                            {row}_force_default: True
                            canvas.before:
                                Color:
                                    rgba: 1, 1, 1, 1
                                Rectangle:
                                    pos: self.pos
                                    size: self.size
                            Widget
                            Label:
                                text: 'Hi!'
                                canvas.before:
                                    Color:
                                        rgba: 0, 0, 1, 0.5
                                    Rectangle:
                                        pos: self.pos
                                        size: self.size
                            Widget
                    Widget
                Widget
'''.format(**fmt))

class TestApp(App):
    def build(self):
        return root

if __name__ == '__main__':
    TestApp().run()
```

**Comment by sugarlata** [comment] 2017-05-03 23:32
Hi All,

Have bumped into this issue also. In my case it's a nested Vertical Scroll View inside another Vertical Scroll View. Wondering what the progression on fixing this bug is?
It's something I'm willing to take a look at fixing, although I'm fairly new to kivy. What would be the best next steps to see a solution come about?

**Comment by KeyWeeUsr** [comment] 2017-05-04 00:06
Hard to say something about the progress, but I don't see any active related branch to this issue, so... yeah. But to make it easier, there probably was something similar with `Scatter`(https://github.com/kivy/kivy/commit/fad2f9ce9b3b03bddacf50e0248ccddf2b971bf6), so I'd definitely look at that thing too after reading/understanding how the `ScrollView` works. ^^

**Comment by sugarlata** [comment] 2017-05-04 01:02
Thank you! Will have a look.

**Comment by matham** [comment] 2017-09-07 23:47
So I ran into an issue with this using the following code tested by moving the mouse a little bit:

```py
from kivy.lang import Builder
from kivy.app import runTouchApp

w = Builder.load_string('''
ScrollView:
    scroll_type: ['bars']
    on_touch_move: print('s', args[1].grab_current, args[1])
    Widget:
        on_touch_move: print('w', args[1].grab_current, args[1])
''')

runTouchApp(w)
```

With 1.10.1 I get
```
s None <MouseMotionEvent spos=(0.42125, 0.7833333333333333) pos=(337.0, 470.0)>
w None <MouseMotionEvent spos=(0.42125, 0.7833333333333333) pos=(337.0, 470.0)>
s None <MouseMotionEvent spos=(0.42125, 0.7816666666666667) pos=(337.0, 469.00000000000006)>
w None <MouseMotionEvent spos=(0.42125, 0.7816666666666667) pos=(337.0, 469.00000000000006)>
```

With this PR merged I get:
```
s None <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
w None <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
s <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
w <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.28625, 0.8283333333333334) pos=(229.0, 497.0)>
s None <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
w None <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
s <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
w <kivy.uix.scrollview.ScrollView object at 0x000001AFCA6D2B40> <MouseMotionEvent spos=(0.33875, 0.6766666666666667) pos=(271.0, 406.00000000000006)>
```

With 1.10.0, we get one call per widget, with `grab_current` None. With master, you two calls for each touch, once with `grab_current` None and the other time with it set to the sv. Obviously I can just ignore it if it's not None, but I'm wondering if this is the correct behavior.

**Comment by matham** [comment] 2017-09-07 23:50
On second thought, when `grab_current` is not None, the widget that gets the callback should probably not propagate the touch to its children as it was meant for it due to the grab I think.

**Comment by matham** [comment] 2019-03-14 01:13
I guess I forgot to reopen after reverting because the issue is still present. Here's a small reproducible example:

```py
from kivy.app import App
from kivy.lang import Builder

text = '\\n'.join(
    ','.join(
        map(str, range(100) if i % 2 else range(100, 200))
    ) for i in range(100))

root = Builder.load_string('''
ScrollView:
    scroll_type: ['bars', ]
    bar_width: '15dp'

    BoxLayout:
        size_hint_y: None
        height: 1.1 * self.parent.height
        Widget
        BoxLayout:
            orientation: 'vertical'
            Widget
            ScrollView:
                scroll_type: ['bars', ]
                bar_width: '15dp'
                Label:
                    size_hint: None, None
                    size: self.texture_size
                    text: '{}'
            Widget
        Widget
'''.format(text))


class TestApp(App):
    def build(self):
        return root


if __name__ == '__main__':
    TestApp().run()
```

**Comment by matham** [comment] 2019-04-15 23:29
Fixed by https://github.com/kivy/kivy/pull/6252.

**Closed by matham** 2019-04-15 23:29 UTC
Labels: confirmed, widgets
