### ISSUE TITLE
Memory Leak with animation.Sequence

### ISSUE THREAD

**Issue by DigiCoyote** [kivy/kivy#3764] opened 2015-11-11 17:56 UTC
I've noticed that when I add an animation.Sequence to the stage (created with "+= Animation"), I don't get my memory back when I've removed it. I've checked references to it quite thoroughly. I'm storing the sequence in a list, then using 'del' to remove it from the list. This was the case in kivy 1.8.0 as well.

**Comment by dessant** [comment] 2015-11-11 18:44
@DigiCoyote could you post a runnable example for easier reproduction?

**Comment by DigiCoyote** [comment] 2015-11-11 19:20
Sure, give me a day or so, aiming for tomorrow to push my kivy app to istore and play.

**Comment by DigiCoyote** [comment] 2015-11-11 20:04
Here you go:
http://pastebin.com/FYqsgzLT

Keep clicking the button and watch memory usage increase.

**Comment by matham** [comment] 2015-11-17 21:26
I don't see any evidence of a leak here. What makes you think there's a leak there? 

Also, you never seem to stop the animation and you set it to repeat, so of course it'll stay alive forever.

**Comment by DigiCoyote** [comment] 2015-11-17 21:33
I was running this on Windows and watching the task manager memory increase for that python instance. Also, when running it on my phone it became very slow and glitchy after a few minutes.

 

In the code example, where would you put the animation stop call so it’s handled correctly?

**Comment by matham** [comment] 2015-11-17 22:47
Well that code is not real code. But in real code I'd think about whether repeat needs to be true, and if it does, I'd make sure to stop it manually when the animation is not needed anymore.

I'm closing this for now as this should resolve your issue. If you still see leaks re-open. You should also keep in mind that python does not do garbage collection instantly, so to be sure its an issue you have to call `gc.collect()` and still see the issue.

**Comment by DigiCoyote** [comment] 2015-11-18 02:29
So, I'm not sure what you mean by 'real code'. Dessant asked my to provide a simplified example, that's what this is. Did you run it in a Windows environment and watch the taskmanager as you pressed the button continuously? You can clearly see that ram is being used and not freed.

I've rejigged my code based on what I could get from your instructions. Is this what you suggested?:
http://pastebin.com/EZpeXjEy

Memory usage still increases with the changes.

In the kivy irc channel, I saw that it is not best practice to use gc. Are there conflicting opinions on this?

**Comment by matham** [comment] 2015-11-18 03:13
Ok, I can see how me saying that might have seemed like I was saying that that code is not good or that I was criticizing it. That's not what I meant. By real code I just meant code that you're actually using to do something. I assumed the code you posted by dessant's request is not code you actually want to use like that but is just an example. So I for that example I couldn't really tell you when to stop it since it doesn't have an actual purpose. 

What I'm basically saying, I'd need to know what you're actually trying to do in order to tell you when you should stop it. But at that point, you as the code author should know this better than I do.

Your changes didn't fix it because you weren't canceling it properly. Here's the proper solution: http://pastebin.com/0rdNEKgy.

```In the kivy irc channel, I saw that it is not best practice to use gc. Are there conflicting opinions on this?
```

When I said to use gc, I just meant to use it while testing because python doesn't always release the memory. But in the real world you would not use it.

**Comment by DigiCoyote** [comment] 2015-11-19 01:41
Hey man,

 

Thanks for clarifying. Makes sense.

 

So, the code here is not far off from what we’re actually doing. I’m attaching a midi keyboard to the app, and with certain midi key presses, it shows different effects on the stage. Shapes blinking, fading, rotating, the screen turning different colors, etc… so adding and removing an animated object that has the “repeat = True” is not really far off of reality for us. This is why I was concerned about memory being used up in this example.

 

This being the case, I think where you put the ‘cancel’ property makes sense, no? And remove_widget in the line below ‘cancel’ will destroy the rest of the remaining objects (self.color_animation and self.my_scatter_layout) correct?

 

It looks to be working much better. Memory continuously fluctuates up and down, but it doesn’t seem to rise about 43 M. 

 

Does this all read well to you?

**Comment by matham** [comment] 2015-11-19 01:49
Yes, canceling and then removing the widget in that function should solve the issue and seems reasonable from what you said. That should make sure only the last animation and widget used remains in memory, until that is removed as well when you create the next animation and widget.

**Comment by DigiCoyote** [comment] 2015-11-19 04:26
Super wicked cool awesome. 

 

Thanks for the hand :)

**Closed** 2015-11-19 11:33 UTC

**Comment by tito** [comment] 2015-11-19 11:38
One way to debug this memory leak is to use objgraph.

Before the fix, if you import objgraph at the start of your main.py, you can add in your remove_animation_sequence():

        objgraph.show_growth()

The first call will print all the object created from the start of the app, so you can ignore it, but next call will show only incremental diff.

For example (step 2):
```
dict               2775       +32
EventObservers      776       +21
BoundCallback       537       +17
list               4526       +15
WeakMethod          414       +14
Animation           104        +4
Sequence             78        +3
Canvas               55        +2
instancemethod       67        +2
CanvasBase           52        +2
```

Step 3:
```
dict                           2814       +39
WeakMethod                      435       +21
EventObservers                  797       +21
BoundCallback                   553       +16
list                           4541       +15
weakref                        1119       +10
Animation                       108        +4
Sequence                         81        +3
Canvas                           57        +2
builtin_function_or_method     1337        +2
```

After the fix, no more Animation and related object leaked.
