### ISSUE TITLE
Nested Scrollviews

### ISSUE THREAD

**Issue by sersadaka** [kivy/kivy#7182] opened 2020-10-29 09:16 UTC
Python / kivy 

Dear kivy developers, I know I am still new in python kivy, but to be honest I spent 6 months on a project, yet a long journey remaining! , I got shocked when I found that I couldn't fix this nested scrollview issue, my full project is based on nested horizontal scrollviews! , I believe python kivy is an easy program to help us to make apps easily, I compared with other programs it is the easiest, and I cannot cut my journey here! please try to fix this nested scrollview issue, as it must be same as any app nested horrizontal scrollview which if the user applied the touch on the nested scroll, if he scrolls in x directionit will scroll, if he scrolls in Y direction only the parent scrollview must scroll vertically and so on.. Thank you for your time!

**Comment by matham** [comment] 2020-10-29 17:33
I believe it is a duplicate of https://github.com/kivy/kivy/issues/5617. 

If it isn't, please feel free to re-open the issue with a short, self-contained, and runnable example showing the issue.

**Closed by matham** 2020-10-29 17:33 UTC

**Comment by sersadaka** [comment] 2020-10-30 06:09
@matham I believe you understand what I want, I have seen all links related to nested scrollviews even this one, so far couldnt find the solution, the code is way big to put here!! but a simple example do you see facebook story ? in the tom of the homepage when u are scrolling in between people's story, I want to have the same type of scrollview, which indicates that if the user scrolls in y direction it will only allow the vertical parent scroll to scroll, while if the user scrolls in x direction, then only the nested horizontal scrollview will scroll in x direction!

**Comment by sersadaka** [comment] 2020-10-30 06:38
I tried to make a simple code that looks similar to mine:

import kivy
from kivy.app import App
from scrollview import Scroll_View
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.carousel import Carousel
from kivy.uix.button import Button
from kivy.metrics import cm
from kivy.lang import Builder
from kivy.uix.floatlayout import FloatLayout
from kivy.core.window import Window
kv = Builder.load_string('''
FloatLayout:
    Scroll_View:
        size_hint:1,1
        pos_hint:{'center_x':0.5,'center_y':0.5}
        do_scroll:(True,True)
        GridLayout:
            size_hint_y:None
            cols:1
            #height:self.minimum_height
            size:self.minimum_size
            id:scroll_vertical
''')

class Scroller(Scroll_View):
    def on_touch_move(self, touch):
        print(touch.pos)

class NotificationDemoApp(App):
    def build(self):
        return kv

    def print_btn(self, instance):
        print ('Pressed', instance.text)

    def on_start(self,*args):

        main_grid = self.root.ids.scroll_vertical

        fafa=FloatLayout(size_hint_y=None, height=Window.height/1.5)

        scroller = Scroller(effect_cls= "ScrollEffect",size_hint=(1,0.2)
                                                 ,pos_hint={'x': 0, 'y': 0.5})


        banner_Grid_Floats = GridLayout(rows=1, spacing=20, size_hint=(None, None), height=200)
        banner_Grid_Floats.bind(minimum_width=banner_Grid_Floats.setter('width'))


        for i in range(20):
            btn = Button(text=str(i),size_hint_x=None)
            banner_Grid_Floats.add_widget(btn)

        scroller.add_widget(banner_Grid_Floats)
        fafa.add_widget(scroller)
        main_grid.add_widget(fafa)

if __name__ == '__main__':
    NotificationDemoApp().run()

**Comment by sersadaka** [comment] 2020-10-30 06:39
I want to be able to scroll vertically from this horizontal scroll, not from the screen window, and while doing vertical scroll I dont want to disturb this horizontal scroll, say the user did scroll in y and x direction starting from y direction this must only allow vertical scroll to scroll, not the horizontal one and versa vice!

**Comment by sersadaka** [comment] 2020-10-30 07:54
although how to reopen an issue xd

**Comment by matham** [comment] 2020-10-30 08:54
I tried running your example and I didn't see any unexpected behavior. Please ask on discord for any further help because we only use github issues for bugs, not support requests. If you're running into the other issue I linked to above, I'm afraid there's currently no fix for that.

**Comment by sersadaka** [comment] 2020-10-30 10:08
read this post , https://github.com/kivy/kivy/issues/7188
