### ISSUE TITLE
Kivy on debian-testing under python3 not working

### ISSUE THREAD

**Issue by laerus** [kivy/kivy#4742] opened 2016-11-20 12:14 UTC
debian-testing, python3.5.2, no pygame, GNOME Shell 3.22.2

following the [instructions](https://kivy.org/docs/installation/installation-linux.html#debian-jessie-or-newer) tried to install from stable repo:
```
$ sudo apt install python3-kivy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-kivy : Depends: python3-kivy-bin (= 1.9.1-2~stable0+201608272110~pkg135~ubuntu14.04.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

$ sudo apt install python-kivy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-kivy : Depends: python-gst0.10 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
same for daily repo under python3

i've managed to install daily kivy build on python2
then tried to run a kivy app:
```
> python main.py 
[WARNING] [Config      ] Older configuration version detected (14 instead of 16)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/laerus/.kivy/logs/kivy_16-11-20_24.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12+ (default, Sep  1 2016, 20:27:38) 
[GCC 6.2.0 20160927]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] Building Custom Calendar.
[INFO   ] Building App
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name bcm
  File "/usr/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: No available video device
  File "/usr/lib/python2.7/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 139, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 789, in __init__
    self.create_window()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 262, in create_window
    self.fullscreen, resizable, state)
  File "_window_sdl2.pyx", line 79, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1809)
  File "_window_sdl2.pyx", line 54, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy/core/window/_window_sdl2.c:1459)

x11 - ImportError: No module named window_x11
  File "/usr/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

notes:
gnome doesn't seem to be under X11 anymore,

i've tried to run kivy on a different machine under weston-wayland and i had the same problem as described here managed to solve it by instaling pygame (doesn't seem to work anymore)

ofc i've installed all sdl2, egl related packages on system 
(maybe there is something missing from the docs?)

please help!

edit:
```
> python
Python 2.7.12+ (default, Sep  1 2016, 20:27:38) 
[GCC 6.2.0 20160927] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from kivy.core.window import Window
[INFO   ] [Logger      ] Record log in /home/laerus/.kivy/logs/kivy_16-11-20_30.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.12+ (default, Sep  1 2016, 20:27:38) 
[GCC 6.2.0 20160927]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name bcm
  File "/usr/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: No available video device
  File "/usr/lib/python2.7/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 139, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/__init__.py", line 789, in __init__
    self.create_window()
  File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 262, in create_window
    self.fullscreen, resizable, state)
  File "_window_sdl2.pyx", line 79, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1809)
  File "_window_sdl2.pyx", line 54, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy/core/window/_window_sdl2.c:1459)

x11 - ImportError: No module named window_x11
  File "/usr/lib/python2.7/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)


```

**Comment by laerus** [comment] 2016-11-21 10:37
running with nvidia drivers, any chance this is the root of the problem?

**Comment by laerus** [comment] 2016-11-22 12:39
This seems to be a debian nvidia drivers problem, i returned to nouveau and the last bug doesn't show up. Still though, kivy cannot install under python3.5 on debian-tesitng and that's the only version of python3.

**Comment by laerus** [comment] 2016-11-23 12:48
it's not an nvidia problem, after installing some pkg the problem started appearing again, it  has something to do with libx11 related packages or how kivy searches for a window provider. This is an issue on kivy side.

**Comment by laerus** [comment] 2016-11-23 14:32
also kivy managed to segfault on Weston.

**Comment by FeralBytes** [comment] 2017-01-04 15:39
@laerus I have encountered something like this BCM issue before; but basically it was resolved by a clean re-install. Which means either something is going wrong with the Kivy install or something is going wrong with a different package and Kivy Highlights the issue. If I remember correctly the issue was tied to Nvidia Prime and so I had to make sure that the Nvidia card was active; not the Intel card.
As for Kivy not being install-able due to a dependency on python-gst-0.10; that problem is being fixed right now. I just did a PR to remove pygst aka python-gst; and so only a working version of gStreamer should be needed and the version is likely gStreamer 1.8 +.
So, can you start with a clean install of Debian testing and then install Kivy from the Kivy repository on Github; and install all of the dependencies but leave out python-gst. Also it should be install-able in Python3; although I have not tested.

**Comment by FeralBytes** [comment] 2017-01-04 15:39
Also the segfault did you mean Wayland?

**Comment by laerus** [comment] 2017-01-04 19:21
Hey @FeralBytes, yes weston is the reference wayland compositor and a package under debian-testing.

thanks for your response, i will try for a clean kivy install under python3, gnome and see how it'll go.

**Comment by FeralBytes** [comment] 2017-01-16 10:45
@laerus Any luck?

**Comment by laerus** [comment] 2017-01-17 16:27
tried again from the debian testing repo with python3-kivy Version: 1.9.1-1

```
> python3 main.py 
[WARNING] [Config      ] Older configuration version detected (0 instead of 14)
[WARNING] [Config      ] Upgrading configuration in progress.
[INFO   ] [Logger      ] Record log in /home/laerus/.kivy/logs/kivy_17-01-17_0.txt
[INFO   ] [Kivy        ] v1.9.1
[INFO   ] [Python      ] v3.5.3rc1 (default, Jan  3 2017, 04:40:57) 
[GCC 6.3.0 20161229]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
##*** Currently in: /home/laerus/Dropbox/src/organCalendar
[INFO   ] Building Custom Calendar.
[INFO   ] Building App
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[CRITICAL] [Window      ] Unable to find any valuable Window provider at all!
egl_rpi - ImportError: cannot import name 'bcm'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - TypeError: expected bytes, str found
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 138, in __init__
    super(WindowSDL, self).__init__()
  File "/usr/lib/python3/dist-packages/kivy/core/window/__init__.py", line 722, in __init__
    self.create_window()
  File "/usr/lib/python3/dist-packages/kivy/core/window/window_sdl2.py", line 237, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 94, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy/core/window/_window_sdl2.c:1936)

x11 - ImportError: No module named 'kivy.core.window.window_x11'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
```

**Comment by thopiekar** [comment] 2017-01-17 19:17
First of all the PPA is not meant to be used with Debian, so you are installing Kivy using packages built on Ubuntu on your own risk.
Second, if you are mixing distros try to fetch the Ubuntu release from the PPA, which fits the most to your Debian installation. Eg. you mentioned that there is only Python 3.5, so try to use 'yakkety' here 😉 

Regards

**Comment by laerus** [comment] 2017-01-17 19:27
the last comment was about installing kivy from the debian-testing repo not the kivy one.

**Comment by thopiekar** [comment] 2017-01-17 19:30
Oops, sorry. In that case check the package itself, who the maintainer is. You can use Synaptic for that.

Our PPA packaging differs a lot to the Debian or Ubuntu packaging.

I guess the maintainer(s), who own the package from debian-testing can help you much better.

**Comment by dessant** [comment] 2017-01-20 11:30
If there is still an issue with the packages we maintain, please open a new issue with step by step instructions for reproducing the bug.

**Closed by dessant** 2017-01-20 11:30 UTC
Labels: awaiting-reply, distribution

**Comment by laerus** [comment] 2017-01-20 11:44
should i try installing from the kivy repo on debian-testing or do they only work for ubuntu as previously noted?

**Comment by dessant** [comment] 2017-01-20 11:59
You may try installing the ppa on debian, and it could work, but as @thopiekar said, we do not support the use case.

**Comment by dessant** [comment] 2017-01-20 12:01
@thopiekar, though we may need to remove this block 😋: https://kivy.org/docs/installation/installation-linux.html#debian-jessie-or-newer.

**Comment by dessant** [comment] 2017-01-20 12:06
@laerus, if you haven't set up a working kivy installation yet, try installing these dependencies, mainly the libsdl2 ones, and then pip install kivy. https://kivy.org/docs/installation/installation-linux.html#ubuntu-example

Of course remove any trace of kivy from your system beforehand.

**Comment by laerus** [comment] 2017-01-20 13:05
allright, thanks for the info!

**Comment by FeralBytes** [comment] 2017-01-20 22:29
@laerus I also would like to know if the install via the PPA does work or not. Thanks.
