### ISSUE TITLE
Updating ScrollView from outside and scrolling with mouse after.

### ISSUE THREAD

**Issue by Naomak** [kivy/kivy#1078] opened 2013-04-03 12:11 UTC
When I set ScrollView's scroll_y(x) property from outside (by some button), position of content is updated as supposed. But then when you try to scroll (with mouse wheel) after increasing scroll_y value (still in range 0-1), content and its move animation starts from place before 'outside' updating. When decreasing scroll_y and then scrolls with mouse, it works nicely though.

Test code in gist: https://gist.github.com/Goffrey/5299929
Steps to see problem:
1. Scrolls completely down with wheel.
2. Scroll UP to middle with Up button.
3. Now scroll with mouse wheel:
    \* when scrolling up - it jumps down to little scrolled height from bottom
    \* when scrolling down - it jump completely to the bottom
##

**Comment by fgmcoelho** [comment] 2015-04-30 21:56
This issue still happens on version 1.8 and 1.9.

Here is some info:
https://groups.google.com/forum/?hl=en-US&fromgroups=#!topic/kivy-users/PlSwk_MXe3s

**Comment by dessant** [comment] 2015-05-01 20:01
I can confirm that scrollview is jumping to the bottom in certain cases.

**Comment by fgmcoelho** [comment] 2015-05-01 21:46
Hi, i checked the code to try to track the issue. It seems that the problem is on the _update_effect_x and y. Unfortunately it is a holiday in my country and I won't be able to look further to this issue until Monday, but this should give you a pointer if you want to take a look.

Thanks for revisiting this issue so fast.

**Comment by fgmcoelho** [comment] 2015-05-04 19:19
Adding further info:
calling _update_effect_x_bounds() and _update_effect_y_bounds() after setting the values of scroll_x and scroll_y will remove problem of it jumping back to the old position.

But if you try to replace the scroll view when it is still moving from a long drag, the position will still bug.

**Comment by dessant** [comment] 2015-10-17 21:19
refs
https://github.com/kivy/kivy/issues/3382
https://github.com/kivy/kivy/issues/2038#issuecomment-46158938

**Comment by tshirtman** [comment] 2017-03-02 09:34
I worked around this in my app by calling `_update_effect_y_bounds()` when scroll_y was changed from code, i'm not familiar enough with SV code to know how wrong/inefficient it is, but maybe adding it to _update_from_scroll would solve the issue in a more general way.

**Comment by Bakterija** [comment] 2017-03-29 20:19
I just wanted to do a pull request that solves this problem and accidentaly commited the changes.
This commit makes scrollview not reset back to start position when scroll_y or scroll_x value is set from outside and then scrolled with a touch event https://github.com/kivy/kivy/commit/dce021f9d6d4b20f32e93876302c89e27e1b3f44.

**Comment by matham** [comment] 2020-07-11 02:32
Fixed in https://github.com/kivy/kivy/commit/dce021f9d6d4b20f32e93876302c89e27e1b3f44

**Closed** 2020-07-15 02:38 UTC
Labels: needs-analysis, widgets
