### ISSUE TITLE
Window resize recursion error while using ScrollView

### ISSUE THREAD

**Issue by syfenx** [kivy/kivy#5638] opened 2018-03-01 14:07 UTC
### Versions

* Python: 3.6
* OS: Linux (Debian Jessie 8.2)
* Kivy: v1.10.1.dev0, git-3f01ba0, 20180228

* Kivy installation method: 
### Description

I'm using a large custom widget that draws a grid/spots and this is put inside a ScrollView, everything works as intended until the window is resized and a recursion error occurs.

### Code and Logs

```python


[INFO   ] [Logger      ] Record log in /home/xxxx/.kivy/logs/kivy_18-03-01_17.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-3f01ba0, 20180228
[INFO   ] [Python      ] v3.6.3 (default, Nov  9 2017, 06:46:20) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 375.82'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'GeForce GTX 1050 Ti/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...



   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 516, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/home/xxxx/.virtualenvs/kivytest36/lib/python3.6/site-packages/kivy/effects/scroll.py", line 108, in on_value
     self.scroll = self.value
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 516, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/home/xxxx/.virtualenvs/kivytest36/lib/python3.6/site-packages/kivy/uix/scrollview.py", line 576, in _update_effect_x
     self.scroll_x = -sx
   File "kivy/properties.pyx", line 478, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 516, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 571, in kivy.properties.Property.dispatch
   File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1120, in kivy._event.EventObservers._dispatch
   File "/home/xxxx/.virtualenvs/kivytest36/lib/python3.6/site-packages/kivy/uix/scrollview.py", line 557, in _update_effect_bounds
     self._update_effect_x_bounds()
   File "/home/xxxx/.virtualenvs/kivytest36/lib/python3.6/site-packages/kivy/uix/scrollview.py", line 544, in _update_effect_x_bounds
     self.effect_x.value = self.effect_x.min * self.scroll_x

```

### Quick fix

https://github.com/kivy/kivy/blob/3f01ba0b9983ae60ca69d4d34d6b07ad3777c36a/kivy/uix/scrollview.py#L553

This function causes the recursion error, I've put a pass on it temporarily to see if it would solve the issue, it does but I'm not entirely sure if something else is negatively affected. (It doesn't appear so in my case)

```python

    def _update_effect_bounds(self, *args):
        pass
        # if not self._viewport:
        #     return
        # if self.effect_x:
        #     self._update_effect_x_bounds()
        # if self.effect_y:
        #     self._update_effect_y_bounds()

```

### Example code

```python

import kivy
kivy.require("1.10.0")
from kivy.app import App

from kivy.config import Config
Config.set('graphics', 'width', '1920')
Config.set('graphics', 'height', '1080')
from kivy.uix.gridlayout import GridLayout
from kivy.uix.scrollview import ScrollView
from kivy.uix.widget import Widget
from random import randint
from kivy.graphics import Color, Ellipse

# Steps to reproduce error
# Window opens, move scrollbars, resize window, maximize
# ** It might not happen right away.

class MyPaintWidget(Widget):
    def __init__(self, **kwargs):
        super(MyPaintWidget, self).__init__(**kwargs)

        self.size_hint=(None,None)
        self.size=(5000,5000)
        with self.canvas:
            Color(1, 1, 0)
            for x in range(5000):
                Ellipse(pos=(randint(0,self.size[0]),randint(0,self.size[1])), size=(5, 5))


class BaseLayout(GridLayout):
    def __init__(self, **kwargs):
        super(BaseLayout, self).__init__(**kwargs)


class BaseApp(App):
    def __init__(self, **kwargs):
        super(BaseApp, self).__init__(**kwargs)

    def build(self):
        base_layout = BaseLayout()

        step_base = ScrollView(
            size_hint=(1,1),
            do_scroll_y=True,
            do_scroll_x=True)
        step_base.bar_width=20
        step_base.scroll_type = ['bars']

        paint_widget = MyPaintWidget()
        step_base.add_widget(paint_widget)

        return step_base

base_app = BaseApp()
base_app.run()

```

**Comment by tshirtman** [comment] 2018-03-04 13:37
So i trimmed down the example a bit, and tried using a create_trigger to fix it, it looks like it mitigate the issue quite a lot, but i still manage to hit it sometime, if i scroll *and* resize the window at the same time (quite fast, too, by toggling floating mode for the window in i3 continuously). people can test this "fix" with the following example, though i'll keep looking for a better one.

```
import kivy
kivy.require("1.10.0")  # noqa
from kivy.app import App

from kivy.config import Config
Config.set('graphics', 'width', '1920')  # noqa
Config.set('graphics', 'height', '1080')  # noqa

from kivy.uix.scrollview import ScrollView
from kivy.uix.widget import Widget
from random import randint
from kivy.graphics import Color, Ellipse
from kivy.effects.dampedscroll import DampedScrollEffect
from kivy.clock import Clock

# Steps to reproduce error
# Window opens, move scrollbars, resize window, maximize
# ** It might not happen right away.


class MyPaintWidget(Widget):
    def __init__(self, **kwargs):
        super(MyPaintWidget, self).__init__(**kwargs)

        self.size_hint = (None, None)
        self.size = (5000, 5000)
        with self.canvas:
            Color(1, 1, 0)
            for x in range(5000):
                Ellipse(
                    pos=(randint(0, self.size[0]), randint(0, self.size[1])),
                    size=(5, 5)
                )


class SafeScrollEffect(DampedScrollEffect):
    def __init__(self, **kwargs):
        super(SafeScrollEffect, self).__init__(**kwargs)
        self.on_value = Clock.create_trigger(
            super(SafeScrollEffect, self).on_value)


class BaseApp(App):
    def build(self):
        step_base = ScrollView(effect_cls=SafeScrollEffect)
        step_base.bar_width = 20
        step_base.scroll_type = ['content', 'bars']

        paint_widget = MyPaintWidget()
        step_base.add_widget(paint_widget)

        return step_base


base_app = BaseApp()
base_app.run()
```

**Comment by tshirtman** [comment] 2018-03-14 12:12
I had the same issue with a scrollview that was being resized (by an Animation) while trying to scroll it, current workaround is to disable the scrollview while it's being animated.

**Comment by rodrigocfaria** [comment] 2019-05-09 02:26
I have the same problem, it occurs when I have both x and y scroll enabled, and only happens when I resize the window in y axis after I have scrolled the horizontal bar. If I don't move the horizontal bar at all since the program start, I don't get the RecursionError.

**Comment by kuguma** [comment] 2019-07-04 11:51
Completely the same as @rodrigocfaria's case. @tshirtman's patch has worked when `scroll_type=['content', 'bars']`, but has not worked when `scroll_type=['bars']`.

**Comment by rodrigocfaria** [comment] 2019-07-04 21:19
Yes, I discovered the same, dual axis scroll with scroll_type = ['bars'] breaks Kivy.

---元のメッセージ---
オン 2019年7月4日 8:51, kuguma は書きました。

**Comment by ecdsa** [comment] 2019-09-09 10:14
possibly the same issue here: https://github.com/spesmilo/electrum/issues/5189

**Comment by kuguma** [comment] 2019-11-12 14:25
Attempting to resolve. Here is what I learned at the moment: (The kivy version is 1.11.1.)

- Confirmed the situation that abnormal values ​​are assigned to _viewport, height, width of ScrollView class in the process of changing window size.

- All do_layouts of the upper widget will change the width and height of the ScrollView with value that before layout converges every time the window size is changed.
This change triggers update_effect_bounds every time.

- _viewport is reset by a “bad” widget, such as tabbed_panel, that add_widget a child again in the layout process. 
(Show tabbedpanel.py line 686. This is a pretty bad implementation and should be fixed.)
The size of _viewport at this point is a small size before optimization is performed, but ScrollView performs calculations by referring to it.

I will continue to work on it, but please let me know if you have noticed anything.

**Comment by kuguma** [comment] 2019-11-12 16:24
Mostly solved.

Modify ScrollView as follows:

```
def _update_effect_x(self, *args):
    vp = self._viewport
    if not vp or not self.effect_x:
        return
    sw = vp.width - self.width
    if sw < 1:
        return
    sx = self.effect_x.scroll / float(sw)
    self.scroll_x = -sx
    self._trigger_update_from_scroll()

def _update_effect_y(self, *args):
    vp = self._viewport
    if not vp or not self.effect_y:
        return
    sh = vp.height - self.height
    if sh < 1:
        return
    sy = self.effect_y.scroll / float(sh)
    self.scroll_y = -sy
    self._trigger_update_from_scroll()
```

It seems that line602,616 (specialization with the is_manual flag) in scrollview.py was causing problems.
This flag seems to be True when the effect is started, but the effect may stop when the window is resized for some reason.

**Comment by Elucin** [comment] 2020-03-12 14:17
I was having this issue, but it's because I had created a class that inherited from ScrollView and had foolishly overridden __len__.

**Comment by matham** [comment] 2020-07-11 02:54
https://github.com/kivy/kivy/pull/6985 fixes the original issue.

**Closed** 2020-07-15 02:38 UTC
