### ISSUE TITLE
Some fonts are not fully displayed

### ISSUE THREAD

**Issue by me2beats** [kivy/kivy#6150] opened 2019-02-10 14:33 UTC
Some fonts are not fully displayed, for example:
https://www.fontpalace.com/font-download/New+York+Deco/

```
from kivy.app import App
from kivy.lang import Builder
from kivy.core.text import LabelBase

LabelBase.register(
    name='New York Deco',
    fn_regular='New York Deco.ttf',
    fn_bold='New York Deco.ttf')

KV = """
Label
    font_name: 'New York Deco'
    text: 'THIS TEXT IS NOT displaying properly'

    font_size: 30

"""

class MyApp(App):
    def build(self):
        self.root = Builder.load_string(KV)

MyApp().run()
```

Result:
only the bottom of the text is displayed

Tested with sdl2 and pil providers, ununtu

**Comment by tito** [comment] 2019-02-10 22:15
The font is broken by itself? Check it in https://www.glyphrstudio.com/online/
The font goes above its own bounding box. Even some preview on the tool is broken.

It is quite unusual, but i doubt this is something in Kivy itself? We ask for the size of the bounding box of a text from SDL2, or pygame, or else.

I'm hesitating about a wontfix. Fix the font?
(I already got issues about some home made font by designer, the only way is to fix at least their bounding box then everything is ok.)

Maybe give a try to pango backend too?

**Comment by me2beats** [comment] 2019-02-12 12:35
I have the same problem with Pygame (created an issue):
https://github.com/pygame/pygame/issues/818

But this font displayed fine for example in Godot engine 3.

I'll try to check out pango, but I don’t have a chance yet.

**Comment by me2beats** [comment] 2019-02-23 22:26
It seems there is a solution using pygame https://github.com/pygame/pygame/issues/818#issuecomment-464936369

But still curious how to implement it in kivy.

**Comment by Julian-O** [comment] 2023-11-05 10:09
I am less hesitant about closing the issue - the font is broken.

**Closed by Julian-O** 2023-11-05 10:09 UTC
Labels: Status: Confirmed
