### ISSUE TITLE
GStreamer-WARNING 

### ISSUE THREAD

**Issue by alidalee** [kivy/kivy#6070] opened 2018-12-10 10:01 UTC
# Versions

* Python:2.7.14
* OS: win 10
* Kivy:1.10.1
* Kivy installation method:
python -m pip install --upgrade pip wheel setuptools
python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew
python -m pip install kivy.deps.gstreamer
python -m pip install kivy.deps.angle
python -m pip install kivy

# Description
Hi,I'm learing kivy.when i was trying to use kivy.uix.video .I got this  .

[INFO   ] [Logger      ] Record log in C:\Users\Administrator\.kivy\logs\kivy_18-12-10_27.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [VideoGstplayer] Using Gstreamer 1.14.1.0
[INFO   ] [Video       ] Provider: gstplayer
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] GLEW initialization succeeded
[INFO   ] [GL          ] Backend used <glew>
[INFO   ] [GL          ] OpenGL version <4.6.0 NVIDIA 399.24>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <GeForce GTX 1050 Ti/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <4.60 NVIDIA>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[ERROR  ] [Image       ] Error reading file http://video.ted.com/talk/stream/2004/None/DanGilbert_2004-180k.mp4
[INFO   ] [Base        ] Start application main loop

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libass-9.dll': 'C:\Python27\share\gstreamer\bin\libass-9.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libgstassrender.dll': 'C:\Python27\share\gstreamer\bin\libgstassrender.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libgstpango.dll': 'C:\Python27\share\gstreamer\bin\libgstpango.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libgstrsvg.dll': 'C:\Python27\share\gstreamer\bin\libgstrsvg.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libharfbuzz-0.dll': 'C:\Python27\share\gstreamer\bin\libharfbuzz-0.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libpangocairo-1.0-0.dll': 'C:\Python27\share\gstreamer\bin\libpangocairo-1.0-0.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\libpangoft2-1.0-0.dll': 'C:\Python27\share\gstreamer\bin\libpangoft2-1.0-0.dll': 找不到指定的程序。

(python.exe:8964): GStreamer-WARNING **: Failed to load plugin 'C:\Python27\share\gstreamer\bin\librsvg-2-2.dll': 'C:\Python27\share\gstreamer\bin\librsvg-2-2.dll': 找不到指定的程序。
[INFO   ] [GL          ] NPOT texture support is available

I'm pretty sure there are libass-9.dll,libgstassrender.dll and other dlls  in the path of
 C:\Python27\share\gstreamer\bin:
I also downloaded gstreamer from https://gstreamer.freedesktop.org/data/pkg/windows/1.14.4/ and put int to my python share folder,but,it's still not work.
# this is my code:
File name:kivyplayer.py

from kivy.app import App

from kivy.uix.video import Video
class KivyPlayerApp(App):
	def build(self):
		self.video = Video()
		self.video.source = 'http://video.ted.com/talk/stream/2004/None/DanGilbert_2004-180k.mp4'
		self.video.bind(on_touch_down = self.touch_down)
		return self.video
	def touch_down(self,instance,touch):
		if self.video.state == 'play':
			self.video.state = 'pause'
		else:
			self.video.state = 'play'
		if touch.is_double_tap:
			self.video.state ='stop'

if __name__=='__main__':
	KivyPlayerApp().run()

**Comment by alidalee** [comment] 2018-12-10 15:47
I reinstalled kivy in my another pc(win 7) with python 2.7.15. then run the example kivycatalog,also recived the gsstreamer warning.

Here is packages I've installed.
Package             Version
------------------- ----------
certifi             2018.11.29
chardet             3.0.4
docutils            0.14
idna                2.7
Kivy                1.10.1
Kivy-examples       1.10.1
Kivy-Garden         0.1.4
kivy.deps.glew      0.1.10
kivy.deps.gstreamer 0.1.13
kivy.deps.sdl2      0.1.18
pip                 18.1
Pygments            2.3.0
pypiwin32           223
pywin32             224
requests            2.20.1
setuptools          40.6.2
urllib3             1.24.1
wheel               0.32.3

**Comment by dehole** [comment] 2019-01-23 14:59
I am also getting this error.  Here are my installed versions:

Package             Version
------------------- -----------
certifi             2018.11.29
chardet             3.0.4
Cython              0.29.3
Django              2.1.5
docutils            0.14
ffpyplayer          4.1.0
idna                2.8
image               1.5.27
Kivy                1.11.0.dev0
Kivy-examples       1.11.0.dev0
Kivy-Garden         0.1.4
kivy.deps.glew      0.1.10
kivy.deps.gstreamer 0.1.13
kivy.deps.sdl2      0.1.18
numpy               1.16.0
pandas              0.23.4
Pillow              5.4.1
pip                 19.0.1
Pygments            2.3.1
pypiwin32           223
pyserial            3.4
python-dateutil     2.7.5
pytz                2018.9
pywin32             224
requests            2.21.0
setuptools          40.6.3
six                 1.12.0
urllib3             1.24.1
wheel               0.32.3

**Comment by tgytr** [comment] 2019-01-26 16:11
I have exactly the same problem, that would be so helpful if there is any solution.

**Comment by tito** [comment] 2019-02-12 23:25
Duplicate of #5916

**Closed by tito** 2019-02-12 23:25 UTC
