### ISSUE TITLE
On Andriod build cant display Number Pad Keyboard

### ISSUE THREAD

**Issue by nim4ka** [kivy/kivy#5771] opened 2018-05-24 18:33 UTC
### Versions
* Python: 3.6 
* OS: win10 
* Kivy: 1.10.0
* Kivy installation method: Build on VM

### Description

I Have problem with TextInput i set property s like this -->

TextInput:
                input_filter : 'float'
                input_type : 'number'
                multiline: False

But in andriod when click in Text Put Display Full charecter keyboard , i wanna  Just Numberic Keypad when touch Text input and i'm searching for 3 days and cant find any thing 
thanks for answer

**Comment by nim4karimi** [comment] 2018-05-24 18:34
![whatsapp image 2018-05-24 at 10 59 56 pm](https://user-images.githubusercontent.com/10053631/40504533-bf0641e0-5fa6-11e8-97a8-5546731f50df.jpeg)

**Comment by bionoid** [comment] 2018-05-24 18:56
The problem is described at https://github.com/kivy/python-for-android/issues/796, I don't think any progress has been made in sdl2 to address this. There is an [example of using custom keyboard](https://github.com/kivy/kivy/tree/master/examples/keyboard) included with kivy; that's probably the easiest workaround for now

**Comment by bionoid** [comment] 2018-05-24 19:36
Sorry, I have never used the vkeyboard stuff, my best suggestion is to study the linked example

**Comment by eteamin** [comment] 2018-05-24 20:48
@nim4karimi 
https://github.com/kivy/kivy/blob/master/examples/keyboard/main.py#L180 this helps?

**Comment by nim4karimi** [comment] 2018-05-25 14:16
@eteamin I can not understand it at all. can you tell me how can handle this ? 
i have 3 input and need Keyboard number when touch that all i need to solve and finish my job

**Comment by tshirtman** [comment] 2021-03-27 21:40
This has been fixed in p4a.

**Closed by tshirtman** 2021-03-27 21:40 UTC
