### ISSUE TITLE
Pong tutorial code doesn't resize canvas when user resizes window

### ISSUE THREAD

**Issue by kalinalinkalina** [kivy/kivy#5669] opened 2018-03-21 20:23 UTC
### Versions

* Python: 2.7.13
* OS: CentOS 
* Kivy: 1.10.0
* Kivy installation method: pip install kivy

### Description

I copied both the main.py and pong.kv code from the end of https://kivy.org/docs/tutorials/pong.html . When I run "python main.py" the game starts and seems to work. However, when I resize the window, the canvas remains the same size. The tutorial text explicitly calls out "Try to resize the application window and notice what happens. That’s right, the entire UI resizes automatically" - but it does not.

**Comment by bionoid** [comment] 2018-03-21 20:34
That's weird, UI should resize.. Please provide the startup log (run `python pong.py`, resize window, close app then copy everything). Plus a screenshot of the resized window would maybe provide some clues.

**Comment by kalinalinkalina** [comment] 2018-03-21 20:38
Startup log:

```
[kalina@theviz pong]$ python main.py
[INFO   ] [Logger      ] Record log in /home/kalina/.kivy/logs/kivy_18-03-21_32.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <4.5.0 NVIDIA 375.39>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <Quadro K4000/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <4.50 NVIDIA>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
size hint is[1, 1]
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

Screenshot:
![pong](https://user-images.githubusercontent.com/1111649/37736049-d51eb824-2d1d-11e8-8696-da9bf72f86b5.png)

**Comment by bionoid** [comment] 2018-03-21 20:57
```
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
```

Pygame window provider is depreacted / no longer maintained, using it is almost certainly the cause of the problem (you should be using sdl2). [Here are some old notes on building for CentOS](https://github.com/bionoid/kivy/commit/5795ce80388d7ff4f257c7c4745edfa4ef1877d7#diff-983769ad8b9958abb0c57e4a7ba349e4), and the related [sdl2_from_source.txt](https://github.com/bionoid/kivy/commit/5795ce80388d7ff4f257c7c4745edfa4ef1877d7#diff-424eacf08d0ffac7c135f0dd50c39776).

There were some extra steps with pkg-config etc required for sdl2 when I did this, but you may have a newer version where these libraries can be installed from package manager..

**Comment by inclement** [comment] 2018-03-21 21:34
I'm closing this due to the pygame issue bionoid explained. If this happens with sdl2 as well, just let us know and I'll reopen it.

**Closed by inclement** 2018-03-21 21:34 UTC

**Comment by tom-ek** [comment] 2020-07-04 01:31
I know this is two years later down the road, but if  anybody runs into this issue as well, I can confirm that the resizing issue 
comes from not using SDL2.

See below what one needs to do to save time.

Execute the following in your terminal. If you use a virtual environment, make sure you activate it first.

```
#Uninstall kivy
pip uninstall kivy

#install sdl2
sudo apt install libsdl2-dev libsdl2-2.0-0

#install sdl image
sudo apt install libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0

#install sdl mixer
sudo apt install libmikmod-dev libfishsound1-dev libsmpeg-dev liboggz2-dev libflac-dev libfluidsynth-dev libsdl2-mixer-dev libsdl2-mixer-2.0-0

#install sdl true type fonts
sudo apt install libfreetype6-dev libsdl2-ttf-dev libsdl2-ttf-2.0-0

#Install kivy
pip install kivy
```

Now you should be good to go and widgets should resize automatically when the main window is resized.
