### ISSUE TITLE
kivy.graphics.instructions.RenderContext.set_texture calling removed function

### ISSUE THREAD

**Issue by Michael-F-Bryan** [kivy/kivy#4336] opened 2016-05-30 08:12 UTC
It looks like `kivy.graphics.instructions.RenderContext.set_texture` is calling a function that has been removed from `Pillow`. The error message says that `tostring()` is being called, but that it was removed and you should call `tobytes()` instead.

Relevant version numbers:
- Pillow: 3.2.0
- Kivy: 1.9.1
## Traceback

 Exception ignored in: 'kivy.graphics.instructions.RenderContext.set_texture'
 Traceback (most recent call last):
   File "kivy/graphics/texture.pyx", line 786, in kivy.graphics.texture.Texture.bind (/tmp/pip-build-znaq60mb/kivy/kivy/graphics/texture.c:9935)
   File "/usr/lib/python3.5/site-packages/kivy/core/text/**init**.py", line 628, in _texture_fill
     self.render(real=True)
   File "/usr/lib/python3.5/site-packages/kivy/core/text/__init__.py", line 573, in render
     return self._render_real()
   File "/usr/lib/python3.5/site-packages/kivy/core/text/__init__.py", line 559, in _render_real
     data = self._render_end()
   File "/usr/lib/python3.5/site-packages/kivy/core/text/text_pil.py", line 57, in _render_end
     self._pil_im.mode.lower(), **self._pil_im.tostring()**)
   File "/usr/lib/python3.5/site-packages/PIL/Image.py", line 699, in tostring
     "Please call tobytes() instead.")
 Exception: tostring() has been removed. Please call tobytes() instead.

**Comment by muodov** [comment] 2016-06-02 17:59
While this definitely needs a fix, it seems that in most cases kivy tries to use sdl2 on most platforms, so I would suggest trying to install those libsdl2-* system libraries (see installation notes in docs), and then reinstall kivy. Chances are, kivy will pick up sdl2 and use that for rendering instead of PIL.
This "solved" a problem on my Raspberry Pi.

**Comment by Julian-O** [comment] 2023-11-09 09:15
According to GIT Blame this was fixed in Jan 2016, before this issue was raised.

Closing, but if the problem is still occurring, let us know.

**Closed by Julian-O** 2023-11-09 09:15 UTC
Labels: Component: graphics, Type: Bug
