### ISSUE TITLE
ANGLE not working with VM/Citrix ?

### ISSUE THREAD

**Issue by jimanvlad** [kivy/kivy#4971] opened 2017-02-02 08:46 UTC
Hi,

@dessant 's comment on https://github.com/kivy/kivy/pull/4385#issuecomment-276706707, When kivy is set to use the ANGLE backend (os.environ['KIVY_GL_BACKEND'] = 'angle_sdl2'), OpenGL 2.0 should not be enforced.

Here's my log with a recent nightly build:
```
[INFO   ] [Kivy        ] v1.9.2.dev0, git-309ac12, 20170201
[INFO   ] [Python      ] v3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
**[INFO   ] [Window      ] Activate GLES2/ANGLE context**
[INFO   ] [GL          ] Using the "OpenGL" graphics system
**[INFO   ] [GL          ] Backend used <angle_sdl2>**
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 NVIDIA 361.91'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVS 510/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 2
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 3.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[WARNING] [Call to deprecated function __init__ in P]\Miniconda\envs\conda36\lib\site-packages\kivy\uix\listview.py line 846.Called from P:/TS Projects/Document Classification/main.py line 289 by EmailsList().
[WARNING] [Call to deprecated function __init__ in P]\Miniconda\envs\conda36\lib\site-packages\kivy\adapters\adapter.py line 112.Called from P:\Miniconda\envs\conda36\lib\site-packages\kivy\adapters\simplelistadapter.py line 54 by __init__().
[WARNING] [Call to deprecated function __init__ in P]\Miniconda\envs\conda36\lib\site-packages\kivy\uix\abstractview.py line 43.Called from P:\Miniconda\envs\conda36\lib\site-packages\kivy\uix\listview.py line 866 by __init__().
[INFO   ] [GL          ] NPOT texture support is available
```
The problem is not on this PC where my application works.

The problem is on another PC with an integrated graphics card where it says that Open GL 1.1. is not good enough for my program to run, and that there is a minimum requirement for 2.0.

Is there any way to bypass this OpenGL check?

**Comment by jimanvlad** [comment] 2017-02-02 09:33
PC with OpenGL Problem:

```
[INFO   ] [Kivy        ] v1.9.2.dev0, git-309ac12, 20170201
[INFO   ] [Python      ] v3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [Window      ] Activate GLES2/ANGLE context
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - RuntimeError: b'Could not initialize EGL'
```

**Comment by dessant** [comment] 2017-02-02 09:58
I think the cause of your [error](https://github.com/kivy/kivy/issues/4971#issuecomment-276909025) is different, you'd have to see this message: https://github.com/kivy/kivy/blob/835feab00d35a5ea24032c88118d1c8ebb9d6f1c/kivy/core/gl/__init__.py#L61

If your're not getting that message, open a new issue so we don't mix things.

**Comment by jimanvlad** [comment] 2017-02-02 10:00
Hi, I do see that message popup in a window, I just didn't get time to attach a screenshot.

**Comment by dessant** [comment] 2017-02-02 10:03
@matham, @tito: should `MIN_REQUIRED_GL_VERSION` be (1, 1) when angle is being used?

**Comment by matham** [comment] 2017-02-02 19:24
Duuno, it will need to be tested. @jimanvlad can you play with the code to see if removing that check works?

**Comment by jimanvlad** [comment] 2017-02-03 09:03
Hi,

So I changed `MIN_REQUIRED_GL_VERSION` to `(1, 1)`. Now I don't get the GUI pop-up with the error, but it still crashes with the following error in the console:

```
[INFO   ] [Logger      ] Record log in C:\Users\jimanv\.kivy\logs\kivy_17-02-03_0.txt
[INFO   ] [Kivy        ] v1.9.2.dev0, git-309ac12, 20170201
[INFO   ] [Python      ] v3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <thread> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [Window      ] Activate GLES2/ANGLE context
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
sdl2 - RuntimeError: b'Could not initialize EGL'
  File "\\ubsprod.msad.ubs.net\UserData\JIMANV\Home\Miniconda\envs\conda36\lib\site-packages\kivy\core\__init__.py", line 67, in core_select_lib
    cls = cls()
  File "\\ubsprod.msad.ubs.net\UserData\JIMANV\Home\Miniconda\envs\conda36\lib\site-packages\kivy\core\window\window_sdl2.py", line 139, in __init__
    super(WindowSDL, self).__init__()
  File "\\ubsprod.msad.ubs.net\UserData\JIMANV\Home\Miniconda\envs\conda36\lib\site-packages\kivy\core\window\__init__.py", line 845, in __init__
    self.create_window()
  File "\\ubsprod.msad.ubs.net\UserData\JIMANV\Home\Miniconda\envs\conda36\lib\site-packages\kivy\core\window\window_sdl2.py", line 263, in create_window
    self.fullscreen, resizable, state)
  File "kivy\core\window\_window_sdl2.pyx", line 142, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy\core/window\_window_sdl2.c:2780)
  File "kivy\core\window\_window_sdl2.pyx", line 57, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy\core/window\_window_sdl2.c:1871)
```

What else can I try? Very keen to get this sorted.

**Comment by matham** [comment] 2017-02-03 19:15
I think you may need to adjust your expectation here. I don't think chances
are high that it'll ever work since until now gl 2.0 was a basic hardware
prerequisite for kivy.

@dessant I'm not sure where the idea that angle wouldn't require 2.0 gl
came from?

In any case, what is your system? What does dxdiag say is your GPU and
opengl version?

**Comment by dessant** [comment] 2017-02-03 19:36
@matham, @tito talked about using angle on a win10 pc with gl 1.1.

**Comment by dessant** [comment] 2017-02-03 19:45
> works starting Direct3d 9 support (use dxdiag to find out)
https://github.com/kivy/kivy/pull/4343#issue-157560081

**Comment by jimanvlad** [comment] 2017-02-03 21:06
[System](https://d17oy1vhnax1f7.cloudfront.net/items/2J1N340M1E363a181n0w/Screenshot_2017-02-03%2021.05.02_aqKpGS.png)
[Display](https://d17oy1vhnax1f7.cloudfront.net/items/061X0n1X1C402o1E2F13/Screenshot_2017-02-03%2021.05.28_w4e7pP.png)

**Comment by matham** [comment] 2017-02-03 21:16
I notice it's a vm. Try doing the answers from https://stackoverflow.com/questions/18258386/qtquick-application-wont-run-on-vmware-virtual-machine.

**Comment by tito** [comment] 2017-02-03 23:00
If Angle have acceleration working, the exposed glass version works. No need to change to 1. Angle correctly show which opengl version it support :) 

So yes, root issue is somewhere else. Which d3d compiler have you provided?

**Comment by tito** [comment] 2017-02-03 23:35
Actually, it's not about the compiler. Here is my log when no d3d compiler are provided on my Windows 7 VM using virtualbox:

![selection_186](https://cloud.githubusercontent.com/assets/37904/22612541/9f9d27e8-ea71-11e6-8497-e0436dbbabb4.png)

With the d3dcompiler_47.dll provided, i don't have any issue. Here is my dxdiag display information. 

![selection_185](https://cloud.githubusercontent.com/assets/37904/22612545/a71cb614-ea71-11e6-8edc-9a55507e3afa.png)

Even if Direct3D acceleration is activated on your side, maybe there is missing thing to get ANGLE working. I notice you don't use the Virtualbox directX driver, but citrix. Maybe that's the issue?

**Comment by jimanvlad** [comment] 2017-02-03 23:39
So this is the company provided VM (it works on the PCs, but not in the VMs). What should I test next?

**Comment by tito** [comment] 2017-02-04 00:05
I would like to first understand if it's Kivy only, or more extended to other software as well. Do you have WebGL working on Firefox or Chrome for example?

**Comment by jimanvlad** [comment] 2017-02-06 10:46
Hi,

On both machines (the one where Kivy works, and the virtual machine where Kivy doesn't work), I get the same result using the http://webglreport.com/ tester: WebGL 1 works and WebGL 2 doesn't. Given that the result is the same on both machines, I'm not sure this get us any closer to the answer. 

What else could it be?

Vlad

**Comment by jimanvlad** [comment] 2017-02-06 11:15
Hi,

I've done tests on both machines. here are the differences:

Notable points:

1. Both machines have ANGLE: N
2. The virtual machine has the following flag: Major Performance Caveat: Yes
3. The virtual machine has Unmasked Renderer: Microsoft Basic Render Driver whereas the normal PC has NVIDIA NVS 510 *the gfx card).
4. WebGL 1 seems to work in Internet Explorer on the virtual machine, but not in Chrome...


**Internet Explorer on the machine where Kivy works:**
**WebGL 1:** 
```
Platform:
Win32 

Browser User Agent:
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; MS-RTC LM 8; rv:11.0) like Gecko 

Context Name:
experimental-webgl 
GL Version:WebGL 0.94 
Shading Language Version:WebGL GLSL ES 0.94 
Vendor:Microsoft 
Renderer:Internet Explorer 
Unmasked Vendor:Microsoft 
Unmasked Renderer:NVIDIA NVS 510 
Antialiasing:
Available 
ANGLE:No 
Major Performance Caveat:No 
Vertex Shader
Max Vertex Attributes:16 
Max Vertex Uniform Vectors:512 
Max Vertex Texture Image Units:16 
Max Varying Vectors:15 
Best float precision:[-2127, 2127] (23) 
Transform Feedback
Coming in WebGL 2 
Rasterizer
Aliased Line Width Range:[1, 1] 
Aliased Point Size Range:[1, 300] 
Fragment Shader
Max Fragment Uniform Vectors:512 
Max Texture Image Units:16 
float/int precision:highp/highp 
Best float precision:[-2127, 2127] (23) 
Framebuffer
Max Color Buffers:1 
RGBA Bits:[8, 8, 8, 8] 
Depth / Stencil Bits:[24, 8] 
Max Render Buffer Size:16384 
Max Viewport Dimensions:
[16384, 16384] 
Textures
Max Texture Size:16384 
Max Cube Map Texture Size:16384 
Max Combined Texture Image Units:32 
Max Anisotropy:16 
Uniform Buffers
Coming in WebGL 2 
Supported Extensions:
 WEBGL_compressed_texture_s3tc  
 OES_texture_float  
 OES_texture_float_linear  
 EXT_texture_filter_anisotropic  
 OES_standard_derivatives  
 ANGLE_instanced_arrays  
 OES_element_index_uint  
 WEBGL_debug_renderer_info  
```

**Internet Explorer on the machine where Kivy works:**
**WebGL 2:** 
```
 This browser does not support WebGL 2
Check out Get WebGL, or try installing the latest version of Chrome, or Firefox. 
```

**Chrome on the machine where Kivy works:**
**WebGL 1:** 
```
Platform:	Win32
Browser User Agent:	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Context Name:	webgl
GL Version:	WebGL 1.0 (OpenGL ES 2.0 Chromium)
Shading Language Version:	WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor:	WebKit
Renderer:	WebKit WebGL
Unmasked Vendor:	Google Inc.
Unmasked Renderer:	ANGLE (NVIDIA NVS 510 Direct3D11 vs_5_0 ps_5_0)
Antialiasing:	Available
ANGLE:	Yes, D3D11
Major Performance Caveat:	No
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	1024
Max Vertex Texture Image Units:	16
Max Varying Vectors:	30
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2
Rasterizer
Aliased Line Width Range:	[1, 1]
Aliased Point Size Range:	[1, 1024]
Fragment Shader
Max Fragment Uniform Vectors:	1024
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	8
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	16384
Max Viewport Dimensions:	[16384, 16384]
Textures
Max Texture Size:	16384
Max Cube Map Texture Size:	16384
Max Combined Texture Image Units:	32
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2
Supported Extensions:
ANGLE_instanced_arrays
EXT_blend_minmax
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
```

**Chrome on the machine where Kivy works:**
**WebGL 2:** 
```
This browser does not support WebGL 2
Check out Get WebGL, or try installing the latest version of Chrome, or Firefox.
```

**Internet Explorer on the machine where Kivy doesn't work:**
**WebGL 1:** 

```
Platform:	Win32
Browser User Agent:	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko
Context Name:	experimental-webgl
GL Version:	WebGL 0.94
Shading Language Version:	WebGL GLSL ES 0.94
Vendor:	Microsoft
Renderer:	Internet Explorer
Unmasked Vendor:	Microsoft
Unmasked Renderer:	Microsoft Basic Render Driver
Antialiasing:	Available
ANGLE:	No
Major Performance Caveat:	Yes
Vertex Shader
Max Vertex Attributes:	16
Max Vertex Uniform Vectors:	512
Max Vertex Texture Image Units:	16
Max Varying Vectors:	15
Best float precision:	[-2127, 2127] (23)
Transform Feedback
Coming in WebGL 2 
Rasterizer
Aliased Line Width Range:	[1, 1]
Aliased Point Size Range:	[1, 300]
Fragment Shader
Max Fragment Uniform Vectors:	512
Max Texture Image Units:	16
float/int precision:	highp/highp
Best float precision:	[-2127, 2127] (23)
Framebuffer
Max Color Buffers:	1
RGBA Bits:	[8, 8, 8, 8]
Depth / Stencil Bits:	[24, 8]
Max Render Buffer Size:	16384
Max Viewport Dimensions:	[16384, 16384]
Textures
Max Texture Size:	16384
Max Cube Map Texture Size:	16384
Max Combined Texture Image Units:	32
Max Anisotropy:	16
Uniform Buffers
Coming in WebGL 2 

Supported Extensions:
	WEBGL_compressed_texture_s3tc 
	OES_texture_float 
	OES_texture_float_linear 
	EXT_texture_filter_anisotropic 
	OES_standard_derivatives 
	ANGLE_instanced_arrays 
	OES_element_index_uint 
	WEBGL_debug_renderer_info 
```

**Internet Explorer on the virtual machine:**
**WebGL 2:** 
```
This browser does not support WebGL 2
Check out Get WebGL, or try installing the latest version of Chrome, or Firefox.
```

**Chrome on the virtual machine:**
**WebGL 1:** 
```
This browser does not support WebGL 1
Check out Get WebGL, or try installing the latest version of Chrome, or Firefox.
```

**Chrome on the virtual machine:**
**WebGL 2:** 
```
This browser supports WebGL 1, but it is disabled or unavailable.
Sometimes this is the result of older video drivers being rejected by the browser. Try updating your video drivers if possible.
Also check out Get WebGL, or try installing the latest version of Chrome, or Firefox.
```

**Comment by misl6** [comment] 2017-02-07 11:04
I've got the same problem on an old Windows 7 netbook (so, not a VM)

`[INFO][Window] Provider: sdl2
[INFO][Window] Activate GLES2/ANGLE context
[CRITICAL] [Window] Unable to find any valuable Window Provider`

webglreport.com says that the browser ( Chrome ) supports WebGL 1 & WebGL 2 via ANGLE (Yes, D3D9)

**Comment by matham** [comment] 2017-02-07 17:11
@misl6 we need a full log as it may be a different issue.

**Comment by dessant** [comment] 2017-02-07 17:22
This issue might be related: https://github.com/kivy/kivy/issues/3576#issuecomment-277898559.

**Comment by jimanvlad** [comment] 2017-02-07 17:48
wxPython works in the virtual machine if that helps?

**Comment by misl6** [comment] 2017-02-08 08:58
@matham 

`
[INFO   ] Logger: Record log in C:\Users\pippo\.kivy\logs\kivy_17-02-08_1.txt
[INFO   ] Kivy: v1.9.2.dev0, git-57d41c9, 20170206
[INFO   ] Python: v3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)]
[INFO   ] Factory: 193 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] Window: Activate GLES2/ANGLE context
[CRITICAL] Window: Unable to find any valuable Window provider.
sdl2 - RuntimeError: b'Could not initialize EGL'
  File "D:\GitHub\mykivyapp\mykivyapp-kivy\venv3\lib\site-packages\kivy\core\__init__.py", line 67, in core_select_lib
    cls = cls()
  File "D:\GitHub\mykivyapp\mykivyapp-kivy\venv3\lib\site-packages\kivy\core\window\window_sdl2.py", line 139, in __init__
    super(WindowSDL, self).__init__()
  File "D:\GitHub\mykivyapp\mykivyapp-kivy\venv3\lib\site-packages\kivy\core\window\__init__.py", line 862, in __init__
    self.create_window()
  File "D:\GitHub\mykivyapp\mykivyapp-kivy\venv3\lib\site-packages\kivy\core\window\window_sdl2.py", line 268, in create_window
    self.fullscreen, resizable, state)
  File "kivy\core\window\_window_sdl2.pyx", line 142, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window (kivy\core/window\_window_sdl2.c:2781)
  File "kivy\core\window\_window_sdl2.pyx", line 57, in kivy.core.window._window_sdl2._WindowSDL2Storage.die (kivy\core/window\_window_sdl2.c:1872)

[DEBUG  ] App: Loading kv <.\mykivyapp.kv>
[DEBUG  ] MainRouter: Add route /
[DEBUG  ] MainRouter: Add route /login
[DEBUG  ] MainRouter: Add route /settings
[CRITICAL] App: Unable to get a Window, abort.
`

**Comment by jimanvlad** [comment] 2017-02-12 16:40
What else can we try @tito @dessant

**Comment by dessant** [comment] 2017-02-25 08:19
Issues on this topic seem to be derailed, one of them being https://github.com/kivy/kivy/issues/3576. This issue is also not about the angle backend only, @jimanvlad can't run kivy with the default backend either: https://github.com/kivy/kivy/pull/4385#issuecomment-276649326.

@jimanvlad, could you check if setting `Config.set('graphics', 'multisamples', '0')` *before* importing the rest of kivy solves your issue with the default gl backend? I'm wondering if you're experiencing #3576.

**Comment by dessant** [comment] 2017-02-25 08:24
I'll close this issue because my original assumption about us needing to relax the gl version when angle is being used was wrong: https://github.com/kivy/kivy/issues/4971#issue-204813011. If angle works, our gl version detection should return at least 2.0, even if the device does not support gl 2.0 (without angle).

Please open a new issue for the default backend if https://github.com/kivy/kivy/issues/4971#issuecomment-282469216 does not help.

**Closed by dessant** 2017-02-25 08:24 UTC

**Comment by matham** [comment] 2017-02-25 18:42
I think it'd be simplest to figure this out on #kivy on IRC. Please someone with such a problem join us there.

**Comment by anupamkayal** [comment] 2022-05-19 17:58
I wanted to learn more in kivy. But when I install kivy and run it ,it goes through the same error.I have opengl version 1.4.I have seen many blogs,articles,videos to bypass this problem.Now that I have fixed this, so I want to share my experience. In my case I setup User Environment variable KIVY_GL_BACKEND (variable name) AND sdl2 (variable value) . Then download this opengl dll file according to architecture(x86,x64) of your machine.Now paste the dll file where your python installed.Atleat uninstall kivy & reinstall it. Opengl dll file-- https://bit.ly/39Ep0du
