### ISSUE TITLE
Encoding file .kv in Windows

### ISSUE THREAD

**Issue by H1bertto** [kivy/kivy#5738] opened 2018-05-07 18:39 UTC
### Versions

* Python: 3.6.4
* OS: Windows 10
* Kivy: 1.10.0
* Kivy installation method: Follow your step by step in: https://kivy.org/docs/installation/installation-windows.html

### Description

I have identified an error using this characters in a String: çáàãâäéèêëíìîïóòõôöúùûü
In Windows, there is a problem when using the open (file, 'type') function, it does not open with default encoding "utf-8", so it is necessary to set  encoding='utf-8'  in the function.
For all OS to open without problem, just replace in:
kivy > lang > builder.py > line 288
From:
open (filename, 'r')
To:
open (filename, 'r', encoding='utf-8')

### Code and Logs

```python

# the old line
with open(filename, 'r') as fd:
# the new line
with open(filename, 'r', encoding='utf-8') as fd:

```

**Comment by dolang** [comment] 2018-05-07 18:47
That's not an error. By design, Python uses the system's preferred character encoding when opening files. On Windows that happens to be Win-1252 (`cp1252`).

You can check what encoding your file has been opened with through `f.encoding`.

But yeah, I recommend you always use `open(file, encoding='utf-8')` unless you're doing some quick script or the like where it doesn't matter.

That's not a Kivy bug, however.

**Comment by Julian-O** [comment] 2023-11-06 02:38
I believe this has now been carried out - UTF-8 is the new default.

Closing as completed. If the problem is still happening, please let us know.

**Closed by Julian-O** 2023-11-06 02:38 UTC
