### ISSUE TITLE
ColorPicker: Bugs and Improvement

### ISSUE THREAD

**Issue by thica** [kivy/kivy#2842] opened 2015-01-11 18:49 UTC
I played a little around with the colorpicker widgets and found some issues:

- It is not possible to select a "pure" rgb color (eg pure red (255,0,0) with the color wheel
- if you bind "color" (as documeneted) you get multiple notifications fired, if you touch the colorwheel. If you have intensive operations on a color change, only one notification should get fired when the color is complete calculated

Improvement requests:
Add parameter to show only the wheel or only the input fields

**Comment by merriam** [comment] 2015-03-07 06:19
Fixing the 'pure' rgb color problem.  It was a conversion error down in utils.py.

**Comment by tshirtman** [comment] 2015-03-07 09:55
2) is not a bug, i would say, if you want to only trigger your calculation once, don't bind color directly, bind to some validation button, and trigger the calculation when it's hitten.

**Comment by FeralBytes** [comment] 2015-03-07 16:30
2) I agree because a change to this behavior could negatively affect others that expect this behavior. The workaround as suggested by @tshirtman is better than changing existing functionality.

**Comment by Kovak** [comment] 2015-03-07 17:48
This sounds like it my be a perfect case for a clock trigger. Bind a trigger to the color property, and this will result in the triggered logic only being called once per clock frame at most.

**Comment by merriam** [comment] 2015-03-09 19:09
For the first problem, it's in PR #3112, this commit.  https://github.com/merriam/kivy/commit/513fd31fd4aacf27f1054181865722d2ebb4c5e7

Since my commits won't get merged, someone may wish to submit this.

**Comment by thica** [comment] 2015-03-10 07:13
Hello all, back from hols.
1) I still think, it is not right to get multiple notifications on a click on the wheel. And I don't think that somebody is expecting it...
2)  @Kovak: Thanks for the tip, will try it

**Closed** 2015-03-21 14:41 UTC
