### ISSUE TITLE
stackoverflow during logging

### ISSUE THREAD

**Issue by matthiasharrer** [kivy/kivy#7585] opened 2021-07-27 12:45 UTC
**Software Versions**
* Python: 3.7.5
* OS: Linux
* Kivy: master (53502b7942155dbae96efa3a9e469fe24db90533)
* Kivy installation method: pip

**Describe the bug**
Since #7173 introduced a deepcopy in the (colored) logger format I am getting a stackoverflow on certain Exceptions (specifically a AioRpcError from grpc). I think logging an error should never result in a stackoverflow. 

**Expected behavior**
The exception is logged correctly.

**To Reproduce**
Actually I am not sure what exactly causes copy.deepcopy to fail on this error. I can try to provide an example if that really matters, but I am pretty sure that deepcopy in combination with certain Exceptions is the problem.

**Additional context**
Additionally the deepcopy could be quite expensiv if it does not produce a stackoverflow .. Looking at the properties that are actually changed in the format function a shallow copy should actually be good enough.

What are your opinions on this?

**Comment by Davidy22** [comment] 2021-08-04 17:46
A code example would be very helpful for fixing this, can make an attempt if you can provide one.

**Comment by matthiasharrer** [comment] 2021-08-12 12:17
I tried building a minimal example but did not succeed so far.
It might only occur with some other log configuration and global exception handlers I am using.

I will try to come back to this with a working example later .. until then this: https://github.com/oneclickmetal/kivy/commit/5e762f96b108e70d76349da5ca749fb73ddfbe0d fixes it for me ..

**Comment by carstenfuchs** [comment] 2022-01-29 10:43
The deepcopy was introduced to solve #7062 
Imho, the proper and sustainable solution to this was to not have so many side effects from `import kivy` as described in #7172.

**Comment by matthiasharrer** [comment] 2022-01-31 08:44
I tried reproducing it but wasn't able to come up with a minimal example unfortunately.
Instead of the shallow copy I just manually picked the non colored logger which does not have this problem.

But I totally agree that it would be nice to have more control over what side affects kivy produces when being imported.

**Comment by Julian-O** [comment] 2022-08-13 20:34
This is pretty much a duplicate of #7528.

I have some code that solves this in the pipeline. It doesn't address the bigger picture of the side-effects upon import.

**Comment by misl6** [comment] 2022-08-24 07:54
Should have been fixed via https://github.com/kivy/kivy/pull/7962, feel free to re-open the issue if it persists.

**Closed by misl6** 2022-08-24 07:54 UTC
