### ISSUE TITLE
When using 'app' from a .kv file, AttributeError: 'NoneType' object has no attribute 'bind'

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [kivy/kivy#3384] opened 2015-05-26 03:45 UTC
Like the title says, any reference to the main app from within the .kv file raises `AttributeError: 'NoneType' object has no attribute 'bind'`

Here's a sample of my code:

```
#:kivy 1.9.0

<LoginScreen>:
    GridLayout:
        rows: 2
        Label:
            text: 'Login:'
        GridLayout:
            cols: 2
            Label:
                text: 'Username:'
            TextInput:
                multiline: False
                text: app.getUsername()
            Label:
                text: 'Password:'
            TextInput:
                multiline: False
                password: True
```

```
class TestApp(App):
    def getUsername():
        return 'asdf'
    def build(self):
        return sm
```

and the traceback:

```
[INFO   ] [Logger      ] Record log in /home/james/.kivy/logs/kivy_15-05-25_20.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 10.1.3'>
[INFO   ] [GL          ] OpenGL vendor <b'X.Org'>
[INFO   ] [GL          ] OpenGL renderer <b'Gallium 0.4 on AMD CAICOS'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1649, in create_handler
     return eval(value, idmap)
   File "test.kv", line 14, in <module>
     text: app.getUsername()
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 857, in __getattribute__
     object.__getattribute__(self, '_ensure_app')()
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 852, in _ensure_app
     app.bind(on_stop=lambda instance:
 AttributeError: 'NoneType' object has no attribute 'bind'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2011, in _apply_rule
     value, rule, rctx['ids'])
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1654, in create_handler
     cause=tb)
 kivy.lang.BuilderException: Parser: File "test.kv", line 14:
 ...
      12:           TextInput:
      13:               multiline: False
 >>   14:               text: app.getUsername()
      15:           Label:
      16:               text: 'Password:'
 ...
 AttributeError: 'NoneType' object has no attribute 'bind'
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1649, in create_handler
     return eval(value, idmap)
   File "test.kv", line 14, in <module>
     text: app.getUsername()
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 857, in __getattribute__
     object.__getattribute__(self, '_ensure_app')()
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 852, in _ensure_app
     app.bind(on_stop=lambda instance:


 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "./main.py", line 20, in <module>
     sm.add_widget(LoginScreen(name='login'))
   File "/usr/lib/python3/dist-packages/kivy/uix/relativelayout.py", line 255, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "/usr/lib/python3/dist-packages/kivy/uix/floatlayout.py", line 66, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/usr/lib/python3/dist-packages/kivy/uix/layout.py", line 66, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/usr/lib/python3/dist-packages/kivy/uix/widget.py", line 271, in __init__
     Builder.apply(self)
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2018, in _apply_rule
     e), cause=tb)
 kivy.lang.BuilderException: Parser: File "test.kv", line 14:
 ...
      12:           TextInput:
      13:               multiline: False
 >>   14:               text: app.getUsername()
      15:           Label:
      16:               text: 'Password:'
 ...
 BuilderException: Parser: File "test.kv", line 14:
 ...
      12:           TextInput:
      13:               multiline: False
 >>   14:               text: app.getUsername()
      15:           Label:
      16:               text: 'Password:'
 ...
 AttributeError: 'NoneType' object has no attribute 'bind'
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1649, in create_handler
     return eval(value, idmap)
   File "test.kv", line 14, in <module>
     text: app.getUsername()
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 857, in __getattribute__
     object.__getattribute__(self, '_ensure_app')()
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 852, in _ensure_app
     app.bind(on_stop=lambda instance:

   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 2011, in _apply_rule
     value, rule, rctx['ids'])
   File "/usr/lib/python3/dist-packages/kivy/lang.py", line 1654, in create_handler
     cause=tb)
```
##

**Comment by JamesTheAwesomeDude** [comment] 2015-05-26 03:47
In lieu of `app.getUsername()`, I also tried:

* `str(7)` (succeeded)
* `repr(type(self))` (succeeded)
* `repr(type(app.getUsername))` (failed)
* `repr(type(app))` (failed)

This is what led to my conclusion that references to `app` are what's crashing Kivy.

**Comment by JamesTheAwesomeDude** [comment] 2015-05-26 04:06
`repr(type(app))` is `"<class 'kivy.lang.ProxyApp'>"`, so I suspect that the app isn't initialized early enough or something like that..

**Comment by ZurMaD** [comment] 2019-12-16 05:54
Same error (below)

![image](https://user-images.githubusercontent.com/28235457/70882621-58015e80-1f9e-11ea-94d5-454590c30c81.png)

When I'm trying to compile these lines. (.kv file)
![image](https://user-images.githubusercontent.com/28235457/70882657-72d3d300-1f9e-11ea-9a16-ae7a7aae9673.png)
With the Builder (.py file)
![image](https://user-images.githubusercontent.com/28235457/70882685-8717d000-1f9e-11ea-9aab-ae63c365bc1d.png)
The (.py file) is called by the main.py (fail).
When compile just the (.py) success.

**Comment by ZurMaD** [comment] 2019-12-16 06:02
Fixed using variable instead of reference
![image](https://user-images.githubusercontent.com/28235457/70883032-b8dd6680-1f9f-11ea-990a-305e39bb4725.png)

**Comment by Julian-O** [comment] 2023-11-13 16:19
Is this still happening on Kivy 2.2.1? Can you provide a complete small program that demonstrates the problem?

**Comment by ElliotGarbus** [comment] 2023-11-13 18:13
@Julian-O This is not a bug, this was a user error.  This can be closed.
In the original issue, the definition of the class method the self parameter was not included, resulting in the error.

Here is a simple reproducer:
```python
from kivy.app import App
from kivy.lang import Builder

kv = """
BoxLayout:
    TextInput:
        text: app.with_self()
    TextInput: 
        text: app.without_self()
"""

class A3384App(App):
    def build(self):
        return Builder.load_string(kv)

    def with_self(self):
        return 'works as expected'

    def without_self():
        return 'throws exception'

A3384App().run()
```

**Comment by Julian-O** [comment] 2023-11-13 23:34
@ElliotGarbus: Nice spot!

That gives me `TypeError: A3384App.without_self() takes 0 positional arguments but 1 was given` which is a much more appropriate error message than `AttributeError: 'NoneType' object has no attribute 'bind'`, but I assume that has changed with Kivy and Python upgrades.

Closing, but if the problem still occurs after solving this problem, please let us know.

**Closed by Julian-O** 2023-11-13 23:34 UTC
Labels: awaiting-reply
