### ISSUE TITLE
Svg

### ISSUE THREAD

**Issue by jhay06** [kivy/kivy#8408] opened 2023-10-16 00:55 UTC
any update on SVG support ? 

using kivy.graphics.svg is very limited 

i can load SVG on there but rendering is not good, image is too sharp 
can't scale or resize ,  setting width or height has no effect. 

for mobile apps , SVG or webp is prefer because of difference in screen on every devices , so png/jpg is not good for mobile app for displaying images 

hope that this component will fix. 
do you have any alternative way to show SVG on kivy ?

**Comment by baseplate-admin** [comment] 2023-10-16 01:04
Possibly related to https://github.com/kivy/kivy/issues/8333

**Comment by HinTak** [comment] 2023-10-17 19:35
@baseplate-admin not quite. @jhay06 specifically wants svg on android/ios .  #8333 is about Windows. (And skia python's svg rendering on Windows is okay)

**Comment by baseplate-admin** [comment] 2023-10-17 20:40
> specifically wants svg on android/ios 

The issue exists on andriod ( tested by me ) in the same way it exists on windows

**Comment by Julian-O** [comment] 2023-10-29 16:13
Closing as duplicate of #8333. If this is in error, please let us know.

**Closed by Julian-O** 2023-10-29 16:13 UTC
