### ISSUE TITLE
Packaging Issues on OsX BigSur related to `pushd dir`

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#7411] opened 2021-03-09 07:32 UTC
**Software Versions**
* Python: 3.x
* OS: MacOs
* Kivy: 2.0
* Kivy installation method: Kivy.app or PyInstaller or pip

**Describe the bug**
 
Apps packaged through Kivy.app and PyInstaller both have issues with paths not being setup properly.

With Kivy.app the `script` is not able to activate the packaged `venv` properly therefore not being able to import common packages like Kivy or docutils that are not able to be imported.

With PyInstaller the packaged data files are present in the correct path as packaged but when running on a target machine the dir supposed to be setup in path does not properly get setup.

Both issues are related to proper setting up of path. Most probably from what I could figure out one of the `pushd dir` commands don't seem to work as expected.

**Expected behavior**
Packaged app should work without 

**To Reproduce**
Package app using `Kivy-sdk-packager` or through `pyinstaller` for osx. Try to run the packaged app on a clean/new/separate machine than the packaging machine.

**Comment by matham** [comment] 2021-03-14 17:15
Should be fixed with https://github.com/kivy/kivy-sdk-packager/pull/62. And also is a duplicate of that linked issue.

**Closed by matham** 2021-03-14 17:15 UTC
