### ISSUE TITLE
MDTextField rtl , persian,arabic writing

### ISSUE THREAD

**Issue by OdzOdz** [kivy/kivy#8516] opened 2023-12-17 17:24 UTC
kv='''
MessagesBox:
      font_script_name:'Arab'
      base_direction:'rtl'
      font_name: '*rtl support  font*'
'''

class MessagesBox(MDTextField):
    str = StringProperty()
    def __init__(self, *args,**kwargs):
        super().__init__(*args,**kwargs) 
        self.selected_all=False   
    def insert_text(self, substring, from_undo=False,*args):
        super().insert_text(substring, from_undo=False,*args)
        self.selected_all=False
        if not from_undo and (len(self.str) + len(substring) > self.max_text_length):
            return
        col, row = self.cursor
        text = self._lines[row][:col]
        text_width= self._get_text_width(text,self.tab_width,self._label_cached)
        width = self.width - (self.padding[2]+self.padding[0]+50)
        if text_width >=width:
            self.str=self.str+'\n'  
        self.str=self.str+substring  
        self.text = get_display(self.str)  
        
    
    def _cut(self, data,*args):
        super()._cut(data,*args)
        data=get_display(data)
        self._ensure_clipboard()
        Clipboard.copy(data)
        self.delete_selection()
        self.str=self.str.replace(data,'')
    def copy(self, data='',*args):
        super().copy(data,*args)
        self._ensure_clipboard()
        if data:
            data=get_display(data)
            return Clipboard.copy(data)
        if self.selection_text:
            selection_text=get_display(self.selection_text)
            return Clipboard.copy(selection_text)
    def paste(self,*args):
        if self.selected_all:
            self._ensure_clipboard()
            self.delete_selection()
            data = Clipboard.paste()
            self.str=data
            self.text=get_display(self.str)
            self.selected_all=False
        elif self.selection_text:
            selection_text=get_display(self.selection_text)
            data = Clipboard.paste()
            self.str=self.str.replace(selection_text,data)
            self.text=get_display(self.str)
        else:
            data = Clipboard.paste()
            data=data
            self.str=self.str+f' {data}'
            self.text=get_display(self.str)   
    def keyboard_on_key_down(self,window,keycode,text,modifiers,*args):
        if keycode[0]==8:
            if self.selected_all:
                self.str=''
                self.text = ''
                self.selected_all=False
            elif self._selection:
                selection_text=get_display(self.selection_text)
                self.str=self.str.replace(selection_text,'')
                self.text=get_display(self.str)
            else:
                self.str=self.str[0:len(self.str) - 1]               
                self.text = get_display(self.str)
        
        elif keycode[0]==13:
            self.str+=u'\n'
            self.text += u'\n'        
    def select_all(self):
        self.selected_all=True
        self.select_text(0, len(self.str))

**Comment by Julian-O** [comment] 2023-12-18 00:33
Closed as duplicate of #8517

**Comment by Julian-O** [comment] 2023-12-18 00:37
@OdzOdz 

You have pasted some code here, but there is no information about what the issue is, so there is nothing for us to fix.

We already have a number of issues with RTL languages - see #8444

Please go to the support channels first before raising issues. The bot message below will tell you where.

**Closed** 2023-12-18 00:37 UTC
Labels: support
