### ISSUE TITLE
Touch event on piTFT causes Warning Traceback

### ISSUE THREAD

**Issue by czerwe** [kivy/kivy#2790] opened 2014-12-25 19:35 UTC
Hi,

i have an PiTFT Capacitive Screen and running Kivy in 1.9.0dev (checkout from 22.12.2014).

If i startup an basic kivy application and touch the screen i get following error:

```
[INFO              ] Logger: Record log in /home/pi/.kivy/logs/kivy_14-12-03_24.txt
[INFO              ] Kivy v1.9.0-dev
[INFO              ] Python: v2.7.3 (default, Mar 18 2014, 05:13:23)
[GCC 4.6.3]
[INFO              ] Factory: 172 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_pygame, img_gif (img_sdl2, img_ffpyplayer, img_pil ignored)
[INFO              ] Text: Provider: pygame
[INFO              ] Window: Provider: egl_rpi
[INFO              ] GL: OpenGL version <OpenGL ES 2.0>
[INFO              ] GL: OpenGL vendor <Broadcom>
[INFO              ] GL: OpenGL renderer <VideoCore IV HW>
[INFO              ] GL: OpenGL parsed version: 2, 0
[INFO              ] GL: Shading version <OpenGL ES GLSL ES 1.00>
[INFO              ] GL: Texture max size <2048>
[INFO              ] GL: Texture max units <8>
[INFO              ] Shader: fragment shader: <Compiled>
[INFO              ] Shader: vertex shader: <Compiled>
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] OSC: using <multiprocessing> for socket
[INFO              ] ProbeSysfs: device match: /dev/input/event2
[INFO              ] HIDInput: Read event from </dev/input/event2>
[INFO              ] Base: Start application main loop
[INFO              ] HIDMotionEvent: using <ft6x06_ts>
[INFO              ] GL: NPOT texture support is available
[INFO              ] HIDMotionEvent: <ft6x06_ts> range position X is 0 - 4095
[INFO              ] HIDMotionEvent: <ft6x06_ts> range position Y is 0 - 4095
[INFO              ] HIDMotionEvent: <ft6x06_ts> range pressure is 0 - 255
[WARNING           ] stderr: Exception in thread Thread-1:
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
[WARNING           ] stderr:     self.run()
[WARNING           ] stderr:   File "/usr/lib/python2.7/threading.py", line 505, in run
[WARNING           ] stderr:     self.__target(*self.__args, **self.__kwargs)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 598, in _thread_run
[WARNING           ] stderr:     process_as_multitouch(*infos)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 388, in process_as_multitouch
[WARNING           ] stderr:     process(l_points)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 509, in process
[WARNING           ] stderr:     touch = HIDMotionEvent(device, tid, args)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/motionevent.py", line 286, in __init__
[WARNING           ] stderr:     self.depack(args)
[WARNING           ] stderr:   File "/usr/local/lib/python2.7/dist-packages/kivy/input/providers/hidinput.py", line 56, in depack
[WARNING           ] stderr:     self.sx = args['x']
[WARNING           ] stderr: KeyError: 'x'`
```

Could this be related to: https://github.com/kivy/kivy/issues/2656?

What do i miss?
##

**Comment by czerwe** [comment] 2015-01-01 19:51
Hi,

i found out an configuration which is almost working for me:
[input]
pitft = mtdev,/dev/input/touchscreen,max_position_x=240,max_position_y=320

Wth hidinput i get always the problem that he's not able to unpack x (and y as well, since none of them exists in the parameters).

The  provider mtdev is working better but now i have the same rotation problem as it is fixed in the hidinput during issue #2656 . Is is possible to move this additional option to the mtdev provider as well?

**Comment by tito** [comment] 2015-01-18 01:05
Can you post a trace of your touchscreen event from evtest? And explain what you did to make it crash?

Just to ensure the issue is something we can fix or not, and maybe hidinput got the fix not mtdev, or the inverse.

**Comment by czerwe** [comment] 2015-01-18 09:51
Hi,

i made an workaround by using the mtdev provider and implemented an rotate agruments based on the changes done by tshirtman in an early stage from #2656 (i saw already that the. But hidinput seems to miss the x and y axis informations inside the parameters. When i printed the arguments from the hidinput i wasn't able to find the x and y inside.

my current configuration string (remember that i altered the mtdev provider) is:

```
pitft = mtdev,/dev/input/touchscreen,max_position_x=240,max_position_y=320,invert_y=1,invert_x=0,rotate=90
```

I attach an output from evtest. It's just an random output i hope that's ok:
```
Event: time 1418829326.904420, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.904420, -------------- SYN_REPORT ------------
Event: time 1418829326.916576, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 186
Event: time 1418829326.916576, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 174
Event: time 1418829326.916576, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.916576, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.916576, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.916576, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.916576, type 3 (EV_ABS), code 0 (ABS_X), value 186
Event: time 1418829326.916576, type 3 (EV_ABS), code 1 (ABS_Y), value 174
Event: time 1418829326.916576, -------------- SYN_REPORT ------------
Event: time 1418829326.928769, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 186
Event: time 1418829326.928769, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 174
Event: time 1418829326.928769, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.928769, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.928769, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.928769, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.928769, -------------- SYN_REPORT ------------
Event: time 1418829326.941926, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 183
Event: time 1418829326.941926, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 172
Event: time 1418829326.941926, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.941926, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.941926, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.941926, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.941926, type 3 (EV_ABS), code 0 (ABS_X), value 183
Event: time 1418829326.941926, type 3 (EV_ABS), code 1 (ABS_Y), value 172
Event: time 1418829326.941926, -------------- SYN_REPORT ------------
Event: time 1418829326.953720, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 183
Event: time 1418829326.953720, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 172
Event: time 1418829326.953720, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.953720, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.953720, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.953720, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.953720, -------------- SYN_REPORT ------------
Event: time 1418829326.967242, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 180
Event: time 1418829326.967242, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 170
Event: time 1418829326.967242, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.967242, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.967242, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.967242, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.967242, type 3 (EV_ABS), code 0 (ABS_X), value 180
Event: time 1418829326.967242, type 3 (EV_ABS), code 1 (ABS_Y), value 170
Event: time 1418829326.967242, -------------- SYN_REPORT ------------
Event: time 1418829326.976816, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 177
Event: time 1418829326.976816, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 169
Event: time 1418829326.976816, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.976816, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.976816, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.976816, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.976816, type 3 (EV_ABS), code 0 (ABS_X), value 177
Event: time 1418829326.976816, type 3 (EV_ABS), code 1 (ABS_Y), value 169
Event: time 1418829326.976816, -------------- SYN_REPORT ------------
Event: time 1418829326.989163, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 175
Event: time 1418829326.989163, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 168
Event: time 1418829326.989163, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829326.989163, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829326.989163, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829326.989163, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829326.989163, type 3 (EV_ABS), code 0 (ABS_X), value 175
Event: time 1418829326.989163, type 3 (EV_ABS), code 1 (ABS_Y), value 168
Event: time 1418829326.989163, -------------- SYN_REPORT ------------
Event: time 1418829327.001628, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 172
Event: time 1418829327.001628, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 168
Event: time 1418829327.001628, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.001628, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.001628, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.001628, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.001628, type 3 (EV_ABS), code 0 (ABS_X), value 172
Event: time 1418829327.001628, -------------- SYN_REPORT ------------
Event: time 1418829327.012777, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 170
Event: time 1418829327.012777, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 167
Event: time 1418829327.012777, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.012777, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.012777, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.012777, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.012777, type 3 (EV_ABS), code 0 (ABS_X), value 170
Event: time 1418829327.012777, type 3 (EV_ABS), code 1 (ABS_Y), value 167
Event: time 1418829327.012777, -------------- SYN_REPORT ------------
Event: time 1418829327.024800, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 167
Event: time 1418829327.024800, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.024800, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.024800, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.024800, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.024800, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.024800, type 3 (EV_ABS), code 0 (ABS_X), value 167
Event: time 1418829327.024800, type 3 (EV_ABS), code 1 (ABS_Y), value 166
Event: time 1418829327.024800, -------------- SYN_REPORT ------------
Event: time 1418829327.037109, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 164
Event: time 1418829327.037109, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.037109, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.037109, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.037109, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.037109, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.037109, type 3 (EV_ABS), code 0 (ABS_X), value 164
Event: time 1418829327.037109, -------------- SYN_REPORT ------------
Event: time 1418829327.050370, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 161
Event: time 1418829327.050370, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.050370, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.050370, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.050370, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.050370, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.050370, type 3 (EV_ABS), code 0 (ABS_X), value 161
Event: time 1418829327.050370, -------------- SYN_REPORT ------------
Event: time 1418829327.061740, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 159
Event: time 1418829327.061740, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.061740, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.061740, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.061740, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.061740, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.061740, type 3 (EV_ABS), code 0 (ABS_X), value 159
Event: time 1418829327.061740, -------------- SYN_REPORT ------------
Event: time 1418829327.075492, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 157
Event: time 1418829327.075492, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.075492, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.075492, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.075492, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.075492, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.075492, type 3 (EV_ABS), code 0 (ABS_X), value 157
Event: time 1418829327.075492, -------------- SYN_REPORT ------------
Event: time 1418829327.085103, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 155
Event: time 1418829327.085103, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.085103, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.085103, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.085103, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.085103, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.085103, type 3 (EV_ABS), code 0 (ABS_X), value 155
Event: time 1418829327.085103, -------------- SYN_REPORT ------------
Event: time 1418829327.097075, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 152
Event: time 1418829327.097075, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.097075, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.097075, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.097075, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.097075, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.097075, type 3 (EV_ABS), code 0 (ABS_X), value 152
Event: time 1418829327.097075, -------------- SYN_REPORT ------------
Event: time 1418829327.108871, type 3 (EV_ABS), code 53 (ABS_MT_POSITION_X), value 150
Event: time 1418829327.108871, type 3 (EV_ABS), code 54 (ABS_MT_POSITION_Y), value 166
Event: time 1418829327.108871, type 3 (EV_ABS), code 58 (ABS_MT_PRESSURE), value 127
Event: time 1418829327.108871, type 3 (EV_ABS), code 57 (ABS_MT_TRACKING_ID), value 0
Event: time 1418829327.108871, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 127
Event: time 1418829327.108871, ++++++++++++++ SYN_MT_REPORT ++++++++++++
Event: time 1418829327.108871, type 3 (EV_ABS), code 0 (ABS_X), value 150
Event: time 1418829327.108871, -------------- SYN_REPORT ------------
Event: time 1418829327.120898, type 3 (EV_ABS), code 48 (ABS_MT_TOUCH_MAJOR), value 0
Event: time 1418829327.120898, type 3 (EV_ABS), code 24 (ABS_PRESSURE), value 0
Event: time 1418829327.120898, type 1 (EV_KEY), code 330 (BTN_TOUCH), value 0
Event: time 1418829327.120898, -------------- SYN_REPORT ------------
```
Due to my move from one flat to an small house i am not able to answer that fast (we still have only limited Internet), sorry for some delays.

Thanks for you answer.

**Comment by czerwe** [comment] 2015-01-19 15:36
Oh i forgot the question about what i did.
The error occures the first time i touch the screen after application startup, regardless where and which type of widget i touch.

**Comment by tpulatha** [comment] 2015-07-09 18:53
I had the exact same issue. Fixed it by using the mtdev input provider and adding rotation to the mtdev input in kivy. (fixed another bug along the way) I will create a pull request as soon as possible.

**Comment by tpulatha** [comment] 2015-07-09 19:19
Added in https://github.com/kivy/kivy/pull/3494

**Comment by Julian-O** [comment] 2023-11-05 02:50
Closing as fixed.

**Closed by Julian-O** 2023-11-05 02:50 UTC
Labels: Platform: RPi
