### ISSUE TITLE
Sensible Spinner? Separate key from text

### ISSUE THREAD

**Issue by Cheaterman** [kivy/kivy#6786] opened 2020-03-19 10:49 UTC
**Is your feature request related to a problem? Please describe.**
(Excuse the wording, I'm merely using the template :-P ) I'm always frustrated when I use Kivy's Spinner class, which forces me to monitor its "text" property, and translate that text to a usable key myself. Particularly problematic when making internationalized software... The text will change, while the selected key should not...

**Describe the solution you'd like**
Well, maybe a few lines of code speak louder than a thousand words, so I present to you the KeyedSpinner (if it LGTY I'll PR it) :
```python
class KeyedSpinner(Spinner):
    values = DictProperty()
    '''Values that can be selected by the user. It must be a dict.

    The expected format is {key: 'Text for the key'} where key is a
    hashable value that will be stored as `KeyedSpinner.value`.

    :attr:`values` is a :class:`~kivy.properties.DictProperty` and
    defaults to {}.
    '''

    value = ObjectProperty(allownone=True)
    '''Key of currently selected item. It must be hashable.

    :attr:`value` is a :class:`~kivy.properties.ObjectProperty` and
    defaults to None.
    '''

    def on_text(self, *args):
        for key, value in self.values.items():
            if value == self.text:
                self.value = key 
                break
        else:
            self.value = None

    def on_value(self, *args):
        if self.value not in self.values:
            self.text = ''
        else:
            self.text = self.values[self.value]

    def _update_dropdown(self, *largs):
        dp = self._dropdown
        cls = self.option_cls
        values = self.values
        text_autoupdate = self.text_autoupdate

        if isinstance(cls, string_types):
            cls = Factory.get(cls)

        dp.clear_widgets()

        for key, value in values.items():
            item = cls(text=value)
            item.key = key
            item.height = self.height if self.sync_height else item.height
            item.bind(on_release=self._on_select_item)
            dp.add_widget(item)

    def _on_select_item(self, button):
        self._dropdown.select(button.text)
        self.value = button.key
```
Usage is fairly self-explanatory: instead of `values` being a list of strings, it's a dict, the values should be strings (used for display) while the key is, well, a key, that will be set as `value` property whenever the user selects an item.

**Describe alternatives you've considered**
None. To be honest, I merely noticed HTML has a `select` tag that can do this, and I was like « How the fricking heck is it possible we don't have something that useful in Kivy??? ». Also one day on one project, I needed it, so I coded it. :-)

**Additional context**
Dunno bros, maybe [this](https://i.ytimg.com/vi/qIKG5ehbhIU/maxresdefault.jpg)? [Hehehe](https://static.mmzstatic.com/wp-content/uploads/2012/01/trollface-meme.jpg).

**Comment by matham** [comment] 2020-03-19 16:47
I feel you, I had the same issue. The reason for the problem is that kivy widgets are not very abstract, so this may benefit from creating a better Spinner in garden or a special section of kivy core widgets in garden. 

Personally, I copied the Spinner widget source code into my project and customized it as I needed...

**Comment by Cheaterman** [comment] 2020-03-19 19:21
Yeah, that's fair, I guess it could be a good idea to start building an alternative widget library in the garden or something :-)

**Comment by tshirtman** [comment] 2020-03-28 17:15
This is possible since the dictionaries are now ordered, but it still feels a bit hacky (yes, i know they said it would stay ordered, but it feels wrong to rely on that to provide the flexibility the interface need). Another option that would allow keeping that in the kivy Spinner class, would be to keep the items as a ListProperty, but allow items to be tuples ,and treat them as key/values in this case (for simplicity's sake, if the values are strings, they could be transformed to 2-tuples of identical values. We could also indicate that passing simple strings is deprecated if we want to simplify the interface later.

usage would be ```yml
Spinner:
    values: (('key1': 'value 1'), ('key2': 'value 2'))
```
the spinner in this case would display 'value 1', 'value 2' but on value change, on top of dispatching text, it would dispatch `value` as `key1` or `key2`.

**Comment by matham** [comment] 2020-05-13 21:22
I'm gonna close this, as I don't expect kivy's spinner to be changed soon. But PRs are welcome if you want to implement what @tshirtman suggested (although I don't really like back-engineering this syntax like this.

**Closed by matham** 2020-05-13 21:22 UTC
Labels: feature
