### ISSUE TITLE
Blurry/Crippled Images

### ISSUE THREAD

**Issue by BillBridge** [kivy/kivy#5249] opened 2017-06-29 09:38 UTC
### Versions

* Python: 2.7.12
* OS: Windows 10 Pro
* Kivy: 1.10.0
* Kivy installation method: pip

### Description

Images and buttons on images are presented blurry/crippled. 

![image](https://user-images.githubusercontent.com/18249253/27680143-19c20438-5cbb-11e7-95d5-79d8ac8b71b9.png)

Where the original images are crisp and sharp:
![image](https://user-images.githubusercontent.com/18249253/27680244-63a51c0c-5cbb-11e7-9978-92234dd6614c.png)

![ng-assistant32](https://user-images.githubusercontent.com/18249253/27680295-9283e3f0-5cbb-11e7-95b3-467421ebd686.png)

When you look more in detail, it seems that there is a 1 pixel shift:

![image](https://user-images.githubusercontent.com/18249253/27680378-c781557e-5cbb-11e7-8f14-b58e4d873e99.png)

In the previous version of Kivy I encountered the same issues with Spinner widgets. Text in selectable items were very blurry. After changing the following lines in the Kivy code this problem was solved. Also images on button looked better but not all. Some images stayed crippled.:

kivy/core/text/__init__.py
	@@ -645,6 +645,9 @@ def refresh(self):
		             texture = Texture.create(size=(width, height),
		                                      mipmap=self.options['mipmap'],
		                                      callback=self._texture_fill)
		+            #switching off linear interpolation
		+            texture.mag_filter="nearest"
		+            texture.min_filter="nearest"
		             texture.flip_vertical()
		             texture.add_reload_observer(self._texture_refresh)
		             self.texture = texture

kivy/uix/scrollview.py
	@@ -924,7 +924,8 @@ def update_from_scroll(self, *largs):
		         # widget position behind. We set it here, but it will be a no-op most of
		         # the time.
		         vp.pos = 0, 0
		-        self.g_translate.xy = x, y
		+        #translating to integer values to avoid texture blur
		+        self.g_translate.xy = int(x), int(y)

After upgrading to 1.10.0 I had to make the changes above manually because the items in the Spinner looked awfull again.

### Code and Logs

```python
    BoxLayout:
        canvas.before:
            Color:
                rgb: 0.9,0.42,0.3    # oranje
            Rectangle:
                pos: self.pos
                size: self.size

        orientation: "vertical"

        Image:
            size_hint: 1,0.1
            canvas.before:
                Color:
                    rgb: 0.5,0.5,0.5     # mid grijs
                Rectangle:
                    pos: self.pos
                    size: self.size
            source: './images/NG-Assistant32.png'
            on_size: args[0].texture.min_filter = 'nearest'

        Button:
            size_hint: 1,0.15
            on_press: root.maximize_itapp()
            Image:
                source: './images/ic-maxim-white.png'
                center_x: self.parent.center_x
                center_y: self.parent.center_y

```

**Comment by dessant** [comment] 2017-06-29 09:41
Duplicate of https://github.com/kivy/kivy/issues/2297.

**Closed by dessant** 2017-06-29 09:41 UTC

**Comment by BillBridge** [comment] 2017-06-29 10:24
TMHO, this is not a duplicate of #2297. Why is the problem still there? It is maybe solved in Listviews but not in a plain image.
