### ISSUE TITLE
installation problem ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2==0.1.* (from versions: 0.3.0, 0.3.1) 

### ISSUE THREAD

**Issue by LloydTSmith** [kivy/kivy#7175] opened 2020-10-23 22:55 UTC
**Software Versions**
* Python: 3.9.0
* OS: Win 10
* Kivy: 1.11.1
* Kivy installation method: following instructions at https://kivy.org/doc/stable/installation/installation-windows.html

I saw another thread on this error, but it seemed to related to CygWin, which I don't have as far as I know. Complete newbie here, installing for the first time so that I can begin a Python course. Installation according to the instructions above gives me this:

(kivy_venv) C:\Users\lsmith>python -m pip install --upgrade pip wheel setuptools virtualenv
Collecting pip
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Requirement already up-to-date: wheel in c:\users\lsmith\kivy_venv\lib\site-packages (0.35.1)
Collecting setuptools
  Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
Collecting virtualenv
  Using cached virtualenv-20.0.35-py2.py3-none-any.whl (4.9 MB)
Collecting six<2,>=1.9.0
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting distlib<1,>=0.3.1
  Using cached distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting filelock<4,>=3.0.0
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting appdirs<2,>=1.4.3
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: pip, setuptools, six, distlib, filelock, appdirs, virtualenv
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
  Attempting uninstall: setuptools
    Found existing installation: setuptools 50.3.1
    Uninstalling setuptools-50.3.1:
      Successfully uninstalled setuptools-50.3.1
Successfully installed appdirs-1.4.4 distlib-0.3.1 filelock-3.0.12 pip-20.2.4 setuptools-50.3.2 six-1.15.0 virtualenv-20
.0.35

(kivy_venv) C:\Users\lsmith>python -m pip install docutils pygments pypiwin32 kivy_deps.sdl2==0.1.* kivy_deps.glew==0.1.
*
Collecting docutils
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting pygments
  Using cached Pygments-2.7.1-py3-none-any.whl (944 kB)
Collecting pypiwin32
  Using cached pypiwin32-223-py3-none-any.whl (1.7 kB)
ERROR: Could not find a version that satisfies the requirement kivy_deps.sdl2==0.1.* (from versions: 0.3.0, 0.3.1)
ERROR: No matching distribution found for kivy_deps.sdl2==0.1.*

**Comment by matham** [comment] 2020-10-23 23:13
Duplicate of https://github.com/kivy/kivy/issues/6806#issuecomment-608176268.

**Closed by matham** 2020-10-23 23:13 UTC
