### ISSUE TITLE
New install on OSX Yosemite won't launch

### ISSUE THREAD

**Issue by rwdim** [kivy/kivy#3235] opened 2015-04-05 15:01 UTC
I had a previous working version of Kivy, and replaced it with the latest today. It will not launch. Here's the info dumped into logs in /var/log

Apr  5 10:01:23 rwdmac com.apple.dock.ecti[1271]: Failed to connect (textField) outlet from (ECTIHelperApp) to (NSTextField): missing setter or instance variable
Apr  5 10:01:25 rwdmac Kivy[1275]: Failed to connect (applicationMenu) outlet from (ScriptExecController) to (NSMenu): missing setter or instance variable
Apr  5 10:01:25 rwdmac Kivy[1275]: App did finish launching

That's it. No kivy. No happiness.

**Comment by FLIR31207** [comment] 2015-04-05 17:40
I am seeing the same thing.
I'd like to add that the DMG I downloaded does not contain the Readme.txt file referred to in the Installation instructions:
<code>
To install Kivy, you must:
Download the latest version from http://kivy.org/#download
Double-click to open it
Drag the Kivy.app into your Applications folder
Make sure to read the Readme.txt
</code>

**Comment by kris-s** [comment] 2015-04-05 19:25
I've gotten it to launch if installed when unplugged from an external monitor (Apple Cinema w/ Thunderbolt in this case), .app does not contain Readme or make-symlinks script either.

**Comment by FLIR31207** [comment] 2015-04-05 19:36
I did not use an ext. screen during install

**Comment by akshayaurora** [comment] 2015-04-05 19:56
@rwdim how do you run kivy? We missed setting up the read me and the make symlinks option.
We will be providing a new package with these, however in the mean time could you please try setting up the symlink ?

ln -s /Applications/Kivy.app/Contents/Resources/script /use/local/kivy

With this link setup you guys can then use kivy from the command line by running your app using `kivy yourapp.py`

**Comment by rwdim** [comment] 2015-04-06 04:43
Thx - I'll try that.

**Comment by rwdim** [comment] 2015-04-06 04:48
tried

sudo ln -s /Applications/Kivy.app/Contents/Resources/script /usr/local/kivy

and when I run it from the terminal, it does start python 2.7.6. WIll try
that with an app.

**Comment by FLIR31207** [comment] 2015-04-06 12:39
@akshayaurora thanks for the tip; can you plesse post a short comment when the new package has been released?

**Comment by r1chardj0n3s** [comment] 2015-04-09 14:29
The new package doesn't include the "Make Symlink" or readme file that the 1.8 release had, which is confusing users.

**Comment by codyit** [comment] 2015-04-16 13:31
Consider me another confused user :)
/Resources/script should be linked as kivy isn't obvious at all for new user trying out kivy.
Thanks @akshayaurora

**Comment by handsomegui** [comment] 2015-04-18 15:51
My kivy refuse to start on OSX Yosemite.

**Comment by passiomatic** [comment] 2015-04-23 19:15
I can confirm that on my copy of Yosemite (10.10.3) Kivy doesn't launch too.

**Comment by FLIR31207** [comment] 2015-04-23 19:34
As I understand it is confirmed that the current OSX package is missing the readme as well as the symlink and since this has now been open for 3 weeks, it seems like we will not see an updated package until there is a new version of kivy. Fortunately @akshayaurora 's tip to 

sudo ln -s /Applications/Kivy.app/Contents/Resources/script /usr/local/kivy

seems to work.

**Comment by akshayaurora** [comment] 2015-04-26 22:23
We have a new package for OS X uploaded to Kivy,org/#downloads OS X
section. This file is named Kivy1.9-rev3-osx.dmg
It's built on top of stable branch which has a few small fixes over 1.9
mostly for packaging and couple regressions over 1.8 mostly packaging fixes
though.

This also has the `MakeSymlinks` script you guys asked for. Hope this
helps, apologies  for delay.

**Comment by rogererens** [comment] 2015-04-26 22:32
> We have a new package for OS X uploaded to Kivy,org/#downloads OS X
> section. This file is named Kivy1.9-rev3-osx.dmg

Thanks a lot!
Maybe you should update the name of the link on the download page as well to make it more clear?

**Comment by akshayaurora** [comment] 2015-04-26 22:38
Done, Website should update in about 15 minutes.

**Comment by passiomatic** [comment] 2015-05-01 07:42
Works for me. Thank you!

**Comment by akshayaurora** [comment] 2015-06-21 15:26
this issue was fixed on April 27th,  we just forgot to close the issue

**Comment by vichargrave** [comment] 2015-12-31 18:51
Still not working for me even after creating the symlink

**Comment by Takage** [comment] 2016-01-07 15:13
Having the same problem here with the newest kivy version on Yosemite

**Comment by akshayaurora** [comment] 2016-01-07 17:12
@vichargrave @Takage your issues are for different versions as the original one, please post details of your issue, like which package are you using python2 or 3? What error do you get?

**Comment by akshayaurora** [comment] 2016-01-07 17:22
Please add the details here on a new issue #3897 .

**Closed by akshayaurora** 2016-01-07 17:22 UTC
