### ISSUE TITLE
Build OS X/macOS wheels

### ISSUE THREAD

**Issue by akshayaurora** [kivy/kivy#4965] opened 2017-01-29 17:25 UTC
Wheels should be available for next release on osx. Specially cause of binary issues with gstreamer and the like.

**Comment by dessant** [comment] 2017-01-29 17:28
Duplicate of https://github.com/kivy/kivy/issues/4620.

**Comment by dessant** [comment] 2017-01-29 18:25
Reopening, the scope of #4620 was narrowed down to manylinux wheels.

**Closed** 2019-12-18 23:34 UTC
Labels: distribution
