### ISSUE TITLE
Importing Kivy DLL Issue

### ISSUE THREAD

**Issue by datascininja** [kivy/kivy#3921] opened 2016-01-16 18:06 UTC
Sigh...Here's another question about Python's never ending module issues. I have Python 3.4 and Windows 8. I can import Kivy fine, but if I try to import kivy.graphics, I run into a DLL issue:

```javascript
File "C:\Users\Young\Anaconda3\lib\site-packages\kivy\graphics\__init__.py",  line 89, in <module>
 from kivy.graphics.instructions import Callback, Canvas, CanvasBase, \
ImportError: DLL load failed: The specified module could not be found.
```

Does anyone know how to fix this?

**Comment by pythonic64** [comment] 2016-01-16 18:12
Did you install Kivy dependencies?

**Comment by datascininja** [comment] 2016-01-16 19:50
pythonic64: Don't current kivy installations already come with dependencies? I've looked into dependencies and they said I need zip files with contain the kivy files and dependencies, but zips aren't available anymore since python module installation now requires pip.

**Comment by pythonic64** [comment] 2016-01-16 19:56
Did you followed instructions on [Installation on windows](https://kivy.org/docs/installation/installation-windows.html#install-win-dist) page? This dll error looks like you didn't installed kivy.deps.sdl2.

**Comment by matham** [comment] 2016-01-16 20:53
This may be related to https://github.com/kivy/kivy/issues/3889.

**Comment by matham** [comment] 2016-01-17 00:06
For now, the solution is to use pillow: `pip install pillow`. However, you'll need to use a nightly kivy as 1.9.1 won't work with pillow I believe. I'm closing this as a duplicate of #3889. If it isn't, please re-open.

**Closed by matham** 2016-01-17 00:06 UTC
