### ISSUE TITLE
Kivy UrlRequest error on android, gaierror(7,’No address associated with host name’)

### ISSUE THREAD

**Issue by skoy20** [kivy/kivy#7087] opened 2020-09-15 10:12 UTC
**Software Versions**
* Python: 3.8
* OS: Android
* Kivy: 2.0.0rc3
* Kivy installation method: buildozer

**Describe the bug**
UrlRequest doesnt work on android while working perfectly on my computer. The error says : <UrlRequest Thread-1, started daemon ....> , gaierror(7,'No address associated with host name).
i used https url and already added internet permission in buildozer.

**Expected behavior**
Successful https request

**Comment by misl6** [comment] 2023-05-14 09:42
Closing as we can't reproduce the issue on Kivy==2.2.0rc1. Feel free to re-open if you're still encountering this issue on a newer Kivy version.

**Closed by misl6** 2023-05-14 09:42 UTC
