### ISSUE TITLE
start animation of the window

### ISSUE THREAD

**Issue by cTas0099** [kivy/kivy#6089] opened 2019-01-01 17:40 UTC
### Versions

* Python: 3.7.1
* OS: ArchLinux
* Kivy:1.10.1 

### Description

Happy new year!!

what am I doing wrong..?   I want to get an animation from a certain position in the application window, but this does not work

the animation works well, BUT from the beginning of the screen

### Code and Logs
My python file

```python
from kivy.app import App
from kivy.uix.widget import Widget


class Anim(Widget):
	pass


class MenuApp(App):
	def build(self):
		but = Anim()
		return but


if __name__ == '__main__':
	MenuApp().run()

```
my kivy file
```python

#:kivy 1.10.1
#: import Animation kivy.animation.Animation

<Anim>:
	
	btn: btn
	btn1: btn1
	box: box
	an1: Animation(x=320,  duration=3).start(self.box)	
	BoxLayout:
		id: box
		pos: 200, 0
		orientation: 'vertical'
		
		Button:
			id: btn
			text: 'ghjdddsaw2345'
			on_press: self.text=('ghjkl')
		
		Button:
			id: btn1
			text: 'ghjdddsaw'
			on_press: self.text=('87623')
```

**Comment by Zen-CODE** [comment] 2019-01-06 07:56
Hi

I am going to close this is not a bug. Your don't really want to put the animation object in the KV as 'start' does not return anything.

In future, please post you question on the forum (link below). Tickets should be used only when you are certain you have found a bug.

https://groups.google.com/forum/#!forum/kivy-users

Anyway, here is perhaps a better waYfrom kivy.lang import Builder
from kivy.app import App
from kivy.uix.widget import Widget
from kivy.animation import Animation

Builder.load_string('''
#:kivy 1.10.1
#: import Animation kivy.animation.Animation

<Anim>:

	btn: btn
	btn1: btn1
	box: box
	# an1: Animation(x=320, duration=3).start(self.box)
	BoxLayout:
		id: box
		pos: 200, 0
		orientation: 'vertical'

		Button:
			id: btn
			text: 'ghjdddsaw2345'
			on_press: self.text = ('ghjkl')

		Button:
			id: btn1
			text: 'ghjdddsaw'
			on_press: self.text = ('87623')
''')

class Anim(Widget):
	pass


class MenuApp(App):
	def build(self):
		but = Anim()
		Animation(x=320, duration=3).start(but.ids.box)
		return but


if __name__ == '__main__':
	MenuApp().run()

**Closed by Zen-CODE** 2019-01-06 07:56 UTC

**Comment by cTas0099** [comment] 2019-01-07 11:05
@Zen-CODE 

please watch my GIF, this is the animation written in my code, the animation that you sent me begins with the position of BoxLayout

![main](https://user-images.githubusercontent.com/38870180/50764431-5e6a5f00-1294-11e9-9aee-d0bfe880df1b.gif)

**Comment by Zen-CODE** [comment] 2019-01-07 14:40
Yes, so what is the problem? Where do you want it to start?

**Comment by cTas0099** [comment] 2019-01-07 15:03
@Zen-CODE  I want the animation to start from the position of BoxLayout, not from the bottom right of the application window
and yes, I wrote similar code with yours, and everything worked fine:

.py file

```
from kivy.app import App
from kivy.uix.widget import Widget



class Anim(Widget):
	pass
		

class MenuApp(Anim, App):
	def build(self):
		
		but = Anim()
		return but


if __name__ == '__main__':
	MenuApp().run()

```

.kv file
```
#:kivy 1.10.1
#: import Animation kivy.animation.Animation
<Anim>:
	
	btn: btn
	btn1: btn1
	box: box
	#an1: Animation(x=320,  duration=3).start(self.box)
	Button:
		text:'12345'
		on_press: Animation(x=320,  duration=3).start(root.box)
		top: root.top
	BoxLayout:
		id: box
		pos: -150, 0
		orientation: 'vertical'
		
		Button:
			id: btn
			text: 'ghjdddsaw2345'
			on_press: Animation(x=420,  duration=3).start(root.btn)
		
		Button:
			id: btn1
			text: 'ghjdddsaw'
			on_press: self.text=('87623')
```

**Comment by cTas0099** [comment] 2019-01-07 15:10
@Zen-CODE  
![main1](https://user-images.githubusercontent.com/38870180/50775515-342a9880-12b8-11e9-954a-a42cfbe3c9cf.gif)
