### ISSUE TITLE
Tabs converted to spaces

### ISSUE THREAD

**Issue by abhigenie92** [kivy/kivy#3616] opened 2015-09-05 17:57 UTC
![capture](https://cloud.githubusercontent.com/assets/12474640/9700583/b06417d2-5425-11e5-94bc-58a0fc1a14b5.JPG)

**Comment by dessant** [comment] 2015-09-06 12:09
Duplicate of https://github.com/kivy/kivy/issues/3477.

**Closed by dessant** 2015-09-06 12:09 UTC
