### ISSUE TITLE
kivy language: propagate value updates when using f-strings

### ISSUE THREAD

**Issue by tomaskrizek** [kivy/kivy#7370] opened 2021-02-06 20:39 UTC
Python 3.6 allows use of [f-string](https://www.python.org/dev/peps/pep-0498/) for formatting values:
```
'{}'.format(x)  # becomes
f'{x}'
```

In the kivy language, when the first format is used, anytime `x` is updated, so will be the value that uses it, e.g.
```
Label:
    text: '{}'.format(x)
```

If an f-string is used instead, only the initial `x` value is used and any updates to `x` are no longer reflected.
```
Label:
    text: f'{x}'
```

It'd be nice if it'd be possible to use f-strings and get the value updates propagated.

**Comment by tshirtman** [comment] 2021-02-06 21:46
i believe this is a duplicate of #6108

**Closed** 2021-02-06 21:47 UTC
