### ISSUE TITLE
Cannot build cython with XCode 5.1 installed - doc change

### ISSUE THREAD

**Issue by cropleyb** [kivy/kivy#2022] opened 2014-03-28 11:05 UTC
I was having trouble re-installing cython using pip after installing the latest version of XCode:

```
$ sudo pip install --upgrade cython
[snip]

cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c /private/tmp/pip_build_root/cython/Cython/Plex/Scanners.c -o build/temp.macosx-10.9-intel-2.7/private/tmp/pip_build_root/cython/Cython/Plex/Scanners.o

clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]

clang: note: this will be a hard error (cannot be downgraded to a warning) in the future

error: command 'cc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools;__file__='/private/tmp/pip_build_root/cython/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Z4otlr-record/install-record.txt --single-version-externally-managed failed with error code 1 in /private/tmp/pip_build_root/cython
Storing complete log in /Users/cropleyb/Library/Logs/pip.log
```

Setting the CFLAGS env var doesn't help by itself:
(as per http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation-fa)

```
export CFLAGS=-Qunused-arguments
```

...because you also need the -E flag to sudo:

```
sudo -E pip install --upgrade cython
```
##

**Comment by misl6** [comment] 2023-05-14 09:38
Closing as we can't reproduce the issue on Kivy==2.2.0rc1. Feel free to re-open if you're still encountering this issue on a newer Kivy version.

**Closed by misl6** 2023-05-14 09:38 UTC
Labels: Component: documentation
