### ISSUE TITLE
UI scaling is not working correctly with different dpi displays

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [kivy/kivy#6425] opened 2019-07-18 10:55 UTC
### Versions

* Python: 3.7
* OS: macOS Mojave
* Kivy: 1.11.0
* Kivy installation method: pip

### Description

When on macbook pro with external display plugged in the app is scaled according to retina display dpi, however when app is moved to secondary display with much lower dpi the UI scaling is not recalculated resulting in huge UI elements. Is there a quick solution to this?
Screenshots for those without a macbook on hand to reproduce:
https://i.stack.imgur.com/9wAMM.png - retina
https://i.stack.imgur.com/2HP04.png - external display

### Code and Logs

```python
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.button import Button
from kivy.config import Config
from kivy.metrics import sp
Config.set('graphics', 'width', '200')
Config.set('graphics', 'height', '50')


class TestApp(App):
    def build(self):
        mylayout = BoxLayout(orientation="vertical")
        mybutton = Button(text="TEST", font_size=sp(20))  
        mylayout.add_widget(mybutton)
        return mylayout

TestApp().run()
```

**Comment by matham** [comment] 2019-07-21 21:48
Duplicate of https://github.com/kivy/kivy/issues/6144.

**Closed by matham** 2019-07-21 21:48 UTC
