### ISSUE TITLE
SoundSDL2 get_pos() returns 0 - missing function?

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#4152] opened 2016-04-06 12:03 UTC
<pre>from kivy.core.audio import Sound, SoundLoader

sound = SoundLoader.load(my_sound)
sound.play()
sound.get_pos()
Sound().get_pos()
Sound.get_pos(sound)</pre>

I'm using SDL2 and I see defined `get_pos` in all other files except `audio_sdl2.pyx`. Every `get_pos()` in my code returns zero as it's defined in `__init__()`.

Is that funtion missing for some reason or why it's not there? Should I use gstreamer instead of default sdl2 when I want to do something with audio?

**Comment by dessant** [comment] 2016-04-06 13:03
Yes, gstreamer should be good for get_pos.
Duplicate of https://github.com/kivy/kivy/issues/4139.

**Closed by dessant** 2016-04-06 13:03 UTC
