### ISSUE TITLE
kivy.graphics.texture Texture.create () dumps core

### ISSUE THREAD

**Issue by mvdvalk** [kivy/kivy#7321] opened 2021-01-09 17:01 UTC
Hi,

On Kivy v2.0.0:

from kivy.graphics.texture import Texture
tx = Texture.create () # dumps core

**Comment by Schlaubischlump** [comment] 2021-02-26 18:52
This issue is missing some important informations. E.g Which platform are you using ? It is working fine for mac OS 10.15

**Comment by pythonic64** [comment] 2021-02-27 10:39
You have to import `Window` (`from kivy.core.window import Window`) to use `Texture.create`.

Duplicate of https://github.com/kivy/kivy/issues/5254.

**Closed by pythonic64** 2021-02-27 10:39 UTC
