### ISSUE TITLE
TypeError: key_up() missing 2 required positional arguments: 'text' and 'modifiers'

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#3853] opened 2015-12-19 14:28 UTC
https://github.com/kivy/kivy/blob/master/examples/keyboard/main.py#L204
The callback method assumes a different event signature for on_key_up, note that both Keyboard and Window have this event, and they have different signatures.

```python
 Traceback (most recent call last):
   File "E:\dev\envs\py34_x86\kivy\examples\keyboard\main.py", line 220, in <module>
     KeyboardDemo().run()
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 828, in run
     runTouchApp()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 613, in mainloop
     self._mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 546, in _mainloop
     self.dispatch('on_key_up', key, scancode)
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\__init__.py", line 163, in _on_window_key_up
     return self.dispatch('on_key_up', keycode)
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
 TypeError: key_up() missing 2 required positional arguments: 'text' and 'modifiers'
```

**Comment by akshayaurora** [comment] 2015-12-31 06:16
closed by #3883

**Comment by dessant** [comment] 2015-12-31 09:57
The events from both classes are used in the example, fitting the callback to the other one will still produce a crash.
Select `dock` mode, restart the app, press `Continue` and select one of the keyboard layouts, then use the docked keyboard.

```python
 Traceback (most recent call last):
   File "E:\dev\envs\py34_x86\kivy\examples\keyboard\main.py", line 220, in <module>
     KeyboardDemo().run()
   File "e:\dev\envs\py34_x86\kivy\kivy\app.py", line 828, in run
     runTouchApp()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "e:\dev\envs\py34_x86\kivy\kivy\core\window\window_sdl2.py", line 362, in _mainloop
     EventLoop.idle()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 330, in idle
     self.dispatch_input()
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 315, in dispatch_input
     post_dispatch_input(*pop(0))
   File "e:\dev\envs\py34_x86\kivy\kivy\base.py", line 281, in post_dispatch_input
     wid.dispatch('on_touch_up', me)
   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\vkeyboard.py", line 841, in on_touch_up
     self.process_key_up(touch)
   File "e:\dev\envs\py34_x86\kivy\kivy\uix\vkeyboard.py", line 790, in process_key_up
     self.dispatch('on_key_up', b_keycode, internal, b_modifiers)
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
 TypeError: key_up() takes 3 positional arguments but 5 were given
```

**Comment by Andromfins** [comment] 2015-12-31 18:20
yeah it does :+1: it wouldn't be that easy i knew it

**Comment by CuriousLearner** [comment] 2016-03-03 16:09
Hello, I would like to get started with contributing to kivy. Since this is my first bug, could someone guide me how can I reproduce this issue?

**Comment by CuriousLearner** [comment] 2016-03-03 17:11
Hi, I've been able to reproduce the issue and after some inspection, I've seen that method is getting 5 arguments, one of them is keycode again and another one is an empty list. Also I see there is a bind method which is essentially binding the keyboard events to kivy. So, should I just get all arguments in that method and do nothing with them, or how could I go around calling of this method.

What I've done to make this work right now is:
```
def key_up(self, keyboard, keycode, *args):
        """ The callback function that catches keyboard events. """
        self.displayLabel.text += u" (up {0})".format(keycode)
```

Can you please guide me further?

**Comment by weihuang0908** [comment] 2016-03-20 07:56
Hello, I am a new contributor and trying to work this issue
“”"
	Select dock mode, restart the app, press Continue and select one of the keyboard layouts, then use the docked keyboard.
	TypeError: key_up() takes exactly 3 arguments (5 given)
	# (<kivy.uix.vkeyboard.VKeyboard object at 0x10ae9c8a0>, u'g', u'g', [])
	# or (keyboard, keycode, text, modifiers)
“”"

	The crash can be avoided simply by appending a parameter for the function key_up
in https://github.com/kivy/kivy/blob/master/examples/keyboard/main.py#L204
like this:

-  def key_up(self, keyboard, keycode):
+ def key_up(self, keyboard, keycode, *args):

Is it correct?

	What’s more, when I look for the defination of function on_key_up,
I find “on_key_up(down): keycode, internal, modifiers”  in kivy.uix.vkeyboard.VKeyboard,
and “on_key_up(down): key, scancode, codepoint” in  ivy.core.window.Keyboard,
while in this example there is “key_down(keyboard, keycode, text, modifiers)"
I’m confused. Why they three are so different?


references:
https://kivy.org/docs/api-kivy.uix.vkeyboard.html?highlight=vkeyboard#module-kivy.uix.vkeyboard
https://kivy.org/docs/api-kivy.core.window.html?highlight=request_keyboard#kivy.core.window.WindowBase.request_keyboard

**Comment by akshayaurora** [comment] 2016-03-25 14:18
closed by #4109

**Closed by akshayaurora** 2016-03-25 14:18 UTC
Labels: easy, examples

**Comment by janssen** [comment] 2016-04-01 19:52
Note that the documentation (in kivy.core.window.WindowBase) of on_event_up is still wrong.

**Comment by janssen** [comment] 2016-04-01 19:53
Sorry, "on_key_up"!
