### ISSUE TITLE
100% cpu on Linux

### ISSUE THREAD

**Issue by pyfrid** [kivy/kivy#3726] opened 2015-10-25 23:46 UTC
Even starting very simple applications, kivy (from master) makes one cpu core 100% busy on my linux machine (ubuntu 14.04). Application works properly. If I do something, for example, moving slider cpu goes down, but while being idle goes back to 100%. Is this a bug or a feature?

**Comment by dessant** [comment] 2015-10-25 23:55
Definitely a feature. 😛

**Comment by bionoid** [comment] 2015-10-26 00:30
Cannot reproduce this on Ubuntu 14.04 with py2 or py3, testing touchtracer, pictures or showcase on master. @pyfrid can you please verify that you see this behavior with these examples?

**Comment by pyfrid** [comment] 2015-10-26 20:35
I can reproduce this on my PC with touchtracer both with master and with daily build.
The output is the following:
[INFO   ] [Kivy        ] v1.9.1-dev
[INFO   ] [Python      ] v2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
[INFO   ] [Factory     ] 177 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 10.1.3>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Sandybridge Desktop >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...

**Comment by dessant** [comment] 2015-10-26 20:55
@pyfrid could you profile touchtracer? Please run the command below, leave the app open for a bit while the cpu is at 100%, then close it. `touchtracer.prof` will be saved in the same folder and you will have to attach that file here.

```
python -m cProfile -o touchtracer.prof main.py
```

**Comment by pyfrid** [comment] 2015-10-26 21:06
Here it is
https://drive.google.com/open?id=0B47IF5KCd6h0Mjc4V19QSVljbWs

**Comment by dessant** [comment] 2015-10-26 21:07
It asks for a login, please make it public.

**Comment by pyfrid** [comment] 2015-10-26 21:10
sorry
https://drive.google.com/file/d/0B47IF5KCd6h0Mjc4V19QSVljbWs/view?usp=sharing

**Comment by dessant** [comment] 2015-10-27 14:38
There seems to be a very high number of clock calls, some of the core devs looked into it, but i'm not sure if a possible cause was found.

@kived, @tshirtman, @Kovak: what could cause this?

**Comment by Kovak** [comment] 2015-10-27 18:40
Can you post the .config for your computer? This could be that fps has been set to a very large number forcing way too many updates. For comparison in a 13 second run on my computer we see ~1000 clock iterations, you are seeing ~80,000. Even if we were executing a clock schedule at 60 fps we would only see 36,000 calls, and touchtracer does not try to do so much work as to even need that rate of update.

**Comment by pyfrid** [comment] 2015-10-27 21:21
My FPS limit was set to 0, i.e. unlimited. When I set it to 60 fps, CPU usage is normal. I think it must be better clarified in settings widget, that unlimited FPS can cause high CPU load. I change it couple of months ago just for trying and forgot immediately because there was no performance change.

**Closed** 2015-11-19 22:55 UTC
Labels: documentation
