### ISSUE TITLE
ScrollView: Horizontal scrolling using Shift + Mousewheel

### ISSUE THREAD

**Issue by Alspb** [kivy/kivy#7238] opened 2020-11-28 00:47 UTC
**Feature request**
It would be convenient to scroll horizontally in ScrollView using Shift + Mousewheel (holding Shift and using mousewheel to scroll), as is typical for many apps (browsers, Excel, etc.).

**Comment by Julian-O** [comment] 2023-11-02 03:15
#8022 is a duplicate of this, but has a PR, so I am closing this one.

**Closed by Julian-O** 2023-11-02 03:15 UTC
Labels: Type: Feature, Priority: Medium
