### ISSUE TITLE
Kivy 1.10 GstPlayerException: Unable to create a playbin (one more)

### ISSUE THREAD

**Issue by perceptualJonathan** [kivy/kivy#5886] opened 2018-08-05 06:00 UTC
### Versions

* Python: 2.7.6
* OS: El Capitan
* Kivy: 1.10.1
* Kivy installation method: pip

### Description

When running the example file examples/demo/kivycatalog/main.py, the GstPlayerException: Unable to create a playbin error gets raised. I had run this file with no problems in earlier versions of Kivy, but when I run the file under Kivy 1.10.1, I get this error. I have seen various other reports on this error, such as #5203, and also [the Google group](https://groups.google.com/forum/#!topic/kivy-users/LJrQGiN773A); however, the recommended fix of ```brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-ffmpeg010``` hasn't solved the problem for me. One consideration that I've observed is that Kivy is running Gstreamer 1.10.4, but brew is pouring Gstreamer 1.14.2. If that's a potential problem, would there be a reason why Kivy isn't finding a more recent Gstreamer version?

### Code and Logs

```python
[INFO   ] [Logger      ] Record log in /Users/KeikiHekili/.kivy/logs/kivy_18-08-05_3.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v2.7.6 (default, Jun 30 2014, 17:05:37) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <2.1 INTEL-10.0.52>
[INFO   ] [GL          ] OpenGL vendor <Intel Inc.>
[INFO   ] [GL          ] OpenGL renderer <Intel HD Graphics 3000 OpenGL Engine>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [VideoGstplayer] Using Gstreamer 1.10.4.0
[INFO   ] [Video       ] Provider: gstplayer
[WARNING] [Image       ] Unable to load image </Users/KeikiHekili/Documents/examples1.9/widgets/softboy.mpg>
[ERROR  ] [Image       ] Error loading texture ../../widgets/softboy.mpg
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 
 Traceback (most recent call last):
   File "/Users/KeikiHekili/Documents/examples1.9/demo/kivycatalog/main.py", line 191, in <module>
     KivyCatalogApp().run()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/uix/video.py", line 183, in _do_video_load
     self._video = CoreVideo(filename=filename, **self.options)
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/video/video_gstplayer.py", line 56, in __init__
     super(VideoGstplayer, self).__init__(**kwargs)
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/video/__init__.py", line 84, in __init__
     self.filename = kwargs.get('filename')
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/video/__init__.py", line 116, in <lambda>
     lambda self, x: self._set_filename(x),
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/video/__init__.py", line 113, in _set_filename
     self.load()
   File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/kivy/core/video/video_gstplayer.py", line 68, in load
     self.player.load()
   File "kivy/lib/gstplayer/_gstplayer.pyx", line 233, in kivy.lib.gstplayer._gstplayer.GstPlayer.load
 GstPlayerException: Unable to create a playbin
```

**Comment by linwenchao** [comment] 2018-08-16 19:37
same error here

**Comment by matham** [comment] 2018-08-17 00:44
You should probably look into into setting `GST_PLUGIN_PATH` and/or `GST_REGISTRY`. Also, `GST_REGISTRY_FORK` may or may not be relevant.

**Comment by KeikiHekili** [comment] 2018-08-17 15:02
@matham what should I set them to? What would the command look like?

**Comment by matham** [comment] 2018-08-17 17:54
I'm not really sure because I'm not on osx. You can read more about these variables here: https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gst-running.html. But specifically try setting `GST_REGISTRY` with e.g. `export GST_REGISTRY=~/registry.bin` or some other path. 

There may be other variables on the listed page that could solve this, but essentially, this is a gstreamer and not kivy problem so you may try searching for this error on google.

**Comment by KeikiHekili** [comment] 2018-08-22 17:51
It appears that the issue is related to kivy.lib.gstreamer.__init__.py loading kivy.lib.gstreamer._gstreamer.so as opposed to a different gstreamer version from brew.

**Comment by physicsninja** [comment] 2018-10-19 01:49
I have encountered the same issue. The only difference in my setup compared to @KeikiHekili is that I am using python 3.7. Otherwise I generate the same errors.

**Comment by KeikiHekili** [comment] 2018-10-19 04:45
@physicsninja did you also have no problems with gstreamer in Kivy 1.10.0, 1.9, etc. but then the problems flared up in 1.10.1?

**Comment by physicsninja** [comment] 2018-10-19 14:46
I am new to kivy so I haven't used any earlier versions. I tried to compile an earlier version to test if indeed that would be the case for me but I have been having little success due to what appear to bugs in cython

**Comment by sgpy** [comment] 2019-02-23 16:09
Is there a fix for this item? using __py37__.

**Comment by ElliotGarbus** [comment] 2023-11-29 23:02
@Julian-O I recommend closing this issue.
I ran the kivy catalog on MacOS Catalina 10.15.7 with no issue using Kivy V2.2.1 with python 3.9.13

**Comment by Julian-O** [comment] 2023-11-30 02:05
Closing as duplicate of #6521

**Closed by Julian-O** 2023-11-30 02:05 UTC
Labels: Platform: OSX, Status: Needs-analysis
