### ISSUE TITLE
textinput bug with swipe typing

### ISSUE THREAD

**Issue by eulerreich** [kivy/kivy#1773] opened 2014-01-16 12:10 UTC
I'm on android 4.3 with cyanogenmod, using the AOSP keyboard.

In a TextInput, if I type "hello" by swiping, the output is ``hello``. If I then follow it immediately by "world" by swiping, the total output so far is ``helloworld``. If I then tap another key, say "y", the output becomes ``helloworldworld y``.

So 2 things are wrong: 1) there should be a space between ``hello`` and ``world``, or even better, let there be an option for whether to auto-insert spaces between swiped words. 2) the more egregious: ``world`` shouldn't be repeated when I tap another key.

This happens in my own app and also with the kivy showcase.

**Comment by merriam** [comment] 2015-03-07 06:18
Right.  I think I found this as an error down in kivy/behaviors.py/select_with_key_down().  Basically, time.clock() was used instead of time.time(), which meant the 'delay' for keys being different words never triggered.   Might be fixed shortly.

**Comment by akshayaurora** [comment] 2015-03-07 09:57
@merriam behaviours have nothing to do with how input is handled through android IME's you might want to look in here https://github.com/kivy/python-for-android/blob/master/src/src/org/renpy/android/SDLSurfaceView.java#L1075 this is where input from IME is handled and passed onto kivy text input

**Comment by merriam** [comment] 2015-03-09 19:15
@akshayaurora  Thank you, I was incorrect.   I was trying to find an already submitted bug for the fix here:
https://github.com/merriam/kivy/commit/d735622ad5802d6d42a2a739ab83a7521a34e6d4

I will submit a fresh bug.

**Comment by dessant** [comment] 2016-04-13 06:33
Duplicate of https://github.com/kivy/kivy/issues/3284.

**Closed by dessant** 2016-04-13 06:33 UTC
Labels: widgets
