### ISSUE TITLE
kvlang comment causes unexpected crash

### ISSUE THREAD

**Issue by ghost** [kivy/kivy#5257] opened 2017-07-04 11:51 UTC
### Versions

* Python: 3.6.1
* OS: Win 8.1 pro
* Kivy: 1.10
* Kivy installation method: pip

### Description

Comment following ``on_event:`` crashes application in a multiline (indented) callback

### Code and Logs

```python
from kivy.base import runTouchApp
from kivy.lang import Builder

runTouchApp(Builder.load_string('''
Button:
    on_press: # ninja comment
        print("hello")
'''))
```

```
 Traceback (most recent call last):
   File "test.py", line 8, in <module>
     '''))
   File "C:\python36\lib\site-packages\kivy\lang\builder.py", line 350, in load_string
     parser = Parser(content=string, filename=fn)
   File "C:\python36\lib\site-packages\kivy\lang\parser.py", line 392, in __init__
     self.parse(content)
   File "C:\python36\lib\site-packages\kivy\lang\parser.py", line 501, in parse
     objects, remaining_lines = self.parse_level(0, lines)
   File "C:\python36\lib\site-packages\kivy\lang\parser.py", line 664, in parse_level
     if current_property[:3] == 'on_':
 TypeError: 'NoneType' object is not subscriptable
```

**Comment by KeyWeeUsr** [comment] 2017-07-05 11:23
Similar to #4415

**Comment by Julian-O** [comment] 2023-11-07 15:39
Marking this as duplicate of #6657 (even though it is earlier)

**Closed by Julian-O** 2023-11-07 15:39 UTC
