### ISSUE TITLE
Weird scrollview when i scroll with my touchpad

### ISSUE THREAD

**Issue by optivlad** [kivy/kivy#6600] opened 2019-11-15 14:10 UTC
### Versions

* Python: 3.7
* OS: Windows 10 familly
* Kivy:  1.11.1
* Kivy installation method: use documentation

### Description

When i scroll in scrollview with my touchpad it goes to bottom again.
i'll do a test in kivy/input/providers/mouse.py but if other people can help me thank you

### Code and Logs

```python

from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

KV = """
<YouTuber>:
    BoxLayout:
         orientation:"horizontal"
    BoxLayout:
        orientation:"vertical"
    ScrollView:
        do_scroll_y: True
        pos_hint: {'top': 1}
        bar_width: 8
        bar_color: 1, 0, 0, 1
        scroll_type: ['bars']
    Label:
        size_hint_y: None
        text:"test"
        height: 2100
"""

Builder.load_string(KV)

class YouTuber(BoxLayout):
    pass

class MainApp(App):
    def build(self):
        self.m = YouTuber()
        return self.m

MainApp().run() 

```

**Comment by optivlad** [comment] 2019-11-15 18:09
It seem don't detect touchpad release (my scrollview widget scrollbar still active)
and so scroll down alone

**Comment by optivlad** [comment] 2019-11-18 16:51
Maybe found error that i see with "print()" bad scrollbar event in mouse.py when i touch off my touchpad maybe thread ending problem So hard for me. I test my code on 2 Windows10 computer it's same problem

**Comment by MisterNox** [comment] 2020-04-21 06:43
I can confirm this behaviour. WIth the scroll wheel of the mouse everything works fine, but with the touchpad it always tries to further scroll down. I am using kivy with windows 10 as well. Tested it on two laptops with the same result. So it seems to be a general problem.

**Comment by clorax** [comment] 2020-05-23 20:32
I am also experiencing the same issue on Windows 10.  Scrolling with the mouse works fine, scrolling with two finger swipe on the touchpad works when scrolling down, but will not scroll up correctly.

**Comment by snuq** [comment] 2020-08-24 02:14
Been running into this bug too, seems to be new to kivy 1.11, it does not happen in 1.10.
Also, it does not appear related to the scrollview python file itself, i tried replacing that with the kivy 1.10 version, and it still scrolls oddly... so apparently its due to how the scroll is being caught before it reaches the scrollview (the touch event?).

**Comment by SPEARTECH** [comment] 2020-09-04 19:17
I have the same exact issue. 
-Two finger touchpad scroll: scrolls to bottom and cannot scroll up.
-Track-point scrolling: Works fine.
-Mouse wheel scrolling: Works fine.

I am using Kivy 2.0.0rc3 with Python3, Windows 10, Lenovo laptop.

**Comment by VictorManhani** [comment] 2020-09-25 15:24
Hello people, I have the same problem with my laptop touchpad, basically I need to scrollup and I can't.

I am using kivy 1.11.1, python 3.7.7, Windows 10 and a Lenovo laptop.

I tried to solve this problem, but was not successful, follow my analysis code:

```
from kivy.app import App
from kivy.lang import Builder
from kivy.factory import Factory
from kivy.uix.scrollview import ScrollView
from kivy.core.window import Window

class MainApp(App):
    scroll = None
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def _scroll(self, obj, motion):
        try:
            print("#############################################")
            print(motion.dsy, "dsy")
            print(motion.dy, "dy")
            print(motion.is_mouse_scrolling, "is_mouse_scrolling")
            print(motion.is_touch, "is_touch")
            print(motion.osy, "osy")
            print(motion.oy, "oy")
            print(motion.psy, "psy")
            print(motion.py, "py")
            print(motion.sy, "sy")
            print(motion.y, "y")
            print(motion.button, "button")
            print(motion.device, "device")
            print(self.scroll.scroll_y, "scroll_y")
            print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
        except:
            pass

    def build(self):
        self.scroll = Factory.ScrollView(
            do_scroll_x = False, 
            do_scroll_y = True, 
            scroll_type = ["bars", "content"]
        )
        self.scroll.bind(on_scroll_start=self._scroll)

        container = Builder.load_string("""
BoxLayout:
    id: container
    orientation: "vertical"
    size_hint: [1, None]
    height: self.minimum_height
""")

        for i in range(50):
            but = Factory.Button(text = str(i), size_hint_y = None, height = 60)
            container.add_widget(but)

        self.scroll.add_widget(container)
        return self.scroll

MainApp().run()
```

With this code you can follow the problem in some more superficial way, I believe the problem is in the capture of the scroll of the laptop's touchpad by kivy.

I think that the problem itself occurs because when we move the ScrollView through the touchpad it increases the scroll_y more than necessary, and this is a problem that occurs before with the management of the event that comes from the touchpad.

You can notice that when moving with the mouse scroll, it works very well, since the scroll_y is incremented and decremented only as necessary.

Thinking about it, I tried to correct this by masking these events that come from the touchpad to the scrollview.

In ScrollView there is the on_scroll_start function that is called every time we scroll through the mouse or touchpad.

Soon:
* If you slide the touchpad forward, it releases the scrollup event that scrolls down.

* If we slide the touchpad backwards, it releases the scrolldown event on the scrollview.

Thus, the problem also occurs because the kivy receives the event from the touchpad and internally there is some confusion that recognizes any movement on the touchpad as scrollup.

I was not able to solve this problem, but I leave my analysis in relation to that.

**Comment by optivlad** [comment] 2021-01-31 16:21
Up ? I update to python 3.9.1 / kivy 2.0.0 and problem wasn't solved, i need superkivyman to fixed it please 👍 

Thank you very much

**Comment by matham** [comment] 2021-01-31 19:37
I believe this should be fixed in master with https://github.com/kivy/kivy/pull/7279. So try master and see if it fixes it.

**Comment by optivlad** [comment] 2021-01-31 21:21
Yeah it's perfect ! Solved
Thank you So much, specialy teeshirtman 😉
Just waiting to have 2.1.0 to stable branch

**Closed** 2021-01-31 21:44 UTC
