### ISSUE TITLE
Audio and Video Streaming issue on Android

### ISSUE THREAD

**Issue by aarondiazr** [kivy/kivy#4242] opened 2016-04-29 03:42 UTC
Hi!

I'm trying to test a video player on android, with mp3 and mp4 files from urls, on Desktop works fine, but in android only shows loading gif. I add ffmpeg in list requeriments of buildozer.spec, but not chances anything. 

Is a bug or player streaming not work on android platform?

Thanks!

**Comment by dessant** [comment] 2016-04-29 08:25
@aarondiazr, could you share a minimal app example that reproduces the issue, and the buildozer spec?

**Comment by aarondiazr** [comment] 2016-04-29 12:39
Thanx!

Example app:
```python
import kivy

from kivy.app import App
from kivy.uix.label import Label
from kivy.lang import Builder
from kivy.properties import ObjectProperty
from kivy.uix.videoplayer import VideoPlayer


class ExampleApp(App):

    def build(self):
        player = VideoPlayer(source='http://vjs.zencdn.net/v/oceans.mp4', state='stop', options={'eos': 'loop'})
        player.volume = 1
        return player


if __name__ == '__main__':
    ExampleApp().run()
```

buildozer.spec
```
[app]

# (str) Title of your application
title = Example kivy

# (str) Package name
package.name = example

# (str) Package domain (needed for android/ios packaging)
package.domain = com.ironsistem

# (str) Source code where the main.py live
source.dir = .

# (list) Source files to include (let empty to include all the files)
#source.include_exts = 

# (list) Source files to exclude (let empty to not exclude anything)
#source.exclude_exts = spec

# (list) List of directory to exclude (let empty to not exclude anything)
#source.exclude_dirs = tests, bin

# (list) List of exclusions using pattern matching
#source.exclude_patterns = license,images/*/*.jpg

# (str) Application versioning (method 1)
version = 0.1

# (str) Application versioning (method 2)
# version.regex = __version__ = ['"](.*)['"]
# version.filename = %(source.dir)s/main.py

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy, ffmpeg, sqlite3, openssl

# (str) Custom source folders for requirements
# Sets custom source for any requirements with recipes
# requirements.source.kivy = ../../kivy

# (list) Garden requirements
#garden_requirements =

# (str) Presplash of the application
#presplash.filename = %(source.dir)s/data/presplash.png

# (str) Icon of the application
#icon.filename = %(source.dir)s/data/icon.png

# (str) Supported orientation (one of landscape, portrait or all)
orientation = portrait

#
# OSX Specific
#

#
# author = © Copyright Info

#
# Android specific
#

# (bool) Indicate if the application should be fullscreen or not
fullscreen = 1

# (list) Permissions
android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE

# (int) Android API to use
android.api = 19

# (int) Minimum API required
android.minapi = 9

# (int) Android SDK version to use
android.sdk = 20

# (str) Android NDK version to use
android.ndk = 9c

# (bool) Use --private data storage (True) or --dir public storage (False)
#android.private_storage = True

# (str) Android NDK directory (if empty, it will be automatically downloaded.)
#android.ndk_path =

# (str) Android SDK directory (if empty, it will be automatically downloaded.)
#android.sdk_path =

# (str) ANT directory (if empty, it will be automatically downloaded.)
#android.ant_path =

# (str) python-for-android git clone directory (if empty, it will be automatically cloned from github)
#android.p4a_dir =

# (list) python-for-android whitelist
#android.p4a_whitelist =

# (str) Android entry point, default is ok for Kivy-based app
#android.entrypoint = org.renpy.android.PythonActivity

# (list) List of Java .jar files to add to the libs so that pyjnius can access
# their classes. Don't add jars that you do not need, since extra jars can slow
# down the build process. Allows wildcards matching, for example:
# OUYA-ODK/libs/*.jar
#android.add_jars = foo.jar,bar.jar,path/to/more/*.jar

# (list) List of Java files to add to the android project (can be java or a
# directory containing the files)
#android.add_src =

# (str) python-for-android branch to use, if not master, useful to try
# not yet merged features.
#android.branch = master

# (str) OUYA Console category. Should be one of GAME or APP
# If you leave this blank, OUYA support will not be enabled
#android.ouya.category = GAME

# (str) Filename of OUYA Console icon. It must be a 732x412 png image.
#android.ouya.icon.filename = %(source.dir)s/data/ouya_icon.png

# (str) XML file to include as an intent filters in <activity> tag
#android.manifest.intent_filters =

# (list) Android additionnal libraries to copy into libs/armeabi
#android.add_libs_armeabi = libs/android/*.so
#android.add_libs_armeabi_v7a = libs/android-v7/*.so
#android.add_libs_x86 = libs/android-x86/*.so
#android.add_libs_mips = libs/android-mips/*.so

# (bool) Indicate whether the screen should stay on
# Don't forget to add the WAKE_LOCK permission if you set this to True
#android.wakelock = False

# (list) Android application meta-data to set (key=value format)
#android.meta_data =

# (list) Android library project to add (will be added in the
# project.properties automatically.)
#android.library_references =

#
# iOS specific
#

# (str) Name of the certificate to use for signing the debug version
# Get a list of available identities: buildozer ios list_identities
#ios.codesign.debug = "iPhone Developer: <lastname> <firstname> (<hexstring>)"

# (str) Name of the certificate to use for signing the release version
#ios.codesign.release = %(ios.codesign.debug)s


[buildozer]

# (int) Log level (0 = error only, 1 = info, 2 = debug (with command output))
log_level = 2

# (int) Display warning if buildozer is run as root (0 = False, 1 = True)
warn_on_root = 1


#    -----------------------------------------------------------------------------
#    List as sections
#
#    You can define all the "list" as [section:key].
#    Each line will be considered as a option to the list.
#    Let's take [app] / source.exclude_patterns.
#    Instead of doing:
#
#[app]
#source.exclude_patterns = license,data/audio/*.wav,data/images/original/*
#
#    This can be translated into:
#
#[app:source.exclude_patterns]
#license
#data/audio/*.wav
#data/images/original/*
#


#    -----------------------------------------------------------------------------
#    Profiles
#
#    You can extend section / key with a profile
#    For example, you want to deploy a demo version of your application without
#    HD content. You could first change the title to add "(demo)" in the name
#    and extend the excluded directories to remove the HD content.
#
#[app@demo]
#title = My Application (demo)
#
#[app:source.exclude_patterns@demo]
#images/hd/*
#
#    Then, invoke the command line with the "demo" profile:
#
#buildozer --profile demo android debug
```

**Comment by tomatoes-prog** [comment] 2020-11-06 13:13
Same problem here, did you solve the problem?

**Comment by matham** [comment] 2020-11-06 16:37
I'm closing this because ffmpeg has been deprecated. Instead ffpyplayer should be used on android.

**Closed by matham** 2020-11-06 16:37 UTC
Labels: Status: Needs-analysis

**Comment by Sahil-pixel** [comment] 2020-11-06 18:18
see  video on Android with Kivy 
https://youtu.be/PfXgbIcLhbA

**Comment by tomatoes-prog** [comment] 2020-11-06 20:41
> see video on Android with Kivy 😁😁😁
> https://youtu.be/PfXgbIcLhbA

Do u know if this works with url links?

**Comment by Sahil-pixel** [comment] 2020-11-06 21:31
requirements = hostpython3==3.7.5,python3==3.7.5,kivy,libshine,libx264,ffpyplayer,ffpyplayer_codecs,certifi

**Comment by tomatoes-prog** [comment] 2020-11-07 05:25
Not solution yet :( the video now takes the sound in the background with your requirements, but i dont know if i am still missing something

**Comment by sandeshchand87** [comment] 2022-09-14 10:29
> libx264

buildozer throws an compilation error while installing ffpyplayer_codecs. how to solve this issue.
