### ISSUE TITLE
Can not install kivy on macOS - SDL2 error

### ISSUE THREAD

**Issue by Zujiry** [kivy/kivy#5818] opened 2018-06-22 08:34 UTC
### Versions

Python: 3.6.5
OS: macOS Sierra 10.12.6
Kivy: latest stable
Kivy installation method: homebrew with pip

### Description

Even though I tried all the steps in #5653  I have the same problem still.
I can not install kivy

### Code and Logs

The error (-end, as there are many)
```python
In file included from /private/var/folders/85/ndbqsh5n5s79pz0564vvbvcr0000gn/T/pip-D5TGyb-build/kivy/core/text/_text_sdl2.c:485:
In file included from /Library/Frameworks/SDL2_image.framework/Headers/SDL_image.h:27: In file included from /usr/local/include/SDL2/SDL.h:36:
In file included from /usr/local/include/SDL2/SDL_audio.h:32: /usr/local/include/SDL2/SDL_error.h:59:5: error:
redefinition of enumerator 'SDL_EFWRITE' SDL_EFWRITE, ^ /Library/Frameworks/SDL2.framework/Headers/SDL_error.h:59:5: note: previous definition is here SDL_EFWRITE, ^ 
fatal error: too many errors emitted, stopping now [-ferror-limit=] 20 errors generated. error: command 'clang' failed with exit status 1
```

**Comment by tito** [comment] 2018-10-04 09:38
Duplicate of #5653

**Closed by tito** 2018-10-04 09:38 UTC

**Comment by tito** [comment] 2018-10-04 09:39
Sorry, the #5623 reference it, but it is a new one.
