### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by pilotkid** [kivy/kivy#3309] opened 2015-04-28 01:11 UTC
Hello the error code I am getting is : 
     
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-       PG4g5k/kivy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'),      __file__, 'exec'))" install --record /tmp/pip-K9ESpR-record/install-record.txt --single-version-externally-    managed --compile" failed with error code 1 in /private/tmp/pip-build-PG4g5k/kivy```

**Comment by skyline75489** [comment] 2015-04-28 02:32
Same here. 

    clang: error: no such file or directory: '/private/tmp/pip-build-O7Lk_7/kivy/kivy/core/camera/camera_avfoundation_implem.m'
    clang: error: no input files
     error: command 'cc' failed with exit status 1

**Comment by wiyarmir** [comment] 2015-05-06 10:08
Same error here on OS X Yosemite. Tried both with built-in python and brew's python.

**Comment by SuperFoodIQ** [comment] 2015-05-26 20:57
AVFoundation has never worked properly w/ MacOSX.  Either you can get the MacOSX installer from the kivy website that is provided in a .dmg or if you are trying to build, do the following.  I believe the last time they pushed out the latest version MacOSX was at platform 10, 7 ? Date looks about right...

This is what I did to build from source -- (Do the obvious & make sure xcode is at latest, etc..)
1:)  git clone http://github.com/kivy/kivy 
2:)  cd kivy
3:) vi setup.py 
4:) :712  (go to line 712) and you will see this 
if mac_ver >= [10, 7]:  
Comment out this line w/ a # 
and set to 1 platform version higher so change the [10, 7] to [10, 11] if on yosemite.

To determine your mac_ver use the above line in a simple python script:

import platform as _platform
mac_ver = [int(x) for x in _platform.mac_ver()[0].split('.')[:2]]
print mac_ver

What ever is returned go up a level and update the setup.py to that or make sure that 'use_avfoundation' returns  false/0

5:) make 
6:) if no further errors make install

Fixed... I am doing more investigation around avfoundation and seeing if I can fix what is broken.  If I can I will come back and let you all know..

End result:

running install_egg_info
Writing /Library/Python/2.7/site-packages/Kivy-1.9.1_dev-py2.7.egg-info

**Comment by SuperFoodIQ** [comment] 2015-05-26 21:18
From what I read from the header files in:

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/QD.framework/Headers

ColorSyncDeprecated.h shows that this functionality has been deprecated since 10.6, I think in setup.py this is a bug and the eval should be:

if mac_ver < [10, 7]:

Other wise you would need to use the new API to accomplish these tasks and the only documentation of this functionality that I could find was in the actual header files themselves.  I think this is a bug for the kivy team. I will open a bug and see what they say.

**Comment by andreif** [comment] 2015-05-28 08:23
@SuperFoodIQ thanks! I was lucky to get this error few hours after you posted the fix, saved me some time. However, even after installing pillow and pygame I failed to get the example from the homepage to work on osx+py3.5.

**Comment by SuperFoodIQ** [comment] 2015-06-01 04:52
There are some bugs still w/ python3 from what I understand after reading some reddit posts.  I really want to change the kivy file format to native JSON. It would be really nice if you could generate the kivy customization files accurately...  In my case I want to be able to customize my UI and build custom screens for clients so the requirements would change and using say a jenkins job to generate the UI would be really slick. Don't get me wrong it is possible in the current kivy format but, it would be nice if this was based on a standard and you could have some kind of validation via templates.

The whole avfoundation is b0rked after 10.6 as I stated.  I updated the bug on the kivy bugtracker and pointed them in the right direction.

If you are still getting this error let me know and I can dig further if you need assistance.

**Comment by cbenhagen** [comment] 2015-11-19 23:22
This is a duplicate of https://github.com/kivy/kivy/issues/3320 which has been fixed by https://github.com/kivy/kivy/commit/e56d44feeac37ed9f433afe5c59b0fa938f33216

The fix has not been released to pypi yet (https://github.com/kivy/kivy/issues/3717) so you have to install with
```
pip install git+https://github.com/kivy/kivy.git@1.9.0
```
or if using homebrew with
```
USE_OSX_FRAMEWORKS=0 pip install git+https://github.com/kivy/kivy.git@1.9.0
```

**Closed** 2015-11-20 00:06 UTC
Labels: platform-osx

**Comment by SuperFoodIQ** [comment] 2015-11-23 19:31
Python3 is not supported as of yet... Please read the requirements
carefully and do not just assume that py3 is supported!

I know there is extensive development around the py3 platform..

-luke
