### ISSUE TITLE
Cannot upgrade kivy to latest version

### ISSUE THREAD

**Issue by AFAgarap** [kivy/kivy#4155] opened 2016-04-06 17:47 UTC
I tried the following code solution, but it fails to upgrade kivy.
`sudo pip3 install --upgrade kivy`
## Screenshot

![deepinscreenshot20160407014646](https://cloud.githubusercontent.com/assets/11130276/14326922/a6b2d6b6-fc62-11e5-9d10-582b08c304ed.png)

**Comment by thopiekar** [comment] 2016-04-06 18:27
The compiler almost says what's missing on your machine...
```GL/gl.h``` is missing and depending on your OS you'll need to install these OpenGL headers in order to build kivy :wink:

**Comment by AFAgarap** [comment] 2016-04-07 03:41
Thank you. I already installed the OpenGL. I successfully upgraded Kivy to 1.9.1 as well. I upgraded the Kivy installed in my computer since it's the suggested solution to my original problem in issue #4123 
After upgrading Kivy to 1.9.1, the problem still arises.

Screenshot
--
![deepinscreenshot20160407113638](https://cloud.githubusercontent.com/assets/11130276/14339986/6d0b841e-fcb5-11e5-8c55-a19b97f0e47d.png)

**Comment by thopiekar** [comment] 2016-04-17 08:21
I see no output of the SDL module here again. I also saw this here https://github.com/kivy/kivy/issues/3002#issuecomment-210906292
If that person also uses a non-xUbuntu distribution that it could be related to changes made by the maintainers of the distribution. I can't reproduce it here on my Kubuntu system.

**Comment by abhigenie92** [comment] 2016-04-17 08:37
Provided details as per https://github.com/kivy/kivy/issues/3002#issuecomment-210974766
```
abhigenie92@ubuntu:~$ dpkg-architecture
DEB_BUILD_ARCH=amd64
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=amd64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=x86_64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=x86_64-linux-gnu
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
DEB_HOST_ARCH=amd64
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=x86_64-linux-gnu
DEB_HOST_MULTIARCH=x86_64-linux-gnu
DEB_TARGET_ARCH=amd64
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=amd64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=x86_64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=x86_64-linux-gnu
DEB_TARGET_MULTIARCH=x86_64-linux-gnu
abhigenie92@ubuntu:~$ glxinfo | grep "direct rendering"
direct rendering: Yes
abhigenie92@ubuntu:~$ glxinfo | grep "OpenGL"
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on SVGA3D; build: RELEASE;  
OpenGL version string: 2.1 Mesa 10.5.9
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 10.5.9
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
abhigenie92@ubuntu:~$ 
```

**Comment by thopiekar** [comment] 2016-04-17 08:47
@AFAgarap Please open a python interpreter by ```python``` for example and run ```import kivy.core.window._window_sdl2```. It should open an empty/transparent window and you should be only able to close it via [CTRL]-D at the python interpreter.

The output should look like:
```thopiekar@home:[...]$ python 
Python 2.7.11+ (default, Mar 30 2016, 21:00:42) 
[GCC 5.3.1 20160330] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy.core.window._window_sdl2
[INFO   ] [Logger      ] Record log in /home/thopiekar/.kivy/logs/kivy_16-04-17_1.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11+ (default, Mar 30 2016, 21:00:42) 
[GCC 5.3.1 20160330]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <4.5.0 NVIDIA 361.42>
[INFO   ] [GL          ] OpenGL vendor <NVIDIA Corporation>
[INFO   ] [GL          ] OpenGL renderer <GeForce GT 720/PCIe/SSE2>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <4.50 NVIDIA>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
>>>

I hope we can force an error message with that.

**Comment by abhigenie92** [comment] 2016-04-17 08:51
@thopiekar I tried that : 
```
(noteapp_env)abhigenie92@ubuntu:~/dev_work/2_Paint/build_linux$ python
Python 2.7.11 (default, Apr 16 2016, 14:08:48) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import kivy.core.window._window_sdl2
[INFO   ] [Logger      ] Record log in /home/abhigenie92/.kivy/logs/kivy_16-04-17_3.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11 (default, Apr 16 2016, 14:08:48) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] OpenGL version <2.1 Mesa 10.5.9>
[INFO   ] [GL          ] OpenGL vendor <VMware, Inc.>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on SVGA3D; build: RELEASE;  >
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
>>>  
(noteapp_env)abhigenie92@ubuntu:~/dev_work/2_Paint/build_linux$ 

```

**Comment by thopiekar** [comment] 2016-04-17 08:52
Did you see anything? Does the window appear?

**Comment by abhigenie92** [comment] 2016-04-17 08:55
@thopiekar  Yes, the windows appears to fine
![screenshot from 2016-04-17 01 54 28](https://cloud.githubusercontent.com/assets/12474640/14586033/6116e9b4-043f-11e6-999d-fb6864258ccc.png)

**Comment by thopiekar** [comment] 2016-04-17 08:56
Then I don't get why kivy can't find the SDL2 window provider when running an own script.
This doesn't make any sense to me :disappointed:

**Comment by abhigenie92** [comment] 2016-04-17 09:04
Posting error:
My aim here to package for linux using pyinstaller. I am unable to import the hooks.
https://kivy.org/docs/guide/packaging-windows.html#packaging-a-simple-app

```
(noteapp_env)abhigenie92@ubuntu:~/dev_work$ python
Python 2.7.11 (default, Apr 16 2016, 14:08:48) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.tools.packaging.pyinstaller_hooks import install_hooks
[INFO   ] [Logger      ] Record log in /home/abhigenie92/.kivy/logs/kivy_16-04-17_5.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11 (default, Apr 16 2016, 14:08:48) 
[GCC 4.9.2]
[INFO   ] [Factory     ] 193 symbols loaded
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 ImportError: cannot import name install_hooks
>>> from kivy.deps import sdl2, glew
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 ImportError: cannot import name sdl2
>>> 
```

**Comment by abhigenie92** [comment] 2016-04-17 10:13
I tried to use pip install, but no luck with that:
```
(noteapp_env)abhigenie92@ubuntu:~/dev_work/virtualenvs$ python 
Python 2.7.11 (default, Apr 16 2016, 14:08:48) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from kivy.deps import sdl2, glew
[INFO   ] [Logger      ] Record log in /home/abhigenie92/.kivy/logs/kivy_16-04-17_6.txt
[INFO   ] [Kivy        ] v1.9.2-dev0
[INFO   ] [Python      ] v2.7.11 (default, Apr 16 2016, 14:08:48) 
[GCC 4.9.2]
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 ImportError: cannot import name sdl2
>>>  
 KeyboardInterrupt
>>> 
[1]+  Stopped                 python
(noteapp_env)abhigenie92@ubuntu:~/dev_work/virtualenvs$ pip install kivy.deps.sdl2 kivy.deps.glew \
> kivy.deps.gstreamer --extra-index-url https://kivy.org/downloads/packages/simple/
Collecting kivy.deps.sdl2
  Could not find a version that satisfies the requirement kivy.deps.sdl2 (from versions: )
No matching distribution found for kivy.deps.sdl2
(noteapp_env)abhigenie92@ubuntu:~/dev_work/virtualenvs$ pip install kivy.deps.sdl2 kivy.deps.glew
Collecting kivy.deps.sdl2
  Could not find a version that satisfies the requirement kivy.deps.sdl2 (from versions: )
No matching distribution found for kivy.deps.sdl2
```

**Comment by AFAgarap** [comment] 2016-04-17 14:10
@thopiekar I have no problems with using Python 2.7.11 for Kivy. I want to upgrade to the new version of Kivy for my Python 3.5.1

**Comment by AFAgarap** [comment] 2016-04-17 14:13
![deepinscreenshot20160417221048](https://cloud.githubusercontent.com/assets/11130276/14587672/4cdd6e5a-04e9-11e6-99e3-54fff46577bf.png)
![deepinscreenshot20160417221102](https://cloud.githubusercontent.com/assets/11130276/14587673/4cdd99b6-04e9-11e6-97c6-41a5b68fde4e.png)

**Comment by thopiekar** [comment] 2016-04-17 14:13
Then you want to use pip3 I guess. It is just for the cases if you want at
least python3. On Ubuntu it is in the package called "python3-pip".

**Comment by AFAgarap** [comment] 2016-04-17 14:15
> I tried the following code solution, but it fails to upgrade kivy.
> `sudo pip3 install --upgrade kivy`

**Comment by AFAgarap** [comment] 2016-04-17 14:15
pip3 is what I've been using in the first place

**Comment by thopiekar** [comment] 2016-04-17 15:03
Hmm, ok. In case you want to build Kivy via pip(3) don't forget to install the libsdl2 development files.. Just take ```sudo synaptic``` and search for ```libsdl2``` and install all packages with ```-dev``` suffix.

**Comment by AFAgarap** [comment] 2016-04-17 16:13
Same problem rises.

**Comment by AFAgarap** [comment] 2016-04-17 16:14
I installed all packages with `-dev` suffix from my `libsdl2` search in `synaptic`.

**Comment by AFAgarap** [comment] 2016-07-31 09:45
Hello @thopiekar May I ask if there are developments for the issue I reported?

**Comment by thopiekar** [comment] 2016-07-31 09:52
I'm not familiar with pip, but what I suggest is to remove all pip installations and then retry.

It really should work as this solution can be found in the docs.

**Comment by AFAgarap** [comment] 2016-07-31 12:39
This is a run of a newly-installed `kivy` using `sudo pip3 install kivy` in using a `python3` compiler.

![deepinscreenshot20160731203833](https://cloud.githubusercontent.com/assets/11130276/17276522/cb124bb6-575e-11e6-963e-97b2e6c21200.png)

**Comment by akshayaurora** [comment] 2016-07-31 13:40
@AFAgarap your screenshot shows kivy version 1.9.0 please upgrade to latest one

**Comment by AFAgarap** [comment] 2016-07-31 13:53
@akshayaurora Oh, sorry. My bad. I'll try again.

**Comment by AFAgarap** [comment] 2016-07-31 13:53
@akshayaurora Though that is one issue around here as well. In the past, I couldn't upgrade to latest version of `kivy`.

**Comment by AFAgarap** [comment] 2016-08-01 14:55
@thopiekar No progress. Perhaps kivy is just incompatible with my machine. I have Deepin Linux OS version 15.2
![deepinscreenshot20160801225434](https://cloud.githubusercontent.com/assets/11130276/17298044/f640090e-583a-11e6-8ccb-01a3c3d83773.png)

**Comment by AFAgarap** [comment] 2016-08-01 14:56
@thopiekar Although it is fine with Python 2.7.11 in the same machine. But when I'm using Python 3.5.2, it doesn't work at all. :(

**Comment by akshayaurora** [comment] 2016-08-01 15:12
On Mon, Aug 1, 2016 at 8:26 PM, Abien Fred Agarap <notifications@github.com>
wrote:

> @thopiekar <https://github.com/thopiekar> Although it is fine with Python
> 2.7.11 in the same machine. But when I'm using Python 3.5.2, it doesn't
> work at all. :(
>
> You can not use the same installation on different python versions, kivy
package for python3 would only work with python3, and the version for
python2.x only with python2.x you can't just install py2 version and expect
it to work with py3.

**Comment by AFAgarap** [comment] 2016-08-01 15:21
I'm aware of that. I installed kivy using `sudo pip install kivy` and `sudo pip3 install kivy`. `pip` is for Python 2.x in my machine, while `pip3` is for Python 3.x in my machine

**Comment by AFAgarap** [comment] 2016-08-01 15:24
@akshayaurora Will this information help?
```
darth@darth-pc:~/Documents/Projects/practice-programming-problems/Python$ dpkg-architecture
DEB_BUILD_ARCH=amd64
DEB_BUILD_ARCH_BITS=64
DEB_BUILD_ARCH_CPU=amd64
DEB_BUILD_ARCH_ENDIAN=little
DEB_BUILD_ARCH_OS=linux
DEB_BUILD_GNU_CPU=x86_64
DEB_BUILD_GNU_SYSTEM=linux-gnu
DEB_BUILD_GNU_TYPE=x86_64-linux-gnu
DEB_BUILD_MULTIARCH=x86_64-linux-gnu
DEB_HOST_ARCH=amd64
DEB_HOST_ARCH_BITS=64
DEB_HOST_ARCH_CPU=amd64
DEB_HOST_ARCH_ENDIAN=little
DEB_HOST_ARCH_OS=linux
DEB_HOST_GNU_CPU=x86_64
DEB_HOST_GNU_SYSTEM=linux-gnu
DEB_HOST_GNU_TYPE=x86_64-linux-gnu
DEB_HOST_MULTIARCH=x86_64-linux-gnu
DEB_TARGET_ARCH=amd64
DEB_TARGET_ARCH_BITS=64
DEB_TARGET_ARCH_CPU=amd64
DEB_TARGET_ARCH_ENDIAN=little
DEB_TARGET_ARCH_OS=linux
DEB_TARGET_GNU_CPU=x86_64
DEB_TARGET_GNU_SYSTEM=linux-gnu
DEB_TARGET_GNU_TYPE=x86_64-linux-gnu
DEB_TARGET_MULTIARCH=x86_64-linux-gnu
```

**Comment by balihoo-gens** [comment] 2016-10-18 23:05
see https://github.com/kivy/kivy/issues/4656

**Comment by dessant** [comment] 2016-12-10 11:07
If the bug is still present, please reopen the issue with step by step instructions on how to reproduce it, starting from a fresh OS install.

**Closed by dessant** 2016-12-10 11:07 UTC
Labels: incomplete, needs-analysis, platform-linux, sdl2
