### ISSUE TITLE
Color updating can't keep up

### ISSUE THREAD

**Issue by Leva7** [kivy/kivy#4329] opened 2016-05-28 10:33 UTC
I have a set of custom buttons configured to change color on press and change back on release. However, when I started rapidly clicking on different buttons, some of them kept the "pressed" color, even though the touch event ended.
To demonstrate, [here](http://imgur.com/Guoiz9h) is the expected behaviour and [here](http://imgur.com/z0eilXx) is the actual behaviour
This is the code:
```
from kivy.app import App
from kivy.uix.button import Button
from kivy.uix.boxlayout import BoxLayout

class ColorButton(Button):
    def on_press(self):
        self.color = (0, 1, 0, 1)
    def on_release(self):
        self.color = (1, 1, 1, 1)

class TestApp(App):
    def build(self):
        grid = BoxLayout()
        for i in range(10):
            grid.add_widget(ColorButton(text="test"))
        return grid

TestApp().run()
```

**Comment by dessant** [comment] 2016-05-28 10:42
I'm not able to reproduce it with 1.9.1 and master on windows, could you share the logs?

**Comment by Leva7** [comment] 2016-05-28 10:56
Sorry, I'm using Python 3.4 on Windows with Kivy `v1.9.2-dev-0`

**Comment by KeyWeeUsr** [comment] 2016-06-30 22:59
@dessant Not really sure if it is the same thing, but if you click & hold a button and then move outside of the button area, the text will remain green - `on_touch_up` isn't triggered. Add this to `ColorButton`:

    def on_touch_up(self, touch, *args):
        if super(ColorButton, self).on_touch_up(touch):
            print self

**Comment by dessant** [comment] 2016-06-30 23:23
@KeyWeeUsr, that's because `ButtonBehavior.always_release` is False.

**Comment by KeyWeeUsr** [comment] 2016-06-30 23:37
Oh, so if I imagine right, rapidly clicking includes _at least_ some drag movement and therefore this might be the issue with green text.

**Comment by dessant** [comment] 2016-06-30 23:50
Yeah, probably that's what they've been seeing. Let's close this. :yum:

**Closed by dessant** 2016-06-30 23:50 UTC
Labels: awaiting-reply

**Comment by dessant** [comment] 2016-06-30 23:53
Btw, you can drag, just make sure to not drag outside the button bounds, or set `always_release` to True.
