### ISSUE TITLE
 Attempt to use On-screen keyboard causes UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 389: ordinal not in range(128)

### ISSUE THREAD

**Issue by horsetailfiddlehead** [kivy/kivy#3934] opened 2016-01-22 02:18 UTC
Trying to make a simple login screen using TextInput widgets on the Raspberry Pi (ArchLinux). Everything is fine until I focus on the text widget. Then I got the UnicodeDecodeError (log part replicated):

```
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/core/window/__init__.py", line 1439, in request_keyboard
[WARNING           ] stderr:     vkeyboard = self._vkeyboard_cls()
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/uix/vkeyboard.py", line 352, in __init__
[WARNING           ] stderr:     self._load_layouts()
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/uix/vkeyboard.py", line 418, in _load_layouts
[WARNING           ] stderr:     basename(splitext(fn)[0]))
[WARNING           ] stderr:   File "/usr/lib/python3.5/site-packages/kivy/uix/vkeyboard.py", line 426, in _load_layout_fn
[WARNING           ] stderr:     json_content = fd.read()
[WARNING           ] stderr:   File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
[WARNING           ] stderr:     return codecs.ascii_decode(input, self.errors)[0]
[WARNING           ] stderr: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 389: ordinal not in range(128)
```

 On a hunch, I tracked down the culprit to when the keyboard tries to load the .json file(s) in `vkeyboard.py`:

```
    def _load_layout_fn(self, fn, name):
        available_layouts = self.available_layouts
        if fn[-5:] != '.json':
            return
        with open(fn, 'r') as fd: # <---- fails
            json_content = fd.read()
            layout = loads(json_content)
        available_layouts[name] = layout
```

I was able to eliminate the error by specifying the encoding:

```
with open(fn, 'r', encoding='utf_8') as fd: 
```

Not knowing the details of Kivy or Python too well, can someone with knowledge verify this is a good  fix and incorporate it? Then possibly save others several hours of headaches and despair. :)

**Comment by alexanderweiss** [comment] 2016-12-16 09:21
I've got the same issue, running Kivy on Raspbian Jessie. Specifying UTF-8 encoding as suggested by @horsetailfiddlehead solves it.

**Comment by Julian-O** [comment] 2023-11-12 04:44
This was fixed by February 2017.

Closing as Complete. Let us know if the problem is still present.

**Closed by Julian-O** 2023-11-12 04:44 UTC
