### ISSUE TITLE
ffpyplayer audio inconsistently obeys SoundLoader volume setting

### ISSUE THREAD

**Issue by tmarplatt** [kivy/kivy#6057] opened 2018-11-28 20:46 UTC
### Versions

* Python: 3.5.3
* OS: Windows 7 64-bit
* Kivy: 1.10.1
* Kivy installation method: pip (under virtualenv)

### Description
When using ffpyplayer as audio provider, and I've only tested .ogg Vorbis files, a SoundLoader object ignores the .volume property at the first .play() call. At the next call, it will obey its value, and it will work once more. After that, it seems to ignore .volume again.

I also found out that if you set .volume immediately after calling .play(), it will work the first time, but will still behave inconsistently in subsequent plays.

### Code and Logs
Here's my log and a code sample that reproduces the issue. Note that I am using ffpyplayer because the kivy.deps.sdl2 audio provider will not play .ogg Vorbis files.

https://gist.github.com/tmarplatt/727b5e13dbd0b617582bb15420c2e448

Ogg file tested (or use your own) you can get it from:
https://freesound.org/people/zonkmachine/sounds/164854/

**Comment by tmarplatt** [comment] 2018-11-28 22:56
There is something else about ffpyplayer and ogg files, and please tell me if I should open another issue for it: CPU usage piles up after each sound ends playback. If I run the script above, CPU% increases linearly (in steps of about 16%).

**Comment by ElliotGarbus** [comment] 2023-11-11 00:30
@Julian-O I recommend closing this issue.  I was not able to reproduce the problem.
Win 11, Kivy 2.2.1, Python 3.11.4

I download the audio file the user suggested.  I used the code from the OP and created 2 additional scenarios, I could not replicate the issue.  

```python
# original file
from kivy.app import App
from kivy.core.audio import SoundLoader
from kivy.clock import Clock


class FFPyPlayerTest(App):

    def on_start(self):
        Clock.schedule_once(self.play, 1)

    def play(self, dt):
        self.sound = SoundLoader.load(filename='164854__zonkmachine__bit_bomber3.ogg')
        self.sound.bind(on_stop=self.play_next)
        self.sound.volume = .2
        self.sound.play()

    def play_next(self, *args):
        Clock.schedule_once(self.play, 2)


FFPyPlayerTest().run()
```

```python
# removed loading from the loop
import os
os.environ['KIVY_AUDIO'] = 'ffpyplayer'

from kivy.app import App
from kivy.core.audio import SoundLoader
from kivy.clock import Clock


class FFPyPlayerTest(App):

    def on_start(self):
        self.sound = SoundLoader.load(filename='164854__zonkmachine__bit_bomber3.ogg')
        self.sound.bind(on_stop=self.play_next)
        Clock.schedule_once(self.play, 1)

    def play(self, dt):
        self.sound.play()
        self.sound.volume = .2

    def play_next(self, *args):
        Clock.schedule_once(self.play, 2)


FFPyPlayerTest().run()
```

```python
# gui based test
import os
os.environ['KIVY_AUDIO'] = 'ffpyplayer'

from kivy.app import App
from kivy.core.audio import SoundLoader
from kivy.lang import Builder


kv = """
AnchorLayout:
    BoxLayout:
        size_hint_y: None
        height: dp(48)
        Button:
            text: 'play'
            on_release: app.play()
        ToggleButton:
            text: {'normal': 'loud', 'down': 'soft'}[self.state]
            on_text: app.set_volume(self.text)

"""


class FFPyPlayerTest(App):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.sound = None

    def build(self):
        self.sound = SoundLoader.load(filename='164854__zonkmachine__bit_bomber3.ogg')
        return Builder.load_string(kv)

    def play(self):
        self.sound.play()

    def set_volume(self, text):
        self.sound.volume = 1 if text == 'loud' else 0.2


FFPyPlayerTest().run()
```

**Comment by Julian-O** [comment] 2023-11-11 02:20
@ElliotGarbus: You are a champion! 

Closing as fixed

**Closed by Julian-O** 2023-11-11 02:20 UTC
Labels: Component: core-providers, Status: Needs-analysis
