### ISSUE TITLE
Window goes totally black while resizing it on OS X

### ISSUE THREAD

**Issue by tgrant59** [kivy/kivy#4369] opened 2016-06-05 02:29 UTC
While resizing the window, the entire window goes black. It remains black for as long as the corner of the window is held. Once released, the window redraws and returns. Needless to say this looks awful. Any ideas why this would happen and how to fix it?

Installed with the prebuilt Kivy.app
Using Mac OS X 10.11.5 El Capitan
```
[INFO   ] [Logger      ] Record log in /Applications/Kivy.app/Contents/Resources/.kivy/logs/kivy_16-06-04_5.txt
[INFO   ] [Kivy        ] v1.9.1-dev0
[INFO   ] [Python      ] v2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
[INFO   ] [Factory     ] 179 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] OpenGL version <2.1 INTEL-10.14.66>
[INFO   ] [GL          ] OpenGL vendor <Intel Inc.>
[INFO   ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 6000>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <1.20>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

**Comment by dessant** [comment] 2016-06-05 08:18
Duplicate of https://github.com/kivy/kivy/issues/2844, you can find more details there.

**Closed by dessant** 2016-06-05 08:18 UTC
