### ISSUE TITLE
recent versions of Kivy.app contain a file infected with malware

### ISSUE THREAD

**Issue by gkanarek** [kivy/kivy#5211] opened 2017-06-02 13:51 UTC
I'm aware of this problem in at least the 1.9.1 and 1.10 versions of Kivy.app for python 3. The file Kivy.app/Contents/MacOS/Kivy (a Unix executable with a creation date of April 25, 2015) is infected with the [Backdoor.Eleanor malware](https://blog.malwarebytes.com/cybercrime/2016/07/new-mac-backdoor-malware-eleanor/). 

Here's an analysis of the file: https://www.virustotal.com/en/file/896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb/analysis/1496410669/

**Comment by dessant** [comment] 2017-06-02 14:12
@gkanarek, thanks for the report.
We have stopped serving https://kivy.org/downloads/ while we look into the issue.

**Comment by KeyWeeUsr** [comment] 2017-06-02 16:18
@gkanarek I've uploaded to virustotal [the clean `.dmg` file](https://virustotal.com/en/file/7afa693e825d34bba5972a67593a5d14a810f3f5fab49f48648f88cb8eccf228/analysis/1496418537/) and I got perfect results. If I were you, I'd probably peak into the past and remember if I installed something called [EasyDoc Converter](https://www.macrumors.com/2016/07/06/backdoor-mac-eleanor-faq/)(maybe there's a log somewhere, or maybe it's still installed?)

Or, it might be the [platypus](https://www.jamf.com/jamf-nation/discussions/20521/app-packager-is-being-flagged-as-eleanor-malware) thing, but I don't believe it.

**Comment by gkanarek** [comment] 2017-06-02 16:31
@KeyWeeUsr What I did was download the dmg, mount it, and show the Kivy.app package contents directly off the disk image, without copying to my hard drive. Then I uploaded the "infected file" to virustotal, which resulted in the link I posted above.

**Comment by gkanarek** [comment] 2017-06-02 16:40
@KeyWeeUsr and specifically, I have definitely not installed EasyDoc Converter on this machine. I also checked everywhere else on my machine, and nothing else has the malware.

**Comment by KeyWeeUsr** [comment] 2017-06-02 17:02
Okay, now it makes sense to me:

* [whole app](https://virustotal.com/en/file/102920047878d0c4320196f1e21b6494d9de0d0826654ed29b72f14e929fff37/analysis/1496422195/)(detected)
  * [MacOS subfolder](https://virustotal.com/en/file/4401ba0038b9e8a84f63c314ce7903c9fa21c3ad454faba0e2e9451ad1dde93d/analysis/1496422619/)(detected)

    * [Kivy86](https://virustotal.com/en/file/d2cc3027913853be24b38e9e606c3221ce0b79b74de32c216463fbcafcf21800/analysis/1496422758/)(clean)
    * [Kivy64](https://virustotal.com/en/file/4413eff86e8fdcdf86c2cb3f4c729ba2649c1ed09bf405b7459a51b501eaf977/analysis/1496422820/)(clean)

... or not :D

**Comment by KeyWeeUsr** [comment] 2017-06-02 17:30
Confirmed in py2:

* [Kivy file](https://virustotal.com/en/file/896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb/analysis/1496424510/)
  * [x64](https://virustotal.com/en/file/1f5fe9132f91c0fbcbc0a39be096120b847a95276ad7c421598ae297e7c6f0b4/analysis/1496424496/)
  * [x86](https://virustotal.com/en/file/0055f9e9b12843a2f497635759db5048adeabf2c63370b06dc38dc8b141f3592/analysis/1496424516/)

**Comment by gkanarek** [comment] 2017-06-02 17:32
The fact that it's basically ONLY MacAfee that's flagging these files makes the Platypus thing seem more likely IMO...

**Comment by KeyWeeUsr** [comment] 2017-06-02 17:35
Seems like that after all. Also, it seems like it's the **container** with the detected malware, not the content:

* [Kivy~x86 file(inside Kivy)](https://virustotal.com/en/file/f25e96be65896e7be180441a67151c773b7d41bfe2ef017125d675dadd6287d5/analysis/1496424822/)
* [Kivy~x64 file(inside Kivy)](https://virustotal.com/en/file/a76152b7fbce845dce958601ce8ac724fc448e75f8fff2644093931a5ba63006/analysis/1496424833/)

because when scanned after unpacking and packing into a `.zip`, no such thing is detected.

**Comment by tito** [comment] 2017-06-02 17:40
As i say on IRC, this is weird. The Kivy binary is generated on the fly during packaging.

I did the packaging on a fresh macbook pro (~2 month), with bare minimal environment (nothing related to easydoc).
Quanon did the packaging of Python 3 version.

It would be weird that both have the malware that would infect the binary, just before uploading. I just generated a fresh version of Kivy (by adding exit 0 after https://github.com/kivy/kivy-sdk-packager/blob/master/osx/create-osx-bundle.sh#L24).

**Comment by tito** [comment] 2017-06-02 17:42
If it's the container, it's pure OSX. This may just be a false positive that need to be reported.

**Comment by KeyWeeUsr** [comment] 2017-06-02 17:59
@tito the thing you sent didn't have any of the `x86` or `x64` stuff inside.

**Comment by dessant** [comment] 2017-06-02 20:14
sha256sum for Kivy.app/Contents/MacOS/Kivy:

5f52ce79d5e6d004122bdc2a159d2668024e25412fe1512e878c970084a8446b
Kivy-1.9.0-osx.dmg (py2)
https://drive.google.com/open?id=0By88oIfn3BI4Szkzb1cxMVJ4MUk
(0 / 56) https://www.virustotal.com/en/file/5f52ce79d5e6d004122bdc2a159d2668024e25412fe1512e878c970084a8446b/analysis/

896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb
Kivy-1.9.0-rev3-osx.dmg (py3)
https://drive.google.com/open?id=0B1WO07-OL50_ZmNFTWk0SDgxcEE
(3 / 56) https://www.virustotal.com/en/file/896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb/analysis/


daa1900743fc3b4968f80f80d1a1774d3547f76aa55d5237807f1ae8ac89578a
Kivy-1.9.1-osx-python2.7z (py2)
https://drive.google.com/open?id=0B1WO07-OL50_ejNkZmE4RlJuRGM
(0 / 56) https://www.virustotal.com/en/file/daa1900743fc3b4968f80f80d1a1774d3547f76aa55d5237807f1ae8ac89578a/analysis/

896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb
Kivy-1.9.1-osx-python3.7z (py3)
https://drive.google.com/open?id=0B1WO07-OL50_eGlJaWJYeVdld1U
(3 / 56) https://www.virustotal.com/en/file/896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb/analysis/


896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb
Kivy-1.10.0-osx-python2.dmg (py2)
https://drive.google.com/open?id=0B1WO07-OL50_Zm5udkRUZDNfaTg
(3 / 56) https://www.virustotal.com/en/file/896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb/analysis/

896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb
Kivy-1.10.0-osx-python3.5.dmg (py3)
https://drive.google.com/open?id=0B1WO07-OL50_a3FpU3FQWjctdDg
(3 / 56) https://www.virustotal.com/en/file/896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb/analysis/

**Comment by tito** [comment] 2017-06-02 21:39
@dessant thanks, it's definitively a false positive. So what action can we take?

**Comment by dessant** [comment] 2017-06-03 11:50
@tito, were you able te reproduce this file during a full build?

896c863de42f4ec63a53657ecc5cfbcc780ac60149564e1be40e3899851571bb

**Comment by jerrysoft-x** [comment] 2017-06-04 05:58
Hi, just a suggestion, when stop serving download, please post a notice instead of showing 404...I wanted to report the download issue but luckily I see this.

**Comment by Zen-CODE** [comment] 2017-06-05 06:11
@tito. We would need to submit a False Positive report through McAfee's Service Portal.

https://kc.mcafee.com/corporate/index?page=content&id=KB85567

**Comment by akshayaurora** [comment] 2017-06-05 07:55
Scanning my system with ClamXAV shows a 0 viruses. I am going to try out
Macafee next.

**Comment by tito** [comment] 2017-06-05 16:07
@dessant No, i didn't able to have the same sha256.

My steps:
- I cleaned out the previous build in kivy-sdk-packager
- ./create-osx-bundle.sh
- shasum -a 256 Kivy.app/Contents/MacOS/Kivy -> b876d0000c000ce8e488142431c5a4c39c59b963c33762619712fd50200012e9

Nothing found: https://www.virustotal.com/fr/file/b876d0000c000ce8e488142431c5a4c39c59b963c33762619712fd50200012e9/analysis/1496678235/

- ./create-osx-dmg.sh Kivy.app
- open the dmg
- copy Kivy.app on the Desktop
- sha256 is still the same for ~/Desktop/Kivy.app/Contents/MacOS/Kivy

No clue where the previous file came from, at this point, a hexdiff may help, but i can just ensure that it is generated, not copied from previous generation, if the sdk packager is used. You can see that everytime we bundle, it is generated.

Meanwhile, i'm downloding macaffe for a scan, but i really doubt it would show anything.

Also, please see that: https://www.jamf.com/jamf-nation/discussions/20521/app-packager-is-being-flagged-as-eleanor-malware < it has already been seen by others.

**Comment by dessant** [comment] 2017-06-05 16:44
@tito, thanks for the test.

The odd part is the file hash and modification time has stayed the same since @akshayaurora uploaded it with the [Kivy-1.9.0-rev3-osx.dmg](https://drive.google.com/open?id=0B1WO07-OL50_ZmNFTWk0SDgxcEE) package on April 25, 2015.

Over the years multiple Platypus versions were used to create these packages, and around 6 months ago the system was also fully reinstalled, but this file did not change in new packages. He was able to reproduce the hash today with Platypus 5.0 (this version was used for Kivy 1.10.0) and 5.2.

April 25, 2015 is the file modification time. I couldn't immediately link it to a specific Platypus release, it only coincides with the date the file appeared on our storage for the first time.

Even if this is a false positive (and that we are only guessing at this time), it's not ideal that we can't account for how certain files distributed to our users came to be.

I think we have to find a reproducible explanation for this, or seek help from Platypus developers, maybe they could help finding one.

**Comment by dessant** [comment] 2017-06-05 16:53
@tito, it would be interesting to know if running `create-osx-bundle.sh` again produces the same hash you shared, or a new one.

**Comment by tito** [comment] 2017-06-05 16:56
My guts still tell me that it would be highly probable that it's a real malware. Even if it's not reproducible because i have a new computer, and quanon reinstalled, then just publish the newest regenerated version?

**Comment by dessant** [comment] 2017-06-05 19:27
@jerrysoft-x, we have added a notice and made an announcement on the mailing list, sorry for the delay.

**Comment by akshayaurora** [comment] 2017-06-06 07:07
So on a clean new Mac Mini, I download a Platypus.app and pass it through the virus scanning tool.
It is still detecting malware inside the Platypus.app although a new one this time.

https://www.virustotal.com/en/file/09d6511a62a6965b0d69c7e92455ead70853c299bf1649ea52ba00e528cb34f4/analysis/1496732777/


I don't understand this, is this confirmed to be a false positive or is platypus really being distributed with these malware?

**Comment by akshayaurora** [comment] 2017-06-06 07:30
Platypus 5.2 https://www.virustotal.com/en/file/09d6511a62a6965b0d69c7e92455ead70853c299bf1649ea52ba00e528cb34f4/analysis/1496732777/
Platypus 5.1 https://www.virustotal.com/en/file/14a3595cc4e61f3e4e3051ddd0dde813119b6d2d2f19fa6271c259320b5b9d17/analysis/1496732938/
Platypus 5.0
https://www.virustotal.com/en/file/a14c9f2360feff9f07d5db5eeee238fbc602dccf574c3ebd1ce875fede43bdb1/analysis/1496733092/
Platypus 4.9
https://www.virustotal.com/en/file/f28ed1f0c3f4d4109c55d580dbf69950ad865fa7e91f32bc64d592546f382c6a/analysis/1496733164/
Platypus 4.8
https://www.virustotal.com/en/file/754d9153b92e32faf7e56a4e181de59c6f0b72b3208663042a22e1767d87cb05/analysis/1496733387/

This 4.8 version seems to be the one detected without any malware, should we just test building with this version ?

**Comment by akshayaurora** [comment] 2017-06-06 08:09
so a version of the Kivy.app created using 4.8 version of Platypus does pass the test https://www.virustotal.com/en/file/e9ee58d23ade5fa98faa5fb2030ee3a451d9646c0ee187431eca65f13d1ad009/analysis/1496735376/

**Comment by akshayaurora** [comment] 2017-06-06 08:09
Just for reference
shasum -a 256 Kivy.app/Contents/MacOS/Kivy 
eb0a89698eff83a62973e57f65a82cd0682b691c136a0e637acec3e799a52c67

**Comment by akshayaurora** [comment] 2017-06-06 09:07
Just created a platypus.app using sources and here is the result of it's scan 

Source scanned as clean but the .app scans as  
https://www.virustotal.com/en/file/463d4dbf6df96f5513b0bb4c877e86cad72ef5609ae394dd4582375388e015a1/analysis/1496739815/


Don't know what to make of this...

**Comment by gkanarek** [comment] 2017-06-12 14:49
Any word on this? I'd like to be able to make my Kivy app available to my users again... Lol.

**Comment by matham** [comment] 2017-06-12 20:09
We're working (basically @akshayaurora ) on getting new versions of the package built that don't show this issue (likely built on travis before we release it). We put downloads back up but removed the files with the issue. I guess we'll update the when the files are ready.

**Comment by gkanarek** [comment] 2017-06-13 14:34
OK. Any suggestions for the kivy sdk packager in the meantime?

**Comment by akshayaurora** [comment] 2017-06-17 09:53
The latest files are available here Python2 https://drive.google.com/open?id=0B1WO07-OL50_cTJiSEc4Rkh1V3M and here Python 3.5 https://drive.google.com/open?id=0B1WO07-OL50_UXNPTlIxNUNtVU0

@tshirtman already tested them
Could some one else please test them too and let us know if they work.

The procedure for creating your own Kivy.app is very simple though.

This methods expects you to have pip, python installed, frameworks of sdl2 example https://www.libsdl.org/release/SDL2-2.0.5.dmg same for sdl2_image, sdl2_mixer, gstreamer installed on your system.

```
git clone http://kivy-sdk-packager
cd kivy-sdk-packager
./create-osx-bundle.sh
```

This should create a Kivy.app using the system python in the current directory.
to create .dmg `./create-osx-dmg Kivy.app`

**Comment by gkanarek** [comment] 2017-06-19 15:19
I grabbed that py3.5 version. The "Kivy" file which had been flagged before is clean on VirusTotal. I can't scan the full Kivy.app (even archived) because it's too big, so I can't comment on that.

**Comment by devMoxie** [comment] 2017-07-26 16:17
I assume since this hasn't been closed, this is still an issue. Could we get an update? Thanks!

**Comment by komashu** [comment] 2018-01-11 01:26
why is this still open and not fixed if it is a false positive? is there an update?

**Comment by shreyatheslayer** [comment] 2018-01-30 00:02
Yea please i need to install it for my HSC SDD course,

**Comment by akshayaurora** [comment] 2018-01-30 04:43
@tito could you test the files The latest files are available here Python2 https://drive.google.com/open?id=0B1WO07-OL50_cTJiSEc4Rkh1V3M and here Python 3.5 https://drive.google.com/open?id=0B1WO07-OL50_UXNPTlIxNUNtVU0

I would like to put them up for download by people since it does not have the issue anymore.

**Comment by tomfitzphilly** [comment] 2018-02-13 04:32
I downloaded these both, and they scan clean through AVG.  However both seem to modify python 2.7

**Comment by tjGhani** [comment] 2018-02-20 02:55
Is 1.9.0 clean and safe to use until the next clean version is released?

**Comment by Zen-CODE** [comment] 2018-02-20 18:53
AVG tested clean on the first tests, so I doubt it's a good test. Malware bytes for OSX claims to detect it.

https://blog.malwarebytes.com/cybercrime/2016/07/new-mac-backdoor-malware-eleanor/

As McAfee reported the initial positive, a test with that would be first prize. I'll try testing that over the next few days with both.

@tomfitzphilly. How do they seem to modify python? What did you do to detect that?

@tjGhani. I would using the links for 1.10.0 akshayaurora posted above and scanning them with a tool that detects the threat (OSX/Backdoor.Eleanor). 1.10.0 contains many improvements, and helping us test that would be a great way to help out. Please post your findings if you do. Otherwise, I'll post my finding as soon as I can....

Thanks

**Comment by akshayaurora** [comment] 2018-02-20 20:18
https://drive.google.com/open?id=0B1WO07-OL50_cTJiSEc4Rkh1V3M
result
https://www.virustotal.com/en/file/32b23fe2da063fdae792babc3b9e8642eebf867e33c0f3b3f7e4e8e57497adf9/analysis/1519157415/
https://drive.google.com/open?id=0B1WO07-OL50_UXNPTlIxNUNtVU0
result
https://www.virustotal.com/en/file/615b585db52e12768cc484e3df32c0f79f3bc40afc16b0e66cea282296905931/analysis/1519157711/

**Comment by akshayaurora** [comment] 2018-02-20 20:22
@Zen-CODE since these packages pass I think we should put them up on the website, what say you ?

**Comment by Zen-CODE** [comment] 2018-02-21 06:31
Malware bytes detects no virus either. Let's close this ticket, and it can be re-opened if anyone provides a positive.

**Closed by Zen-CODE** 2018-02-21 06:31 UTC
Labels: important, needs-analysis, packaging, platform-osx
