### ISSUE TITLE
unable to install kivy on mac os

### ISSUE THREAD

**Issue by jcdufourd** [kivy/kivy#5345] opened 2017-08-22 13:29 UTC
### Versions

* Python: 2.7.9 Anaconda 2.2.0
* OS: Mac OS sierra 10.12.6 
* Kivy: 1.10.1 or development
* Kivy installation method: brew

### Description

one error blocks the process of installing kivy as described in https://kivy.org/docs/installation/installation-osx.html

### Code and Logs

```    gcc -bundle -undefined dynamic_lookup -L/Users/dufourd/anaconda/lib -isysroot /Developer/SDKs/MacOSX10.5.sdk -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/graphics/compiler.o -L/Users/dufourd/anaconda/lib -o build/lib.macosx-10.5-x86_64-2.7/kivy/graphics/compiler.so -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks -lm
    cythoning /private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/core/image/img_imageio.pyx to /private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/core/image/img_imageio.c
    building 'kivy.core.image.img_imageio' extension
    creating build/temp.macosx-10.5-x86_64-2.7/private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/core/image
    gcc -fno-strict-aliasing -I/Users/dufourd/anaconda/include -isysroot /Developer/SDKs/MacOSX10.5.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -I/private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/include -I/Users/dufourd/anaconda/include/python2.7 -c /private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/core/image/img_imageio.c -o build/temp.macosx-10.5-x86_64-2.7/private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/core/image/img_imageio.o -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks
    In file included from /private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/kivy/core/image/img_imageio.c:475:
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDataProvider.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:18:
    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFAvailability.h:21:10: fatal error: 'os/availability.h' file not found
    #include <os/availability.h>
             ^
    1 error generated.
     error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/dufourd/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-Is5Hew-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/v9/y_41x4rj4szg6jpdmrxxshcw0000gn/T/pip-OXZGBr-build/
```

**Comment by jcdufourd** [comment] 2017-08-23 11:56
upgrading to python 2.7.13 did not help
trying to download the kivy app did not help: latest v1.9.1 does not start

**Comment by amadeusxnet** [comment] 2017-08-23 12:12
Have you tried to reinstall/upgrade Xcode? The issue seems to be there.

**Comment by jcdufourd** [comment] 2017-08-23 13:51
Thanks for your message.
I installed the Xcode 9 beta and retried pip install kivy.
Nothing has changed.

**Comment by ab-anand** [comment] 2017-08-25 18:58
Did you install gcc?
`sudo yum install gcc`

**Comment by ganesha10** [comment] 2017-10-02 13:16
I did exactly as mentioned in this [link](https://kivy.org/docs/installation/installation-osx.html). No luck, gcc was unable to compile. So I tried something else which is mentioned [here](https://stackoverflow.com/questions/40771664/how-to-install-kivy-within-anaconda).
I just did the one which I suspect as the main reason why gcc failed to compile, cython version. I use the same cython version as mentioned at the comment, which is:
`pip install Cython==0.23`
and then
`pip install kivy`
and kivy is successfully installed. After that I did
`pip install -U Cython`
to get the latest cython. I tried a Hello World example, and it was running. Hope this help

**Comment by zheisenberg** [comment] 2017-10-10 01:14
what is your Cython version? >0.25 would fail

**Comment by Jianhaos** [comment] 2017-10-18 22:27
Cython 0.26.1 also works.

**Comment by matuqam** [comment] 2017-11-26 09:20
Check what your **active** version of cython is `cython --version`. I had the hardest time installing Kivy on macOs High Sierra, until I realised I had mutilple versions of cython and the active version was not compatible with a kivy install. My guess is somewhere in the installation process it calls cython and in my case it did not find what was installed with `pip install Cython==0.26.1`.

**Comment by HarryFengYX** [comment] 2018-02-24 04:34
I have the same issue, and I only solved it, along with many other issues by not using Mac to program anymore

**Comment by sanchit1802** [comment] 2018-03-30 18:10
I have had the same problem
Just paste this command into your terminal
pip install --user --verbose https://github.com/kivy/kivy/zipball/master

If you don't use the --user flag it will give an error

**Comment by valtersilva** [comment] 2018-05-13 16:07
Running into sort of the same problem here. Cython version is 0.23, but also tried with multiple versions. Any sugegstions?

Here is the error I get:



    /private/var/folders/dm/wnqk8wr52hn572dsf9_g_n7m0000gn/T/pip-install-yrm3qdh4/kivy/kivy/core/audio/audio_sdl2.c: In function ‘__pyx_pf_4kivy_4core_5audio_10audio_sdl2_9MusicSDL2_extensions’:
    /private/var/folders/dm/wnqk8wr52hn572dsf9_g_n7m0000gn/T/pip-install-yrm3qdh4/kivy/kivy/core/audio/audio_sdl2.c:4527:69: error: ‘MIX_INIT_MODPLUG’ undeclared (first use in this function)
       __pyx_t_2 = ((__pyx_v_4kivy_4core_5audio_10audio_sdl2_mix_flags & MIX_INIT_MODPLUG) != 0);
                                                                         ^
     error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/dm/wnqk8wr52hn572dsf9_g_n7m0000gn/T/pip-install-yrm3qdh4/kivy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/dm/wnqk8wr52hn572dsf9_g_n7m0000gn/T/pip-record-cj6y_54o/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/dm/wnqk8wr52hn572dsf9_g_n7m0000gn/T/pip-install-yrm3qdh4/kivy/

**Comment by nanodan** [comment] 2018-05-24 02:06
Same issue, tried multiple versions of Cython including those suggested here.

**Comment by bionoid** [comment] 2018-05-24 06:02
@valtersilva @nanodan that error is not the same as the issue report; it's caused by an upstream breaking change in sdl2-mixer. The easiest solution is to build kivy master branch which contains a fix. Alternatively downgrade sdl2-mixer to version 2.0.1

**Comment by matham** [comment] 2019-04-29 04:19
We hit this issue when trying to make a new a [kivy conda release](https://github.com/conda-forge/kivy-feedstock/pull/3). But updating and releasing the conda recipes for sdl2, this seems to have fixed the issue. So I'm going to assume this would also fix the original issue and I'm closing this.

Feel free to re-open if it doesn't fix it.

**Closed by matham** 2019-04-29 04:19 UTC
