### ISSUE TITLE
Examples: SVG broken

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy/kivy#5006] opened 2017-02-19 20:48 UTC
### Versions

* Python: 2.7, 3.5
* OS: Win8.1, 64bit
* Kivy: master, wheels

### Description

SVG example just won't even start, but with py2 it at least returned this:

> File: kivy\lib/libtess2/Source/priorityq.c, Line 413
Expression: LEQ( **(i+1), **i )
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by dessant** [comment] 2017-02-19 20:57
May be a duplicate of https://github.com/kivy/kivy/issues/3693. It seems to be an issue with the svg module, not just the example.

**Closed** 2017-02-19 21:06 UTC
Labels: examples
